slaclab/pydm

pydm/widgets/label.py

Add alarm sensitive border to labels.  Closes #3.

Label alarm improvements

---

examples/slider/slider.ui
pydm/widgets/old_slider.py
pydm/widgets/old_slider_qtplugin.py
pydm/widgets/slider.py
testing-ioc.py

Replace the slider widget with a newer, better one that includes slider limit indicators, a value indicator, and alarm sensitivity.   Closes #4.

New slider

---

pydm/widgets/pushbutton.py

Add write-access and connection state support for push button.

---

pydm/widgets/checkbox.py

Initialize enable state for checkbox.

---

pydm.py
pydm/application.py
pydm/display_module.py
pydm/main_window.py

Add the ability to pass command line arguments to Display subclasses, for them to handle.  Useful for building dynamic panels.

Command line arguments for Displays

---

pydm/main_window.py
pydm/pydm.ui
pydm/pydm_ui.py

Adds support for showing the file path for the currently displayed file.
Closes #19

Toggle title/file path in title bar

---

pydm/data_plugins/pyepics_plugin.py

Check for a valid value before emitting new value signals.

---

designer_plugin.py
examples/spinbox/spinbox.ui
pydm/data_plugins/plugin.py
pydm/data_plugins/psp_plugin.py
pydm/data_plugins/pyepics_plugin.py
pydm/widgets/channel.py
pydm/widgets/spinbox.py
pydm/widgets/spinbox_qtplugin.py

This should fix #37, except alarm sensitive text.

Add SpinBox, add low/high limit signals

---

pydm/widgets/related_display_button.py

Related display button crash fix

---

designer_plugin.py
examples/symbol/go.svg
examples/symbol/stop.svg
examples/symbol/symbol.ui
pydm/PyQt/QtCore.py
pydm/PyQt/QtSvg.py
pydm/PyQt/__init__.py
pydm/widgets/symbol.py
pydm/widgets/symbol_qtplugin.py

Implemented the symbol widget: A widget that takes an enum channel, and displays a different image depending on the value of the channel.

Symbol Widget

---

pydm/widgets/image.py

Fix broken color map calculation.

---

pydm/application.py
pydm/data_plugins/__init__.py
pydm/data_plugins/epics_plugin.py
pydm/data_plugins/epics_plugins/psp_plugin.py
pydm/data_plugins/epics_plugins/pyepics_plugin.py

There were a bunch of issues with plugin loading, especially under python 3.  Importing should work under both Python 2 and 3 again.

Fix crashing issues when plugin loading fails.

---

examples/push_button/push_button.ui
pydm/widgets/pushbutton.py

Updated example to use confirmation on STOP button.
Attn. @lpiccoli27

ENH: Adding confirmation dialog capability to PyDMPushButton

---

pydm/widgets/waveformtable.py

FIX: Waveformtable should use the waveform_signal instead of value_signal.

---

pydm/widgets/timeplot.py
pydm/widgets/waveformplot.py

Fix problem with invalid curves on timeplot and waveformplot  when use  designer
Solve #102

Fix problem with invalid curves on timeplot and waveformplot 

---

pydm/widgets/waveformplot.py
pydm/widgets/waveformplot_curve_editor.py
pydm/widgets/waveformplot_table_model.py

Bug fixes and addition of some properties were to PyDMWaveformPlot:
- Add lineStyle property to set the type of line to connect the data
points. Substitute the old connect_points property;
- Add lineWidth property;
- Add symbolSize property;
- Increase number of options for symbol property.
- Improve curve editor to handle new properties. 
- Fix documentation of new properties. 
- Bug fix: check if y_waveform is None before plotting.

Improve PyDMWaveformPlot

---

examples/scale_indicator/scale.ui
pydm/widgets/qtplugins.py
pydm/widgets/scale.py

Hi,
Recently I needed a widget equivalent to the one described in issue #39 . So I started to write a class for it.
I tried to keep it simple. By now, a graphical pointer is drawn to indicate channel current value, but it is possible to add the option to draw a bar instead in the future.
Possible improvements:
- implement change of orientation
- indicator type option (pointer or bar)
Thanks,
Laís

Scale indicator

---

examples/oscilloscope/scope.ui
pydm/widgets/qtplugin_base.py
pydm/widgets/qtplugins.py
pydm/widgets/timeplot_qtplugin.py
pydm/widgets/waveformplot_qtplugin.py

This finally closes #95 .
Thank you @laispc for adding the group functionality!
Here is a screenshot showing how it was and how it is now with this PR:

ENH: Divide the widgets in categories (Display, Input, Plot, Drawing).

---

pydm/widgets/waveformtable.py

This work was done by @fernandohds564: Adds the ability to edit waveform PVs using the table, adds options to interpret a single waveform as multiple columns, adds the ability to add labels to rows and columns.

PyDM Waveform Table improvements.

---

examples/push_button/push_button_alarm.ui
pydm/widgets/pushbutton.py

ENH: Pushbutton now respect ALARM_CONTENT and changes the color of text.

---

pydm/widgets/__init__.py

ENH: Bring widgets import to __init__.py making it easier for users.

---

pydm/utilities/colors.py

This PR was created only to test if Travis will work.

fix formatting of colors module.

---

docs/source/application.rst
docs/source/index.rst
pydm/application.py

Adds sphinx docs for PyDMApplication.  Closes #161.

Document the PyDMApplication class.

---

pydm/application.py
pydm/main_window.py
pydm/pydm.ui
pydm/pydm_ui.py
scripts/pydm

This closes #149 .
Added menu option to:
- Hide Menu Bar (--hide-menu-bar)... also possible to get toggle using CTRL+M shortcut
- Hide Status Bar (--hide-status-bar).
Attn. @ZLLentz @teddyrendahl @joaopmrod

ENH: Adding Show/Hide Menu Bar & Status Bar.

---

pydm/widgets/drawing.py

@hhslepicka figured out how to get the path to a .ui file being edited in designer, so now we can actually show image files in designer when they are specified with relative paths.
The behavior has one small 'gotcha':  If you open a new form (with no associated file yet, because it hasn't been saved), make an image with a relative path, then save the form into a different directory, the relative path you specified is no longer valid, so your image will break.

Fix relative image path handling so they work in Designer.

---

pydm/widgets/image.py

Fix crashes in PyDMImageView with (0,0) images.

---

examples/image_view/image.ui
pydm/widgets/colormaps.py
pydm/widgets/image.py

Adds a pyqtProperty to ImageView that lets you select colormap presets from an enum.  This will close issue #142.

Add colorMap property to ImageView

---

examples/external_tool/dummy_tool.py
examples/external_tool/lookup_path/new_tool.py
examples/external_tool/lookup_path/root_tool.py
examples/testing_ioc/pydm-testing-ioc
pydm/application.py
pydm/data_plugins/__init__.py
pydm/main_window.py
pydm/pydm.ui
pydm/pydm_ui.py
pydm/tools/__init__.py
pydm/tools/tools.py
pydm/widgets/base.py
pydm/widgets/image.py
pydm/widgets/line_edit.py

After merged this closes #104.

ENH: External Tools Hooks

---

examples/camviewer/camviewer.py
examples/camviewer/marker.py

FIX: Fixing camviewer after changes to PyDMImageView and colormap.

---

examples/ca-filtering/README.md
examples/ca-filtering/ca_filtering.ui
examples/ca-filtering/test.db

ENH: Add Channel Access Filtering example.

---

pydm/about_pydm/__init__.py
pydm/about_pydm/about.py
pydm/about_pydm/about.ui
pydm/about_pydm/contributors.txt
pydm/main_window.py
pydm/pydm.ui
pydm/pydm_ui.py

This adds an 'About PyDM' item in the File menu which pops up a little window with info about PyDM.  It lists version info, lists all external tools in use, all data plugins in use, and most importantly, everybody who has committed code to PyDM.

Add an 'About' screen.

---

pydm/widgets/related_display_button.py
pydm/widgets/shell_command.py

This closes #225 .
Attn. @mattgibbs

ENH: Add showIcon property to related display and shell command buttons.

---

.travis.yml
run_tests.py

CI: Clean up a bit the .travis.yml file.

ENH: Add run_tests.py to simplify how to launch the tests.

---

examples/scale_indicator/scale.ui
pydm/widgets/scale.py

Hi,
This pull request implements some new properties for scale widget, such as orientation, inverted appearance, flip scale, tick color and bar indicator. Some small correction were done too.
The example file was adapted to show these new features. What do you think about them? :)
Thanks,
Laís

Scale upgrade

---

README.md
conda-recipe/build.sh

This solves #234 .
I tested it building the conda package locally and installing at a clean environment.
Attn. @ZLLentz

ENH: Add the PYQTDESIGNERPATH to the conda environment.

---

pydm/application.py

See #244 and #245 for motivation

MAINT: Switch tool print banner to log

---

pydm/tests/utilities/test_colors.py
pydm/tests/utilities/test_iconfont.py
pydm/tests/utilities/test_macro.py
pydm/tests/utilities/test_remove_protocol.py
pydm/tests/utilities/test_units.py
pydm/tests/utilities/test_utilities.py
pydm/utilities/__init__.py
pydm/utilities/iconfont.py
pydm/utilities/macro.py
pydm/utilities/remove_protocol.py
pydm/utilities/units.py

Add tests for utilities, fix some docstrings and add some missing docstrings.

TST: Add tests for utilities.

---

docs/source/conf.py
docs/source/index.rst
docs/source/utilities/index.rst
pydm/utilities/colors.py
pydm/utilities/iconfont.py

DOC: Improved docstrings at colors and iconfont.
After merged this closes https://github.com/slaclab/pydm/issues/279 .

DOC: Adding utilities to the documentation tree.

---

pydm/tests/conftest.py
pydm/tests/widgets/test_pushbutton.py
pydm/utilities/iconfont.py
pydm/widgets/pushbutton.py

TST: Test for PyDM Push Button

---

pydm/tests/widgets/test_base.py
pydm/tests/widgets/test_frame.py
pydm/widgets/base.py
pydm/widgets/frame.py

BUG: Update the _alarm_flags to actually enable style updating when the alarm severity changes
STY: Fix line width and PEP8 issues.
Also close #254

TST: Add unit tests for PyDMFrame.

---

pydm/tests/widgets/test_drawing.py
pydm/widgets/drawing.py

TST: Unit Tests for Drawing Widgets

---

pydm/tests/widgets/test_shell_command.py
pydm/tests/widgets/test_spinbox.py
pydm/widgets/spinbox.py

STY: Fix comment indentations and spelling error.
Close #276

TST: Add PyDMSpinBox tests

---

pydm/tests/widgets/test_colormaps.py

TST: Add unit tests for the PyDMColorMap widget.

---

pydm/tests/widgets/test_base.py
pydm/widgets/base.py

FIX: Reset self._channels when updating channel property.

---

pydm/widgets/waveformplot.py

FIX: Fix the case in which y_waveform shape is 0.

---

pydm/tests/widgets/test_enum_combo_box.py
pydm/tests/widgets/test_frame.py
pydm/tests/widgets/test_label.py
pydm/widgets/enum_combo_box.py

ENH: Update variable naming for test_enum_strings_change() in test_label.py
Close #253

TST: Add unit tests for PyDMEnumComboBox

---

examples/camviewer/camviewer.ui
examples/image_processing/image_view.py
examples/image_processing/image_view.ui
examples/image_view/image.ui
pydm/widgets/image.py

MNT: Refactored the image processing example to work with the new callback.
I also took the opportunity to implement a stop and start on the timer when we reach and leave the redraw_image method. This will ensure that we don't try to process a new image while we have not yet finished with the previous one.

ENH: Add  method to Image View so users can easily hook-up data processing code of their own.

---

pydm/widgets/waveformplot.py

Small change to prevent unnecessary plot redraws when no data has changed.  Reduces CPU load quite a bit when plotting data that updates less frequently than the plot's update rate.
With this PR, if any curve in the plot updates, the plot will redraw all curves on the next update.  It could be made more granular, and only 'redraw' curves that have new data, but I have a hunch that isn't actually any more performant.  If anybody wants to investigate and change again, it is more than welcome :).

Don't re-draw waveform plots unless the data has changed.

---

appveyor.yml
pydm/application.py
pydm/qtdesigner.py
pydm/tests/utilities/test_stylesheet.py
pydm/tests/widgets/test_lineedit.py
pydm/tests/widgets/test_pushbutton.py
pydm/tests/widgets/test_rules.py
pydm/utilities/stylesheet.py
pydm/widgets/base.py
pydm/widgets/qtplugin_base.py
pydm/widgets/qtplugins.py

This PR fixes some bugs found since the last merges in the code as well as refactor the way we set the stylesheet on the QtDesigner by no longer using the QTimer and now relying on the FormWindowManager.
@mattgibbs after this is merged we are good for a release.

MNT: Stylesheet & others

---

examples/actions/actions2.ui
pydm/application.py
pydm/main_window.py
pydm/tests/widgets/test_base.py
pydm/tests/widgets/test_rules.py
pydm/widgets/base.py
pydm/widgets/qtplugin_extensions.py
pydm/widgets/rules.py
pydm/widgets/rules_editor.py
pydm/widgets/symbol.py

This PR adds new properties to the Rules list and also fix some bugs with the RulesEngine/Dispatcher.
Test is added to ensure that we unregister properly a widget.

ENH: Adding new properties to Rules.

---

pydm/application.py
pydm/main_window.py

FIX: Related Display button opening properly in New Window for Windows.

---

pydm/application.py
pydm/data_plugins/plugin.py
pydm/main_window.py
pydm/widgets/channel.py
pydm/widgets/embedded_display.py

FIX: Make sure that establish_connection and remove connection can be called multiple times without prejudice to other channels connected to a same plugin.

FIX: Make sure we expand vars and user when opening files.

---

examples/testing_ioc/pydm-testing-ioc
pydm/tests/conftest.py
pydm/tests/test_baseplot.py
pydm/tests/widgets/test_baseplot.py
pydm/tests/widgets/test_lineedit.py
pydm/tests/widgets/test_timeplot.py
pydm/utilities/remove_protocol.py
pydm/widgets/baseplot.py
pydm/widgets/timeplot.py

TST: Also create a few unit tests for Base Plot and Time Plot.
Motivations:
To create a charting tool  based on PyDM as a replacement for StripTool, which is a charting tool based on Motif, a framework that is outdated and has dwindling user base, update, and support.
By using PyDM, this new charting tool will have gained the better look-and-feel, performance, and better maintainability advantages offered by Python and the modern GUI framework Qt. The objective therefore is to match feature-by-feature between this PyDMCharting application with StripTool while also providing performance, responsiveness, organization, and appearance improvements wherever possible over StripTool.
Major features:
- Charting with higher resolution, dynamic axis scaling, and better, more responsive mouse …

ENH: Enhance TimePlot and related modules to support PyDM Charting features

---

README.md

DOC: Update README to reflect changes for qtpy.

---

pydm/data_plugins/epics_plugin.py
pydm/data_plugins/epics_plugins/caproto_plugin_component.py

Attn. @tacaswell and @ronpandolfi 
In order to use it, one must export the environment variable:
```sh
export PYDM_EPICS_LIB=CAPROTO
```

ENH: Add caproto as an option for EPICS Plugin.

---

pydm/data_plugins/__init__.py

Fix bug in data_plugins file

---

pydm_launcher/main.py

Make some of the command line help text a little more clear.

Tweak the text on command line argument help.

---

pydm/tests/widgets/test_shell_command.py

Sleep up a bit the tests and also avoid the use of `ping`.

TST: Fix shell command tests. Avoid running ping.

---

pydm/application.py
pydm/main_window.py
pydm/tests/widgets/test_timeplot.py
pydm/tools/__init__.py
pydm/widgets/base.py
pydm/widgets/display_format.py

This PR follows the idea of removing the coupling between PyDM Widgets and functionality and the PyDMApplication and PyDM Main Window components.

ENH: Move tools out of Main Window and Application

---

pydm/widgets/qtplugin_base.py

ENH: Remove whatsThis from widget plugins.

---

pydm/widgets/scale.py

ENH: Add option to Scale Widget to specify user defined limits.

---

pydm/tests/conftest.py
pydm/tests/widgets/test_drawing.py
run_tests.py

TST: Adjust test_drawing that was relying at `is_pydm_app` and was never going to be hit anyway since it was based on the designer.

TST: Fix for OSX to pass.

---

pydm/data_plugins/epics_plugins/caproto_plugin_component.py
pydm/data_plugins/epics_plugins/pyepics_plugin_component.py

Bumped at this issue after releasing 1.6.2.
This is an important fix and we must cut 1.6.3 after that.

FIX: Address ValueError when using comparison of numpy arrays in an if statement.

---

pydm/tests/widgets/test_drawing.py
pydm/widgets/drawing.py

This PR also adjust the tests and code to now behave well when not using `PyDMApplication`.

ENH: Add Pen Cap and Join Styles to Drawing Widgets 

---

azure-pipelines.yml

... and not add it to version control.

CI: Fix docs deploy to clean up artifacts folder

---

pydm/tests/widgets/test_logdisplay.py
pydm/widgets/logdisplay.py

This closes  #474.
@teddyrendahl do you mind to check your test with this fix?
I tested it locally and it is working properly.

FIX: Ensure that PyDMLogDisplay cleans up the handler.

---

azure-pipelines.yml
azure-test-template.yml
dev-requirements.txt

Saw this one so adding yet another dependency to the dev-requirements.txt.
More details here: https://github.com/tonybaloney/pytest-azurepipelines

CI: Use pytest-azurepipelines for tests and coverage upload.

---

pydm/widgets/slider.py

When PyDMSlider with undefined limits is rendered, it remains interactive, even though it shouldn't. Dragging the slider results in the crash.
Fixed by manipulating enabled state of the internal slider explicitly.

BUG: fixed enabled state of PyDMSlider when limits are undefined

---

azure-pipelines.yml
azure-test-template.yml
pydm/tests/widgets/test_enum_button.py
pydm/widgets/rules_editor.py

- CI: Remove constrains on conda=4.6.8 now that the bug with windows is fixed.
- CI: Install dev-requirements with conda.
- CI: Add useful debug information before test to help troubleshoot in the future.

CI: Fix Windows Build with Python 3.6 & 3.7

---

pydm/tests/utilities/test_utilities.py

TST: Remove hardcoded paths from test.

---

MANIFEST.in

Add dev-requirements.txt to MANIFEST.in

---

conda-recipe/build.sh

See https://github.com/pcdshub/typhon/pull/203 for full explanation.

FIX: PYQTDESIGNERPATH variable should not be expanded

---

azure-pipelines.yml
azure-test-template-win.yml
azure-test-template.yml

Solving issues with how conda must be handled in a Windows environment.

CI: Separate Windows template because Windows is SPECIAL.

---

pydm/widgets/baseplot.py

This PR is related to issue #503.

Crosshair deselection was broken due to bug in pyqtgraph.

---

pydm/widgets/baseplot.py

Proper cleanup of curve items will ensure that the channels are also disconnected.
Closes #515

FIX: Ensure that curve items are properly deleted.

---

pydm/data_plugins/epics_plugins/pyepics_plugin_component.py
pydm/data_plugins/plugin.py
pydm/tests/widgets/test_channel.py

- FIX: Use proper key at `remove_connection`
- FIX: Force `notified` at channel when `add_connection`
- FIX: Remove unused `Slot` annotation at PyEpics plugin.

FIX: Couple of fixes at Plugins

---

azure-test-template-win.yml
azure-test-template.yml
pydm/main_window.py
pydm/tests/widgets/test_base.py
pydm/tests/widgets/test_spinbox.py
pydm/widgets/base.py
pydm/widgets/baseplot.py
pydm/widgets/embedded_display.py
pydm/widgets/image.py
pydm/widgets/related_display_button.py
pydm/widgets/shell_command.py
pydm/widgets/slider.py
pydm/widgets/spinbox.py

Maintenance PR to merge the latest fixes from Master into 2.0.

MNT: Merge latest from Master into 2.0

---

docs/source/configuration.rst

Feel free to change, if I misinterpreted some of the variables.

Added missing documentation for environment variables

---

pydm/widgets/channel.py

FIX: Disconnect widget when connection is closed for channel.

---

pydm/about_pydm/contributors.txt

This PR adds more contributors to the contributors list in the "about" screen.  Sorry it took so long, @KurtJacobson and @ivany4!

Update contributors list

---

LICENSE.md

Truly, a PR that will revolutionize PyDM.

Update license year.

---

pydm/widgets/baseplot.py

ENH: Add two new properties to plots for labels at X and Y axes.

---

examples/scatterplot/scatterplot.ui
examples/timeplot/timeplot.ui
examples/waveformplot/waveform_plot.ui
pydm/widgets/timeplot.py

FIX: Disable autoSIPPrefix for TimePlot.

---

pydm/application.py

Fixes #551 for stylesheet and other arguments that are missing.

FIX: Passing missing arguments to child processes

---

pydm/widgets/byte.py
pydm/widgets/enum_button.py
pydm/widgets/logdisplay.py

- Enum Button
- Byte Widget
- Log Display

FIX: Make widgets that inherit from QWidget properly apply Stylesheets

---

pydm/utilities/__init__.py

FIX: We must expand user and var at extra path.

FIX: We must split by pathsep the DISPLAYS_PATH.

---

examples/exception/demo.py
pydm/exception.py

Motivation comes from https://github.com/pcdshub/lucid/issues/11 and other places including PyDM launcher itself.

ENH: Add excepthook handler utility.

---

pydm/main_window.py

The title says it all!  Fixes #622

Re-implement the code that enables the 'Edit in Designer' menu item.

---

examples/related_displays/dynamic_text.ui
pydm/widgets/related_display_button.py

Closes #625
Attn. @tashasummers

ENH: Expose Text as a property for Rules at RelatedDisplayButton.

---

pydm/data_plugins/epics_plugins/pyepics_plugin_component.py
pydm/widgets/rules.py
pydm_launcher/main.py

Many of the issues being addressed here were found in the wild while dynamically creating and destroying widgets.

FIX: Address some issues with Rules and adds improvements on error handling

---

pydm/widgets/byte.py

@prjemian do you mind to give it a try with this branch and report back if the issue is fixed?
Closes #576 .

FIX: Address issue with Horizontal Byte Indicator not respecting BigEndian.

---

pydm/tests/widgets/test_rules.py
pydm/widgets/rules.py

Closes #643 - can happen when iterating over keys in `run`.

FIX: Rules widget_map can change during iteration

---

pydm/widgets/related_display_button.py

BUG: Related display button duplicates

---

examples/shell_command/shell_command.ui
pydm/widgets/shell_command.py

ENH: Add output redirection option

---

pydm/utilities/__init__.py

DOC: Fix docstring in find_file for base_path

---

pydm/data_plugins/epics_plugins/pyepics_plugin_component.py
pydm/main_window.py

FIX: Temporary fix for pyepics callbacks not being cleaned up for connection and access.
Motivation:
https://github.com/pcdshub/lucid/issues/73
and
https://github.com/pyepics/pyepics/issues/208

FIX: Temporary patch for pyepics data plugin

---

pydm/widgets/base.py
pydm/widgets/enum_combo_box.py

ENH: Show address tooltip when disconnected

---

pydm/exception.py

Closes https://github.com/pcdshub/lucid/issues/67

FIX: Deduplicate errors when handling unhandled exceptions.

---

examples/template_repeater_json/main.ui
examples/template_repeater_json/template.ui
pydm/widgets/template_repeater.py

ENH: Allow JSON string at dataSource property for TemplateRepeater.

---

pydm/widgets/enum_button.py

Closes #674 
@klauer do you mind trying with this branch and see if the issue goes away?

FIX: Hide widgets before deleting to make sure they don't ghost around.

---

pydm/widgets/base.py
pydm/widgets/baseplot.py

FIX: Middle-click Adjustments

---

pydm/about_pydm/contributors.txt

Welcome, @jacquelinegarrahan! 🎉

DOC: Adding new contributor

---

pydm/about_pydm/about.py
pydm/data_plugins/__init__.py
pydm/tests/test_data_plugins_import.py
pydm/widgets/template_repeater.py

Initialize data plugins only on demand to avoid circular imports

---

examples/push_button/latch_mode.ui
pydm/tests/widgets/test_pushbutton.py
pydm/widgets/pushbutton.py

Add "latch" model to the push button widget. This implements a write on initial press and upon release with configurable values for both.

Push button latch

---

examples/symbol/symbol.ui
pydm/tests/widgets/test_symbol_editor.py
pydm/widgets/qtplugin_extensions.py
pydm/widgets/qtplugins.py
pydm/widgets/symbol.py
pydm/widgets/symbol_editor.py

Added symbol extension in designer to simplify the process of editing the symbols and corresponding states for a PyDM symbol widget (#374 ) –– updated pull request to include testing of symbol extension

Symbol extension

---

pydm/exception.py

Moves queue import to six for 2/3 compatibility

BUG: move queue import to six

---

pydm/tests/widgets/test_shell_command.py
pydm/widgets/shell_command.py

FIX: Expand User and Env Vars for Shell Command

---

.gitignore
docs/source/widgets/drawing.rst
pydm/tests/widgets/test_drawing.py
pydm/widgets/__init__.py
pydm/widgets/drawing.py
pydm/widgets/qtplugins.py

fixes #578 in support of translating MEDM's .adl screen files into PyDM's .ui file format

add polyline drawing widget

---

pydm/tests/widgets/test_rules.py
pydm/widgets/rules.py

FIX: Make sure channels with enum use the proper value

---

docs/source/conf.py
docs/source/installation.rst

This updates the installation instructions to reflect that pydm itself is available on conda-forge now, which simplifies installation even more.

Update conda installation instructions.

---

pydm/application.py
pydm/display.py
pydm/utilities/__init__.py

find adl files when called from related displays

---

pydm/widgets/__init__.py

Add PyDMArchiverTimePlot to __init__.py

Make PyDMArchiverTimePlot importable

---

pydm/connection_inspector/connection_inspector.py

Adds a button to copy the list of all PVs from the connection inspector.

ENH: Add a button for copying the list of all PVs to the clipboard from the connection inspector

---

pydm/widgets/enum_combo_box.py

Disabling the mouse wheel for the PyDMEnumComboBox.

Deactivating the mouse wheel for the PyDMEnumComboBox 

---

docs/source/data_plugins/calc_plugin.rst
docs/source/data_plugins/local_plugin.rst
docs/source/stylesheets.rst
docs/source/widgets/archiver_timeplot.rst
docs/source/widgets/curve_editor.rst
docs/source/widgets/index.rst
docs/source/widgets/utilities.rst
pydm/utilities/__init__.py
pydm/widgets/archiver_time_plot.py
pydm/widgets/baseplot.py
pydm/widgets/display_format.py

Closes #852 
WIP - may be some more to fix

DOC: fix miscellaneous docstring issues

---

azure-pipelines.yml
docs/source/widgets/drawing.rst
pydm/tests/test_plugins_import.py
pydm/tests/widgets/test_drawing.py
pydm/widgets/__init__.py
pydm/widgets/drawing.py
pydm/widgets/qtplugins.py

new PyDMDrawingIrregularPolygon widget

---

pydm_launcher/main.py

Add a simple `pydm --profile` option that invokes cProfile for the duration of your GUI.
Partial sample output (full output is too long for github pull request text):
<details>
```
6097323 function calls (5938713 primitive calls) in 49.690 seconds
Ordered by: cumulative time
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
1    0.000    0.000   31.825   31.825 /cds/home/z/zlentz/pydev/pydm/application.py:116(exec_)
1    5.912    5.912   31.825   31.825 {function PyDMApplication.exec_ at 0x7fc5d85bcb80}
288/148    0.004    0.000   22.050    0.149 /cds/home/z/zlentz/pydev/pydm/display.py:26(load_file)
1    2.124    2.124   19.996   19.996 /cds/home/z/zlentz/pydev/pydm/application.py:74(__init__)
1    0.000    0.000   17.073   17.073 …
```

ENH: add a quick cProfile onto pydm launcher

---

pydm/widgets/related_display_button.py
pydm/widgets/shell_command.py

We need password validation for these two widgets, just like what PushButton does. I study how the PushButton widget to validate password and have implement the same functionality for the two widgets.

ENH:add password validation for these two widgets.

---

pydm/widgets/drawing.py

The PyDMDrawingLine widget has some unintuitive behavior with its bounding boxes. It's currently being drawn via:
1. draw a line from the left side of the bounding box to the right side
2. rotate the line to match the rotation value
But what if I want a really long vertical line? Well, unless I make the bounding box very wide, it looks like this:
After this diff, the same widget looks like:
This also supports arbitrary angles:
Screenshots include arrows to make it clear that the line isn't getting clipped by the bounding box, and is instead stopping at the boundary appropriately.

ENH: PyDMDrawingLine length on rotation

---

pydm/widgets/shell_command.py

Adds new designer property to set environment variables along with a shell command.  
address issue #930 
Tested on the example shell command ui file.
Auto documentation will add the new properties.

Adds new PyDMShellCommand environment variable property 

---

pydm/tests/widgets/test_base.py

Adds a test case to confirm middle clicking on a widget that inherits from PyDMWidget will copy the name of the connected PV to the clipboard.
Confirmed that this test would have caught the issue resolved in #948

TST: Add test case for PyDM widget middle-click functionality

---

pydm/widgets/scale.py

Same deal as #959
Fix type errors, add type hints, flake 8 fixes.
Verified the widget looks fine now with python 3.10. Verified existing examples still look fine.

MAINT: Update scale indicator to be compatible with python 3.10/PyQt5

---

docs/source/installation.rst

DOC: Update installation guide with note about designer

---

README.md
docs/source/tutorials/action/designer_main.rst

Someone new to PyDM recently went through the tutorial and made a couple suggestions. This PR removes some obsolete installation instructions from the README and points to the installation guide in the documentation instead. Also updates a couple PVs used in the tutorial to reflect the correct names.

DOC: A couple updates to new user documentation

---

pydm/tests/conftest.py
pydm/widgets/drawing.py
pydm/widgets/rules.py

Updated widgets/drawing.py and widgets/rules.py to add 3 new rules for the drawing line widget that allow for dynamically adjusting color,style, and thickness .

Adding rules to pydm drawing line 

---

pydm/widgets/archiver_time_plot.py
pydm/widgets/archiver_time_plot_editor.py
pydm/widgets/timeplot.py

Follow up to #1061 
Add checkable columns to the PyDMArchiverTimePlotCurvesModel for the Live Data and Archive Data columns. These 2 columns should be checkboxes since they are boolean values.
These will be displayed as checkboxes in a QTableView.

ENH: Add checkable columns to Archiver Plot Model

---

pydm/data_plugins/archiver_plugin.py
pydm/data_plugins/plugin.py

https://github.com/spyder-ide/qtpy/blob/1d2a1eae43bda2a3d0efef605cafc5462389ec03/qtpy/compat.py#L191
Pyside6/Qt6 Upgrade Pt 2

MNT: Replace PyQt-specific sip library with wrapper provided by pyqt

---

pydm/widgets/analog_indicator.py
pydm/widgets/scale.py

Instead use the value of the macro stated in the docs https://doc.qt.io/qt-6/qwidget.html#QWIDGETSIZE_MAX.

MNT: remove usage of QWIDGETSIZE_MAX macro, since only PyQt defines it and not PySide

---

CONTRIBUTING.rst

make table render right on github

DOC: format table correctly in CONTRIBUTING doc

---

pydm/widgets/drawing.py

I want to use rules to use PVs to populate start angle and span angle in drawingPie widget.

ENH: add two rules to PyDMDrawingPie widget

---

docs/source/configuration.rst
docs/source/tutorials/intro/launcher.rst
pydm/application.py
pydm/main_window.py

Also updated some of the grammar on the configuration page.
Closes #1063

FIX: misc. nav bar, homefile behavior tweaks

---

pydm/tests/widgets/test_datetime_edit.py
pydm/tests/widgets/test_datetime_label.py

putting this into its own PR so we can merge quickly and stop failing pre-commit in other pending PRs

STY: add missed precommit changes (when precommit was accidently disabled)

---

pydm/widgets/archiver_time_plot.py

This PR is to address a bug in the formula curves where they were not updating when the plot x-axis moves and the formula's archive variables fetch new data from the archiver, the formula would not update with the new data.

FIX: Formula curves not updating when composite curves fetch new data from archive
