slaclab/pydm

examples/enum_combo_box/enum_combo_box.ui
pydm/widgets/enum_combo_box.py
pydm/widgets/enum_combo_box_qtplugin.py

Add a combo box widget to control an enum PV, as well as a new example file for it.  Progress towards #5.

Add a new widget to control the value of an enum PV via a combo box.

---

pydm/data_plugins/pyepics_plugin.py
pydm/widgets/enum_combo_box.py

Fixes #27.
Two separate bugs combine to cause the issue:
1) When connecting put signal types in pyepics plugin, sometimes some would get skipped, if not all types were present on the target channel.
2) The enum combo box widget would not update the combo box's state after changing the value.

Enum combo box issue

---

pydm/data_plugins/plugin.py
pydm/data_plugins/pyepics_plugin.py

Some PVs return units as bytes, so with this change pydm doen's break in this cases.

Fix to units work with bytes type

---

pydm/application.py
pydm/main_window.py

FIX: Checks wether or not the module file has an intelclass.

---

pydm/widgets/label.py
pydm/widgets/slider.py

Hi,
This pull request fix a problem happening with PyDMLabel and PyDMSlider: when channel is disconnected, their colormaps are **not** set to  ALARM_DISCONNECTED.
This happens because method 'alarmSeverityChanged' (which changes stylesheet) is called only when a new value is received. Once the channel the disconnected, no new value is received, thus stylesheet is never updated.

[Label and Slider] Update colormap when channel is disconnected

---

pydm/application.py
pydm/data_plugins/psp_plugin.py

1. Event filter was not being installed on any of the widgets because it was indented into the NameError exception block so it would only ever get installed if pyDM was unable to connect to a PV.  Also, the event filter was catching parent classes as well when called and therefore can't find the "channels" method for things like QWidget and QCombobox.  Moving the installEventFilter command into the hasattr check block fixes this.
2.  QTooltip and QClipboard were not being imported from QtGui
3.  PyDMChannel class must have changed under at some point because the event filter was performing a regex match to strip out some sort of "scheme" from the PV address string, but whatever that was it doesn't seem to exist anymore so the match always fails returning a NoneType.  Simply getting rid of …

Fixed middle-click tooltip and clipboard functionality

---

designer_plugin.py
examples/byte_indicator/byte_indicator.ui
pydm/widgets/byte.py
pydm/widgets/byte_qtplugin.py
pydm/widgets/qtplugin_base.py
testing-ioc.py

Here's my implementation of the byte widget.  It is pretty simple, just shows individual bits of a integer value.  There are a few properties to change the way it looks and behaves.  This will satisfy #35.
@laispc I think this is different than your byte widget, because it only allows for two states on each indicator, on or off.  I like the idea for yours, but it makes the widget more complicated to use, and at least a SLAC, most of the requests for this only care about binary states.  @hhslepicka is working on a Symbol widget, that displays a single multi-state value, and I'm hopeful that using several symbol widgets will be a solution that works for your use case.  Stay tuned.

Byte widget

---

pydm/widgets/byte.py

Hi,
PyDMByteIndicator imports QStringList from QtCore. However, this class does not exist in PyQt5 (http://pyqt.sourceforge.net/Docs/PyQt5/sip-classes.html), which leads to an error.
QStringList is used as the type of a pyqtProperty in this class. Using a string to define the type works for both PyQt4 and 5.
Thanks,
Laís

[Byte] pyqtProperty of type QStringList working for both PyQt4 and PyQt5

---

pydm/application.py
pydm/data_plugins/__init__.py
pydm/data_plugins/archiver_plugin.py
pydm/data_plugins/epics_plugin.py
pydm/data_plugins/fake_plugin.py
pydm/data_plugins/plugin.py
pydm/data_plugins/psp_plugin.py
pydm/data_plugins/pyepics_plugin.py

Implement a default protocol environment variable.  If the environment variable PYDM_DEFAULT_PROTOCOL is set, PyDM will use that whenever a channel was specified without a protocol, rather than just silently failing.  This PR also overhauls the data_plugins system so that you can add new plugins simply by adding files to the data_plugins directory, without needing to modify any other files.
Warning: this very slightly changes the PyDMPlugin base class so that protocols are specified *without* the "://" part.  If you have written your own custom data plugin, you will need to modify it to remove the "://".

Default protocol

---

pydm/widgets/embedded_display.py

FIX: Remove the old widgets when opening a new file in an embedded display.

---

pydm/widgets/slider.py

Another good fix from @mennodoor.

On Slider Widget, make sure to use the value after it has been converted to a float.

---

examples/slider/slider.ui
pydm/data_plugins/epics_plugins/pyepics_plugin.py
pydm/widgets/label.py
pydm/widgets/slider.py
pydm/widgets/spinbox.py

Widgets that can display floats now get their precision from the channel by default.  Properties exist on these widgets to override the channel's precision with a user-specified value.  The pyepics data plugin has been enhanced to emit the precision signal if a PV has precision specified.

Precision improvements on widgets

---

pydm/application.py

To ensure maximum compatibility one should be using ```pydm.PyQt``` for the imports.
This PR tries to babysit users into using the correct way and displays annoying warning messages in the following cases:
- User tries to import PyQt4 or import PyQt5
- User tries to use QtGui, QtCore or QtWidgets from PyQt4 or PyQt5 directly and not from PyDM.

ENH: Check and print warnings in case users are trying to directly import from PyQt4/5

---

pydm/widgets/channel.py
pydm/widgets/label.py
pydm/widgets/slider.py
testing-ioc.py

This PR adds support for displaying units and setting limits based on information from data plugins (for example, setting slider minimum and maximum from EPICS HOPR and LOPR fields).  Additionally, there are many bug fixes for the slider widget.  Previously there were many cases where it could enter an infinite loop of slider changes causing the channel to change, causing the slider to change again, etc.  I am surprised it ever worked at all, to be honest.
This will (finally) close #41 when merged.

Implement channel limits and units in widgets.

---

pydm/widgets/slider.py

Will fix #91.  Thanks to @gabrielfedel for discovering the issue!

Fix 'TypeError' warnings when using sliders in designer.

---

examples/camviewer/camviewer.py

Attn @mattgibbs 
This fixes the issue with cam viewer not being able to open.
We need this merged in for a demonstration.

FIX: Removing undefined variables from CamViewer

---

pydm/widgets/base.py
pydm/widgets/related_display_button.py

Fixes #118.  Calls the check_enable_state() on widget initialization (which should disable it).  Related Display Button overrides check_enable_state() now so that it is never disabled.

Fix a bug where non-connected widgets were not fully disabled.

---

pydm/widgets/qtplugin_base.py

Hi,
This pull request adds the `group` parameter in method `plugin_factory`, as discussed in issue #95 .
This way, it is possible to organize PyDM widgets in groups (or categories) inside Designer widget box.
Thanks,
Laís

Widgets categories

---

pydm/data_plugins/epics_plugins/pyepics_plugin.py

With pyepics 3.2.7 and the newest PyDM, I hit two strange errors today. Not sure if these are the best solutions, but this is how I worked around them:
- Some (but not all) enum PVs enter the `enum_strs` block with python strings instead of bytestrings. These would then fail on the `b.decode step`. Fixed by catching `AttributeError`, since this means we don't need to decode the strings.
- Some PVs call the connection callback before the `__init__` statement for `self.pv` has completed, so when they enter the connection callback block, neither `reload_access_state` or `self.pv.run_callbacks` can work. Fixed by checking for the attribute before entering the block.

FIX: Edge cases in pyepics plugin

---

pydm/widgets/baseplot.py
pydm/widgets/timeplot.py
pydm/widgets/waveformplot.py

This PR adds properties for manually setting the Y axis range for TimePlot and WaveformPlot, and the X axis range for WaveformPlot.  It also adds two new properties to BasePlot for enabling/disabling mouse interaction for each axis.  Finally, it moves autoRange property definitions out of the base class and into the subclasses, so that autoRangeX isn't available for TimePlot.
This will close #100 if merged.

Add properties for manual plot ranges.

---

pydm/widgets/baseplot.py
pydm/widgets/timeplot.py
pydm/widgets/timeplot_curve_editor.py
pydm/widgets/timeplot_table_model.py
pydm/widgets/waveformplot.py
pydm/widgets/waveformplot_curve_editor.py
pydm/widgets/waveformplot_table_model.py

This PR adds modifications to let users make scatter plots with PyDMWaveformPlot.  It also adds another new feature: the curve editors for waveform and time plots now use QColorDialog to pick colors - no more need to remember hex codes or color names from the SVG spec.

Scatter plots

---

pydm/widgets/waveformplot.py

Waveform plot size checking was inadvertently commented out in last changes.  Re-enable it.

Fix commended-out waveform plot size checking.

---

pydm/widgets/base.py
pydm/widgets/waveformtable.py

This pull request creates an additional attribute to the PyDMWidget class named subtype which holds the type of the elements of the numpy.ndarray of a waveform channel. 
This attribute is used in the widget PyDMWaveformTable to convert the cell's text into the correct python type.

Create subtype attribute in PyDMWidget class

---

pydm/widgets/waveformplot.py
pydm/widgets/waveformplot_curve_editor.py
pydm/widgets/waveformplot_table_model.py

A recent change made the waveform plot only redraw when both X and Y channels had received new values.  This is not always desired: sometimes, you might want to plot a Y channel against a static X waveform, for example.  This PR gives users the choice: They can choose to redraw whenever the X waveform updates (regardless of Y update status), redraw whenever Y updates (regardless of X), redraw when either updates (this is the original behavior, and the default), or whenever both X and Y update (useful if X and Y need to stay 'in sync', like when you are plotting two time-varying signals versus one another, and need to know that each X/Y pair happened at the same time.)  The property has been added to the curve editor too.

Waveform plot redraw options

---

pydm/widgets/waveformplot.py

When drawing data point symbols, use the pen color specified by the curve.  Also, never fill in the symbols - only draw the outline.

Symbol pen color

---

pydm/widgets/line_edit.py

<code>send_value</code> method in <code>line_edit.py</code> seems to be striping the units incorrectly.

FIX: bug with unit strip in line_edit

---

pydm/data_plugins/archiver_plugin.py

One can now use the environment variable `PYDM_ARCHIVER_URL` to control the archiver plugin base URL, the default value is "http://lcls-archapp.slac.stanford.edu".
Attn. @mattgibbs @shengb

ENH: Add environment variable to remove hardcoded Archiver URL.

---

pydm/widgets/base.py

Always use 2px-border decoration, irrespectively of widget alarm state.
The reason for this is to keep the widget area constant, thus avoiding PyDM widgets to get misaligned when its alarm state changes. This misalignment is happening when a parent widget area has many widgets within it and when 'grid' layout is being used.
I am not sure if the UI behavior (widget area constant) I am trying to achieve with this PR is actually feasible across all possible PyDM widgets.

Pr alarm style sheet map

---

pydm/widgets/spinbox.py

Bug fixes and new functionality to `PyDMSpinbox`:
- Use of keyboard arrows was triggering float conversion errors for Locale's configuration where comma is used instead of dots. The solution delegates to the `QDoubleSpinBox` class the float conversions.
- The text in `lineEdit` was not updated when `showStepExponent` was changed.
- Creation of `contextMenu` entry to toggle display of `stepSize` in `lineEdit` text.
- Creation of `lineEdit` tooltip to show `stepSize` when it is not show in the text.

PR: improve PyDMSpinbox

---

pydm/widgets/timeplot.py

The bug was being triggered when the widget was created from the command line with the `init_y_channels` option containing one or more channels. It was solved by moving the addition of the initial channels to the end of the widget initialization, after the definition of all attributes.

Bug Fix in PyDMTimePlot

---

pydm/widgets/enum_combo_box.py

When a callback is issued and the PyDMEnumComboBox value_changed method is called, it doesn't update the widget value if new_val is equal to 0.

Fixed bug in the value_changed method of the PyDMEnumComboBox

---

docs/source/widgets/index.rst
docs/source/widgets/scatterplot.rst
examples/scatterplot/scatterplot.ui
pydm/widgets/qtplugins.py
pydm/widgets/scatterplot.py
pydm/widgets/scatterplot_curve_editor.py
pydm/widgets/scatterplot_qtplugin.py
pydm/widgets/scatterplot_table_model.py
pydm/widgets/waveformplot.py
scripts/pydm-testing-ioc

This adds a third plot type: Scatter Plot.  PyDMScatterPlot is a widget to plot one scalar value against another.  Multiple scalar pairs can be plotted on the same plot.  Each pair has a buffer which stores previous values.  All values in the buffer are drawn.  The buffer size for each pair is user configurable.
This PR will close #158.

Add Scatter Plot Widget

---

.travis.yml
conda-recipe/build.sh
conda-recipe/meta.yaml
requirements.txt
setup.py

MAINT: Removed pcaspy from requirements list as it is only used at the testing-ioc.
MAINT: Added back pyqtgraph to the requirements list as it was not causing the issues with PyQt vs pyqt naming.
Attn. @teddyrendahl
```bash
conda install pydm -c pydm-dev -c gsecars -c conda-forge
```
GSECARS channel is needed for pyepics.

ENH: Anaconda recipe for PyDM.

---

pydm/widgets/base.py

Apparently PR #136 did not fix the widget area being constant irrespectively of alarm state. Needed to use "solid transparent" color to achieve it.

Fix bug with alarm borders

---

pydm/widgets/pushbutton.py

Value was not being sent if  `_pressValue` was 0.
This bug is triggered when the `pressValue` property was set in the code with a `float` or `int` value.
- The solution applied consists in checking if `_pressValue` is not None before sending it.
- The type of the `_pressValue` attribute was also forced to be `str` by converting the input value in the `pressValue` property setter.
- Some unrelated formatting was also applied so that the lines did not exceed 80 characters.

FIX: PyDMPushButton sendValue.

---

pydm/widgets/baseplot.py
pydm/widgets/image.py
pydm/widgets/scatterplot.py
pydm/widgets/timeplot.py
pydm/widgets/waveformplot.py

The PyDMImageView and PyDMBasePlot-based widgets now all have a 'maxRedrawRate' property, which controls the maximum rate at which the plots will redraw, regardless of the update rate of the underlying channel.  This greatly improves responsiveness in situations where the channel updates at very high rates (100 Hz or more) - previously, these constant redraws would hog the event loop, and bring all other activity in the window to a grinding halt.
Additionally, some refactoring was done to PyDMImageView to avoid unnecessary work, and simplify the flow of updating image data.

Improve image and plotting widget handling of extremely large update rates.

---

pydm/data_plugins/epics_plugins/psp_plugin.py
pydm/data_plugins/epics_plugins/pyepics_plugin.py
pydm/data_plugins/plugin.py

In current pydm, channel signals are never explicitly disconnected from the plugin slots, so they remain connected after `remove_connection` until the garbage collector catches up. This causes problems in the app we're currently working on because we are often changing the channel of various widgets. This results in oddities like two image PVs competing to update the same image widget, which is visually confusing and spikes the cpu load.
Here, I've simply added signal disconnect calls to the `remove_listener` routines. This changes the `remove_listener` API to require a `channel` argument, but this doesn't appear to break anything.

FIX: Clean up signal/slot connections in plugins

---

pydm/main_window.py

I've redone the way the main window resizes when new displays are loaded.  This fixes a few problems:
- Displays will now load at the same size as the .ui file created in Designer.
- Displays with layouts will no longer shrink to an unreasonably small size if there was no widget with a defined minimum width.
- Previously, a fixed minimum width of 300 px was applied to the window, which made it possible to shrink it much more than the widgets should allow, crushing them and causing all kinds of awful text clipping.  The window's minimum width has been removed, which lets Qt calculate an appropriate minimum size automatically.
I think I have probably revisited this behavior three times in the past, hopefully this is the last time!

Fix resizing behavior when a new display is loaded.

---

pydm/data_plugins/plugin.py

#173 introduced a crash when closing a display which contains an embedded display window.  When the display is being torn down, the application traverses all the widgets and disconnects all channels they use.  For some reason, if you have an embedded window, the widgets inside that window get traversed twice.  When pyqtSignal.disconnect() gets called for the second time, it sees that there were no connections, and throws a TypeError.
This PR just handles the TypeError, and doesn't try to figure out why widgets are getting called twice, which seems to be a peculiarity with how QWidget.findChildWidgets() works.

Handle errors when disconnecting from connection signals.

---

examples/frame/frame.ui
pydm/tests/test_plugins_import.py
pydm/widgets/frame.py
pydm/widgets/qtplugins.py

Add a PyDMFrame widget with alarm capabilities.
One can now group widgets and have a Frame around which will respond to alarms in border (alarmSensitiveBorder) & background-color (alarmSensitiveContent).
Updated the smoke test for widgets imports.

ENH: Add PyDMFrame plugin.

---

.travis.yml

The version information at Travis was behaving weirdly since a couple of commits back.
The issue is related to the fact that Travis runs the following command for checkout:
```
git clone --depth=50 ...
```
And since our last tag is more than 50 commits old the automated systems (versioneer and others) were not able to get the proper tag information from the history.
This PR solves this issue and also switch us back to use `doctr` from the official repo since the pull request was merged and the issue was solved.
Thank you @klauer for the help finding this bug on the `depth`.

FIX: Version Information at Travis

---

examples/buttons/buttons.ui
pydm/application.py
pydm/utilities/iconfont.py
pydm/widgets/base.py
pydm/widgets/related_display_button.py
pydm/widgets/shell_command.py

The three button widgets at PyDM (PushButton, Related Display & Shell Command) were exactly the same for a user standpoint and as pointed out, it can cause confusion for the users.
Keeping in mind that some developers and users may like it, this change can be reverted by code and also using the Designer to remove the Icon & cursor if desired.
Here is a GIF showing how the buttons are looking like now:
The PushButton was left unchanged as it can perform way more operations than a simple write to a PV.
Also on this PR, the Related Display button no longer inherits from QFrame and PyDMWidget but now from QPushButton and PyDMPrimitiveWidget since it has no need for channels.
In order to add Alarm behavior to the widget we strongly recommend that you add this widget to the new PyDMFrame which …

ENH: Icon & Cursor at Button Widgets (Related Display, Shell Command)

---

pydm/widgets/drawing.py

Now all drawing widgets start with a sizeHint of QSize(100,100).  Image drawing widgets get a sizeHint equal to the size of the loaded image.  This prevents layouts from shrinking the drawing widgets down to zero when an expanding item is also in the layout.

Implement sizeHint on drawing widgets.

---

pydm/widgets/drawing.py

I think the order of operations were slightly off when you pass in a `filename` at `__init__`.  In the current setup, you set the filename, which creates a new `QPixmap` with your image, then you initialize a new one, overwriting the correct one.
I moved the `filename` set all the way to the end of the base `__init__` operations. That way we don't overwrite our `QPixmap`, and we also have the base aspect ratio when call `update` for the first time at the end of `filename.setter`
Tested locally

FIX: Prevent overwrite of QPixmap after filename __init__

---

pydm/widgets/base.py

Hi,
I would like to suggest a very small change regarding tooltips.
While composing a GUI, I needed to write custom tooltips for some pydm widgets. However, when the app is executed and channels are connected, method **check_enable_state()** in base.py overwrites them.
This PR is an attempt to preserve both custom tooltips and pydm tooltips.
Thanks,
Laís

Append pydm tooltips without overwritting original ones

---

pydm/widgets/base.py

FIX: Install Event Filter only if running and not at the Designer.

---

pydm/widgets/shell_command.py

This PR adds an option to enable the shell command to run the specified `command` multiple times even if the previous command is still running.
Here is a screenshot of the new Property added.
Attn. @joaopmrod

ENH: Added  option to PyDMShellCommand.

---

examples/code_only/code_only.py
examples/home.ui
pydm/application.py
pydm/display_module.py
pydm/main_window.py

With this new enhancement the `Edit in Designer...` behaves in the following way:
- UI only:
Open the Designer if available with the UI file.
- Python only:
Open the default editor for `.py` files according to what is configured on the system.
- Python & UI:
You guessed right... it does both! 😆 
I need some help testing this with Windows & Linux...
After merged this closes #156 .

ENH: Open in Designer now also opens the PY file associated with the screen.

---

pydm/widgets/shell_command.py

Very simple proposal: protect the users from themselves. If a python exception is raised while executing a shell command, such as a file not found or permission error, the GUI should not crash. Use a simple try/except block to achieve this.

FIX: Prevent gui from crashing when shell command goes wrong

---

pydm/application.py
pydm/data_plugins/epics_plugins/pyepics_plugin.py
pydm/data_plugins/plugin.py
pydm/main_window.py
pydm/widgets/base.py
pydm/widgets/enum_combo_box.py
pydm_launcher/main.py

This PR adds a `--read-only` option for when launching the PyDM application.
At this moment we don't see the need for a `read-only` option at the application menu but it can be easily added if needed by users.
This closes #21 .

ENH: Read only option

---

examples/testing_ioc/pydm-testing-ioc

Tell the testing IOC to look for the access rules in the same directory in which it lives.  Fixes #207.

Fix access rules file location for testing IOC.

---

pydm/data_plugins/epics_plugins/pyepics_plugin.py

The `pyepics` plugin in has no try/except block around the `caput`. This means that if a user enters a comma instead of a period in their number the entire application goes down. 
I added a try/except block and the exception is logged. I noticed that in the `pyca` plugin that exceptions are caught, but they are printed. I believe the proper thing here is to log the exception, and if the user doesn't have a logger configured this goes to `stdout`  anyways. I can always switch my PR to a `print` or switch the `pyca` code to log for uniformity 
On another note, @ZLLentz did some work two weeks ago to make pyca work with Python 3.x. We also now package `psp` with `pyca` so that should make things a little nicer. Just wanted to let people know this is now an option in your Python 3.x …

MAINT: Add try/except around pyepics caput

---

README.md
examples/display_format/display_format.ui
examples/label/test_enum.ui
examples/testing_ioc/pydm-testing-ioc
pydm/application.py
pydm/data_plugins/epics_plugins/pyepics_plugin.py
pydm/widgets/display_format.py
pydm/widgets/label.py
pydm/widgets/line_edit.py

This PR adds a new property to the PyDMLabel and PyDMLineEdit to enable the setup of a display format between the available options:
- Default = 0
- String = 1
- Decimal = 2
- Exponential = 3
- Hex = 4
- Binary = 5
The LineEdit is tricky because we also need to take care of doing the reverse conversion when the user sets the data back into it.
Here is a screenshot of the formats being used:
After merged this PR closes #106 and #107.
**TODO:**

ENH: Display Format option for Label and Line Edit

---

pydm/PyQt/Qt.py

Hi,
In pull request #194 I needed to make the following import:
`from pydm.PyQt.Qt import QWIDGETSIZE_MAX `
However, I got:
`ModuleNotFoundError: No module named 'pydm.PyQt.Qt'`
I tried to import QWIDGETSIZE_MAX from other modules but it did not work. So I throught it could be interesting to add Qt module to pydm in other to not import it directly from PyQt5.
What do you thing about this?
Thanks,
Laís.

Make PyQt.Qt module available through PyDM

---

pydm/data_plugins/epics_plugins/pyepics_plugin_component.py

`self.send_access_state` needs `self.app` to exist, else it will raise an exception. If we create `self.app` before creating the `PV` object, we can avoid this issue.
I'm surprised I'm the first to have this issue, as it makes this plugin unusable for me. Has everyone moved over to only using the psp plugin, or am I just lucky with race conditions?

Pyepics plugin race condition in send_access_state callback

---

docs/source/widgets/tab_widget.rst

Small pull request to add a table of properties to the tab widget.  The idea is that this widget's documentation becomes the template to use for all other widgets as part of the ongoing effort towards better user-level documentation.

Add property table to tab widget docs.

---

pydm/data_plugins/__init__.py

I disagree with printing out all the plugins at import. I very much see the importance of recording which plugins are instantiated, but the issue is that there is no control over `print`. This pull request makes this an `INFO` level log message. It will be printed to the screen in the same way if you configure your logger. This gives those who do not want to see the banner the opportunity to hide it by changing logging settings. 
I did not change the the `warnings.warn` message on failure. I'm tempted to switch these to `logger.exception`, but since you can hide `warnings` easily I decided not to press to hard.

MAINT: Remove plugin banner on import

---

pydm/application.py
pydm/widgets/base.py
pydm/widgets/enum_combo_box.py
pydm/widgets/image.py
pydm/widgets/line_edit.py
pydm/widgets/spinbox.py

This PR supersedes #242 and #243 by implementing the fix in a more general way.
Widgets that have a custom menu should implement `widget_ctx_menu` to return their menu which will be modified to add the Tools if present. 
@anacso17 and @fernandohds564 here is the fix for the issues that we discussed with Context Menus.
Would you mind to give it a try and confirm to me that it works?
I tested locally and all seems fine.

FIX: Make the Context Menu Great Again

---

.travis.yml
README.md
dev-requirements.txt

* I noticed after #285 that there was no `dev-requirements` file that allowed users to install the requirements needed to run the testing suite. I added these into a single file for convenience to be installed with `pip -r` or `conda --file` 
* In general I think it best to test using only  the conda-recipe and the `-requirements` files. This means you avoid the struggle of remembering to add the same dependency in multiple places.
* If you build the package locally with Conda (thus checking the recipe) you can quickly upload this to Anaconda. This solves the unwanted surprise of "my tests passed on Travis why can't I build it for the Anaconda release". 
We now are building `pyepics` and `pcaspy` on the Conda channel `pcds-tag`. Just throwing out the idea of using that rather than the …

BLD: Development Requirements

---

.coveragerc
README.md
appveyor.yml
pydm/tests/utilities/test_utilities.py

Included in this PR are:
- support for AppVeyor to run the automated tests against Windows.
- Fix for one of the tests that was *nix specific.
- Badges for Codecov and AppVeyor
- .coveragerc to control what is included on coverage report.

CI: Add support for AppVeyor (Windows)

---

pydm/application.py
pydm/main_window.py
pydm_launcher/main.py

It always bugged me the fact that we need to specify a file to be loaded.
This PR makes possible to just call `pydm` on the command line and get the Main Window to display so users can `Open File...` from the menu if they want.
It is a common mistake that happens mainly with new users but it is a nice "feature" to have.

ENH: Make MainWindow visible when calling PyDM without arguments.

---

pydm/widgets/image.py

This PR introduce the following main changes:
- Eliminates the `data_max_int` dependency;
- Allows the use of `PyDMImageView` with data of float type;
- Adds new `pyqtProperties`, which make possible to: 
- `colorMapMin`: set the minimum value for the colormap;
- `colorMapMax`: set the maximum value for the colormap;
- `imageWidth`: set the image width through a property, not only `widthChannel`;
- `normalizeData`: choose if the colormap colors are relative to minimum and maximum of the data;
- `readingOrder`: set the order of the data reading on reshape (Fortran-like or C-like).
Also other small changes:
- Remove `set_color_map_to_preset` method;
- Make it private `changeColorMap` method, since just `QAction`s uses it;
- Introduce limits validation on `setColorMapLimits`.

Change PyDMImageView to eliminate data_max_int dependency. Add new pyqtProperties.

---

.travis.yml
pydm/tests/conftest.py
pydm/tests/utilities/test_utilities.py
pydm/tests/widgets/test_label.py
pydm/tests/widgets/test_lineedit.py
pydm/tests/widgets/test_pushbutton.py
pydm/widgets/base.py
pydm/widgets/line_edit.py
pydm/widgets/pushbutton.py

FIX: Moved unicode to str handling for Python 2.7 from Push Button to Base
FIX: Included Hugo's YAML config fix to have focusOut event handled correctly by Travis-CI.
Closes #257

TST: Added tests for the PyDM Line Edit widget

---

pydm/widgets/byte.py

This is generating a weird flickering when using the Widget on Windows and it also creates a little delay in general. This small fix was tested locally by me at my mac.
Attn. @joaopmrod
So what happens is that:
- When creating a widget without a parent it shows up just *flying* on the screen on Windows... so you see a bunch of flickering screens before your real screen shows up
- Moreover, the creation of the widget without parent and later adding it to the layout generates an overhead on the system...

FIX: Create PyDMBitIndicator using self as parent.

---

pydm/widgets/image.py

Hey guys! This PR fixes a bug that I noticed when using an image of non-square dimensions (that is why none of us noticed before, because the `pydm-testing-ioc` generates a square image).

FIX: PyDMImageView bug on reshaping image for Clike reading order.

---

pydm/tests/widgets/test_drawing.py
pydm/widgets/drawing.py

Some minor adjustments to the `PyDMDrawingImage` widget.
* When using `Qt.KeepAspectRatio` you can wind up with the situation where one dimension of the image is much smaller than the widget. The prior implementation always drew this in the upper left hand corner but I think it is better to center the image inside the widget.
* When you typed in the Designer the shell would barf error messages about setting a null `QPixmap` this is because it was trying to creating a `QPixmap` from a path that doesn't exist. We now check whether this path exists before drawing
* The widget would silently fail if the image you added does not exist (besides the  null QPixmap warning). Now if a `QApplication` is active we broadcast an error message saying we can't find your image. If we are in Designer this …

PyDMDrawing Filename

---

pydm/widgets/enum_combo_box.py

Replace the internal layout of `PyDMEnumComboBox` with just a straight inheritance of `QComboBox`.
This allows us to delete all the repeated mapping of the signals which ends up being about 80 lines of code. There are a few things to think about before merging:
1. This will break any code dependent on the `QFrame` API or that was calling `PyDMEnumComboBox.combo`.
2. This changes the look of the widget as there is no frame around the `QComboBox` anymore.
I will let the collaboration decide if these are too much of an issue for this to be merged, just wanted to get this on paper while I was thinking about it.
* Closes #315 
* Tested on live signals
* I am fine waiting to merge this until @hmbui gets to this widget.

MAINT: PyDMEnumComboBox inherits from QComboBox

---

pydm/widgets/timeplot.py

There was a bug when add a new curve on execution, the curve buffer size
keeps default buffer size (1200). To fix this the addYChannel was
changed to set buffer size to curve.

BUG: set buffer size when adds new curve on Timeplot

---

docs/source/add_data_plugins.rst
docs/source/index.rst
pydm/application.py
pydm/data_plugins/__init__.py
pydm/tests/test_data_plugins_import.py

Refactored the way plugins are loaded. There are now two methods:
* ``add_plugin``
- Add a plugin to the global registry
* ``load_plugins_from_path``
-  Searches a list of directories for valid `PyDMPlugin`objects. This is automatically called in `pydm/data_plugins` as well as any directories listed in`$PYDM_DATA_PLUGIN_PATH`.
Finally, the last major change is now instead of constructing the mapping of protocol vs. plugins in the `PyDMApplication` itself, `PyDMApplication.plugins` is just linked to `data_plugins.plugin_modules`. `plugin_modules` was formerly a `list` is now a `dict`. This allows plugins to be added after `PyDMApplication` is imported. This is explicitly tested now in `test_add_plugin`.
The way this was loading plugins before enforced a few restrictions:
1. Can not …

MAINT: Refactor Plugin Loading

---

pydm/data_plugins/__init__.py

There was a malformed log message where I mixed the `format` and `logging` string formatting up. I went back and made all the log messages uniform so that substitution works well.

LOG: Fix logging messages

---

.travis.yml
appveyor.yml
examples/log_display/log_display.ui
pydm/tests/widgets/test_logdisplay.py
pydm/widgets/logdisplay.py
pydm/widgets/qtplugins.py
pydm_launcher/main.py
run_tests.py

Generalized way to show logging output in PyDM
This adds:
* GuiHandler -> A `QObject` `logging.Handler` hybrid that emits log messages from a signal
* `PyDMLogDisplay` -> A `QPlainTextEdit` with a `QComboBox` that allows the operator to select the level of the log. The format of the log can also be selected by the user using the same syntax as a `logging.Formatter`
* QtDesigner Plugin
* Add as a utility pop-up available in `PyDMMainWindow`. Allows for live debugging of the `PyDM` system.
* The coverage display is very verbose. It made it hard to see the output of my failed tests. I added an option to `run_tests.py` that allows you to show the coverage `--show-cov`, but I did not have it do this by default. I think we should have a button for turning this on or off but I'm not convinced if …

ENH: Log Widget

---

docs/source/widgets/frame.rst
docs/source/widgets/index.rst
docs/source/widgets/log.rst
docs/source/widgets/scale.rst
pydm/widgets/qtplugin_base.py
pydm/widgets/qtplugins.py
pydm/widgets/tab_bar_qtplugin.py

As we talked offline, this PR reorganize some of the widgets in a new category named Container so it makes more sense. This PR also add some widgets that were left behind on the documentation part, it is still not perfect but it is better than nothing.
We will revisit those widgets documentation in the near future.
Attn. @teddyrendahl, @mattgibbs and @hmbui

MNT: Add CONTAINER to Widget Category

---

pydm/tests/widgets/test_display_format.py
pydm/widgets/display_format.py

See for #332 for the full motivation
In short, the other display managers and client layers ignore all entries in the char waveforms after the first 0 value. Some IOCs assume that this is the case, and make no effort to clean junk values in the extra spaces. This PR shortens the array before decoding a string if there is a zero in it when the user asks for the data as a string.
I added one test case.
closes #332

FIX: Stop reading epics char waveforms at first zero (null) value for string conversion

---

pydm/widgets/logdisplay.py

An operator can currently write to the `QPlainTextEdit` that displays the logs. I thought we had this set to read-only internally, but I guess it didn't make it in the final PR.

MAINT: QPlainTextEdit should not be user write-able

---

pydm/application.py

The `show_address_tooltip` function assumes that there are `PyDMChannels` on the widget. This crashes the application with an `IndexError` when there are no channels on a widget. This patch checks that there are objects in the list if before grabbing the zero-th channel to display.

FIX: Do not assume widget has populated channels

---

conda-recipe/bld.bat
conda-recipe/build.sh

Bumped into https://github.com/conda/conda/issues/508.

CI: Add single-version-externally-managed to build scripts for Anaconda.

---

docs/source/tutorials/macros.rst
pydm/PyQt/Qt.py
pydm/PyQt/QtCore.py
pydm/PyQt/QtDesigner.py
pydm/PyQt/QtGui.py
pydm/PyQt/QtSvg.py
pydm/PyQt/qtlib.py
pydm/PyQt/uic.py
pydm/widgets/qtplugin_base.py
pydm_launcher/main.py

Before this is merged, will need docs (both in argparse setup and sphinx) and unit tests.
`python ./main.py -m "AA=aa,BB=bb, CC=c{c}, DD=d[a<b}:_"`

#350 code changes, docs will need changes, too, also test code

---

pydm/data_plugins/epics_plugins/pyepics_plugin_component.py

Fixes a bug where PyDM wouldn't send out alarm status changes unless the value also changed at the same time.

Explicitly monitor DBE_VALUE and DBE_ALARM.

---

pydm/data_plugins/epics_plugins/psp_plugin_component.py
pydm/data_plugins/plugin.py

- Properly handle read/write access state changes
- Send signal if ctrl vars change after initial connection to PV
- Send ctrl vars to new listeners of an existing PV (Fixes issue #86)
These updates require pyca 3.1.0.

Improvements in the pyca EPICS plugin.

---

pydm/widgets/related_display_button.py

In PyDMRelatedDisplayButton, only open a display if the user left-clicks on a button.  Ignore middle- and right-clicks.

Only launch a display on a left mouse button click.

---

appveyor.yml

Codecov binary was missing from anaconda.

CI: Install dev-requirements using pip on windows.

---

pydm/application.py
pydm/main_window.py
pydm/tests/utilities/test_utilities.py
pydm/utilities/__init__.py

This adds another environment variable to PyDM: ``PYDM_DISPLAYS_PATH`` which will be useful to point PyDM in where to look for new files such as EDM, MEDM and other display manager do.
Users will be able to specify the filename or a relative path that will be first tried at the local folder and if not found we look at the PYDM_DISPLAYS_PATH for that...
I added a test for this case and all works fine. I also tested that locally with a UI file and it is working great.
The motivation for this implementation came from a comment from @markrivers and the explanation on why such functionality is important to generate and deliver UIs for modules such as AreaDetector.
This closes #348

ENH: Add support for PYDM_DISPLAYS_PATH variable.

---

pydm/widgets/symbol.py

The setter for the 'imageFiles' property on PyDMSymbol would throw an exception if it wasn't valid JSON.  This made it impossible to type in a value for this property in Designer.
Now, the exception is handled, and if the property can't be parsed as JSON, the image dictionary is just left empty.

Fix crash in PyDMSymbol when the imageFiles attribute is invalid.

---

pydm/main_window.py

Why this is different for MacOS than it is for Linux, I have no idea, but for Qt 5 on MacOS, Designer.app lives in 'libexec' instead of 'bin'.  I also added a change that disables the menu item to open in designer if the designer binary isn't found.

On MacOS, look for Designer.app in libexec directory.

---

pydm_launcher/main.py

Added new `--version` argument that will print the version of PyDM in the command line.
Attn. @shengb
```
(py36) slepicka@TID-PC94483:~/pydm-git [version_cmd !?] $ pydm --version
PyDM v1.3.0+9.g7208b289.dirty
```
```
(py36) slepicka@TID-PC94483:~/pydm-git [version_cmd !?] $ pydm -h
usage: pydm [-h] [--perfmon] [--hide-nav-bar] [--hide-menu-bar]
[--hide-status-bar] [--read-only]
[--log_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}] [--version]
[-m MACRO]
[displayfile] ...
Python Display Manager
positional arguments:
displayfile           A PyDM file to display. Can be either a Qt .ui file,
or a Python file.
display_args          Arguments to be passed to the PyDM client application
(which is a QApplication subclass).
optional arguments:
-h, --help            show this help message and exit …
```

ENH: Add version command to launcher.

---

pydm/application.py
pydm/main_window.py
pydm/pydm.ui
pydm/pydm_ui.py
pydm_launcher/main.py

`F11` enters and exits the Full Screen Mode...
Optional command line argument for launcher `--fullscreen` added.
This will be very useful for the CUDs and other applications at the Control Room.

ENH: Add full screen mode capability to MainWindow.

---

.travis.yml

Travis-CI pool of OSX builds is no longer saturated. This means that we can add osx to our matrix of tests.
This PR adds it in and also solves an issue that is: 
- Hugo needs to remember to build the package all the time. 😄 
Attn. @shengb

CI: Add OSX target

---

pydm/tests/widgets/test_enum_combo_box.py
pydm/widgets/enum_combo_box.py
requirements.txt

I have a case where I have a plugin that emits `str` values and also has `enum_strs`. The `PyDMEnumComboBox` has a slot that accepts all types of input but piped this directly to `setCurrentIndex`. This PR checks the type and tries to do the correct thing. 
I also noticed that `six` isn't in the `requirements.txt` file so I added it there.
**Question**:  Is there a way to have the widget only accept certain types. It looks like one side affect of the `base.PyDMWidget`  is that we automatically subscribe `valueChanged` to all the types.

FIX: PyDMComboBox only accepts integers

---

pydm/widgets/shell_command.py

When we are in a Windows environment we can't remove the `\` and the way to avoid that is by passing `posix=False` when running on Windows.
Closes #305 .

FIX: Make shlex be smart when splitting the command

---

pydm/application.py

FIX: Fix the clipboard copy. It was failing under MacOS and Windows.

---

pydm/widgets/baseplot.py
pydm/widgets/scatterplot.py
pydm/widgets/waveformplot.py

PyDM Waveform plot as well as the Scatter plot were not respecting the user defined ranges for X and Y and also the AutoRange was not behaving properly being limited by the min and max of the current data being plotted.
Attn. @mattgibbs @marciodo @ernestow

FIX: Waveform and Scatter plots were not respecting user defined limits.

---

pydm/widgets/qtplugin_extensions.py
pydm/widgets/qtplugins.py

The lines patched in this PR caused designer to crash either after startup or adding a PyDM widget and clicking on it.
There may be a misconfiguration that I'm not seeing, but these minor fixes should be benign regardless.

FIX: Designer crashes due to extensions

---

pydm/application.py
pydm/utilities/macro.py
pydm/widgets/related_display_button.py

(Disclaimer: I'm fairly new to the codebase and may be doing something dumb here. I also don't mind if this isn't merged, this just points to where the issue is.)
It did not seem obvious if any widget (derived from either ui-files or Python classes) had access to the correct set of macros, necessary to fix #342, so I have added them here in a not-so-ideal fashion. I can say that this fixes the issue I've observed locally, at least.

FIX: propagate macros with related display buttons

---

pydm/widgets/scatterplot.py

* Scatter plot X and Y axes were swapped due to lines 210/211 using the wrong index from the data buffer
* `channel_pairs` was not consistent despite the comment indicating how it was indexed
* Added some kwarg names in calls for clarity

FIX: scatter plot X and Y axes swapped

---

.travis.yml
pydm/widgets/byte.py

`np.unpackbits` only works with `uint8`, meaning that values get truncated to 8 bits. Then the shift method which should have allowed access to bits > 8 was then rendered ineffective.
Side note: I think the `endian` flag should also be removed altogether...

FIX: remove 8-bit restriction on ByteIndicator

---

pydm/widgets/waveformplot.py

The bug was being triggered when the following conditions were met:
- the `x_channel` is a constant PV, (updates only on connection);
- the `x_channel` connects before the `y_channel`;
It is possible to see the effect of this bug applying the following patch:
```
diff --git a/pydm/widgets/waveformplot.py b/pydm/widgets/waveformplot.py
index ba4d932..664621e 100644
--- a/pydm/widgets/waveformplot.py
+++ b/pydm/widgets/waveformplot.py
@@ -462,9 +462,9 @@ class PyDMWaveformPlot(BasePlot):
list
"""
chans = []
-        chans.extend([curve.y_channel for curve in self._curves])
chans.extend([curve.x_channel for curve in self._curves
if curve.x_channel is not None])
+        chans.extend([curve.y_channel for curve in self._curves])
return chans
```
and running the `testing_ioc` and the …

BUG: Fix bug in PyDMWaveformPlot.

---

pydm/about_pydm/contributors.txt

Adds @hmbui, @klauer, @anacso17, @tacaswell, and @prjemian to the contributors list.  Thanks, everyone!

Update the list of contributors for the 'About' screen.

---

appveyor.yml

Somehow `conda-build` 3.14 is resulting into a JSON TypeError when running on Windows with Python=3.5.
More details here: https://ci.appveyor.com/project/hhslepicka/pydm-fxpsx/build/1.0.321/job/d33x8aj8qp67w2ug
I was able to reproduce locally and I can confirm that with 3.13 it builds the package.

CI: Pin conda-build to 3.13 for Windows.

---

pydm/widgets/related_display_button.py

Fixes a problem introduced in #392 where related display buttons would not open displays unless they had macros specified.

Fix related display buttons that don't have any macros specified.

---

pydm/widgets/base.py
pydm/widgets/byte.py
pydm/widgets/drawing.py
pydm/widgets/embedded_display.py
pydm/widgets/rules.py
pydm/widgets/spinbox.py

Fix some minor copy/paste errors in widget doc strings and make return values consistent with what the code actually returns.

DOC: Fix copy/paste errors in widget doc strings and make consistent with code

---

pydm/widgets/line_edit.py

A widget may be configured to `showUnits`but the channel might not have any units specified. This leads to a scenario in which we were stripping the entire entered value. 
* ``` send_value = send_value[:-len(self._unit)].strip()``` seems really aggressive. I guess it works but why blindly pop information out? Shouldn't something like:
```python
split_send = send_value.split()
if split_send[-1] == self._units:
spilt_send.pop()
send_value = ' '.join(split_send)
```
* The tests for `send_value` do not accurately test what happens to the widget in reality. Many of tests have the `user_typed_value` listed as `float` or `int`. The user will **only** supply us with `str` values. I think these tests need to be re-written to accurately test real-life behavior i.e
```python …
```

FIX: Show Units with no units metadata

---

pydm/default_stylesheet.qss

Removing the wrong 'px' after the value.
Closes #396

FIX: penWidth is a floating point property.

---

.travis.yml
appveyor.yml
setup.py

This PR is targeted at removing Python 3.5 at Travis, which means no Conda Package for Python 3.5 under Linux and Mac as well as Python 2.7 and Python 3.5 at AppVeyor, resulting in no Conda Package for PyDM on Windows with those versions of Python.
This is part of a initiative to move folks towards Python 3.6 or higher. In the near future we will add Python 3.7 to the matrix. That will come after we do some in-house tests.
The reduced matrix will allow us to run tests faster, which is always good.

CI: Reduce the Test Matrix

---

pydm/widgets/timeplot.py

Removing the Downsampling feature while https://github.com/pyqtgraph/pyqtgraph/pull/763 is pending.

FIX: Removing downsampling from TimePlot due to bug at PyQtGraph.

---

pydm/widgets/baseplot.py
pydm/widgets/timeplot.py

Fixes a few bugs in TimePlot, and cleans up the documentation.  Completely removes the plotByTimeStamps pyqtProperty, which didn't work.  If we want to change the x-axis mode via a pyqtProperty (or equivalently, at run time), it isn't trivial.  We will need to:
1. Make sure all set-up for the x-axis mode happens inside the property setter (can't rely on it happening at initialization).
2. Remove the old bottom AxisItem from the layout, and replace it with the new one.
I don't want to do that right now, so if we do want it, we'll have to add it in later.

Fix bugs and documentation issues in TimePlot.

---

.travis.yml

@jesusvasquez333 alerted me today about this issue in which Travis after the `git pull --unshallow` still misses the new tag...
This PR fixes this issue, which I noticed in the past but never when after it or the causes.
Thank you, @jesusvasquez333

CI: Fix Travis missing tags with long number of commits.

---

pydm/utilities/connection.py

If we do not set `Widget.channel`, `Widget.channels()` will return `None` instead of an empty list. If this happens we should not raise an `Exception` but instead log and move on.

FIX: Watch for widgets with no channels

---

examples/camviewer/camviewer.py
examples/image_processing/image_view.py
examples/macros/macros_and_python/macro_addition.py
examples/macros/nested_embedded_windows/macro_addition.py
pydm/display_module.py
pydm/tests/test_data/test.ui
pydm/tests/test_display.py

This PR implements the `ui_filepath` method of the Display class on the class itself, in a way that will work with subclasses.  Effectively, this means that Display subclasses should not need to implement `ui_filepath` anymore.
The PR also removes `ui_filepath` implementations from all of the Python-based examples.

Add an implementation of ui_filepath to Display class

---

docs/source/widgets/enum_button.rst
docs/source/widgets/index.rst
examples/buttons/buttons.ui
examples/enum_buttons/buttons.ui
pydm/tests/conftest.py
pydm/tests/test_plugins_import.py
pydm/tests/widgets/test_enum_button.py
pydm/widgets/enum_button.py
pydm/widgets/qtplugins.py

Closes #352 and #5.
- Option to select the widget type:
- PushButton
- RadioButton
- CheckBox
- Option to select orientation:
- Horizontal
- Vertical
Added tests, entry at the documentation tree and example.
This widget will be very useful for the PCDS Vacuum Widgets project.

ENH: Add new widget Enum Buttons.

---

pydm/about_pydm/about.py
pydm/tests/test_about_screen.py

This PR removes the 'About' screen's dependency on using the PyDMApplication to get lists of plugins and external tools.  It also adds an incredibly dumb test to just make sure that the AboutScreen can be created and shown.  Closes #431.

Fix 'About' Screen Crash

---

setup.py

This forces setup.py to decode README.md as utf-8, fixing a potential crash if a user has a strange default character encoding.

Always decode README.md as utf-8

---

pydm/display_module.py

Came across this issue when using the code-only example.

FIX: Don't try to load a UI file if ui_filename is None or empty.

---

pydm/application.py
pydm/tests/widgets/test_drawing.py
pydm/tests/widgets/test_label.py

This PR fixes unit tests for PyDMDrawing and PyDMLabel to *actually* test whether alarms change text/brush color when alarmSensitiveContent is True.
NOTE: This will probably cause the tests to fail until we implement a fix for #446.

Add alarmSensitiveContent tests for drawings and labels.

---

.travis.yml
dev-requirements.txt

Following the 🚂 ...
Let's enable Python 3.7 for PyDM as well...
This PR also fix the build issue with OSX and Python 3.6 at Travis...
Somehow I can't reproduce the issue locally and it is related to the newer version of pytest-cov.
For now pinning it to `< 2.6.0`.

FIX: OSX build with Python 3.6 & CI: Enable Python 3.7

---

pydm/PyQt/Qt.py
pydm/PyQt/QtCore.py
pydm/PyQt/QtDesigner.py
pydm/PyQt/QtGui.py
pydm/PyQt/QtSvg.py
pydm/PyQt/QtWidgets.py
pydm/PyQt/__init__.py
pydm/PyQt/uic.py

This PR puts the pydm.PyQt module back in place, but routes everything to qtpy.  The only interesting thing is that it supports the old, PyQt4-ish module paths too: You can import QWidget from pydm.PyQt.QtGui, OR from pydm.PyQt.QtWidgets.
This will fix import errors for people who wrote Display classes, and imported things from pydm.PyQt in those classes.  Note, we're only doing this temporarily, and PyDM will emit a deprecation warning if you import from pydm.PyQt.

Temporarily restore pydm.PyQt module.

---

pydm/tests/widgets/test_channel.py
pydm/utilities/remove_protocol.py
pydm/widgets/channel.py

Came across this issue with an user copying and pasting stuff from an editor into the Designer and line edits for PyDM...
This prevents the channel address to be messed up.
Test added to ensure that this will be around for a long time.

ENH: Protect against invalid chars on Channel address.

---

pydm/utilities/connection.py

pydm.utilities.establish_widget_connections had a couple problems that effectively made it never do anything:
1. `if not channels` was called, referring to the not-yet-defined variable `channels`.  This would have thrown a NameError, but
2. The whole thing was wrapped in a try statement that caught NameError, even though we shouldn't expect any under normal conditions.
I have thrown all of that away.

Fix errors in establish_widget_connections

---

pydm/tests/utilities/test_macro.py
pydm/utilities/macro.py
pydm/widgets/embedded_display.py
pydm/widgets/related_display_button.py
pydm_launcher/main.py

This PR lets you use the 'variable=value' style macro syntax inside the 'macro' properties of PyDMEmbeddedDisplay and PyDMRelatedDisplayButton widgets.

Make EDM-style macros usable in widget properties

---

examples/related_displays/multiple_files.ui
pydm/tests/widgets/test_related_display_button.py
pydm/widgets/related_display_button.py

This PR adds two new properties to PyDMRelatedDisplayButton: additionalFilenames and additionalTitles.  They are both string lists.  If these are specified, and not empty, the related display button will turn into a menu button, where a left-click displays a menu of files to open.  If additionalFilenames and displayFilename are both specified, the displayFilename will be the first item in the menu.
A new example illustrates the new behavior.
Also, I've added a few unit tests for PyDMRelatedDisplayButton, capturing the basic functionality, plus the new stuff.
This will close #464 and #99.  Paging @prjemian and @klauer for comments!

Support for multiple files in Related Display Buttons

---

pydm/widgets/base.py

While developing the PCDS Vacuum Widgets I came across this issue when calling super() at the constructor that PyDMPrimitiveWidget was very restrictive for other params.
This fix will allow folks to inherit from PyDMPrimitiveWidget at their custom widgets and make proper usage of super().

MNT: Add **kwargs to PyDMPrimitiveWidget ctor.

---

pydm/widgets/image.py

This PR hides the channel property at the ImageView widget and also makes it a no-op to avoid issues with people writing Python based displays.
I was skeptical to raise an exception there so I just added a logger info message instead. I think it will be good enough.
Closes #466

FIX: Hide channel Property at ImageView widget.

---

pydm/application.py
pydm/data_plugins/__init__.py
pydm/widgets/channel.py

In the current version of PyDM, connections to channels are established when widgets are instantiated.  For displays with hundreds of channels, this is kind of a slow way to do it.  Some tests I ran indicate that waiting until all widgets are instantiated, then establishing all connections in a second pass can shave ~15% off of display load times.
This PR provides a way to do that, without breaking the existing API for establishing connections.  It introduces a connection queue context manager, that lets you request that all connections made within a block are deferred until exiting the block:
```
with pydm.data_plugins.connection_queue():
for item in some_huge_list:
widget = create_widget_for_item(item)
```
All calls to pydm.data_plugins.establish_connection (which pretty much …

Add support for establishing channel connections in batches.

---

pydm/widgets/base.py
pydm/widgets/label.py
pydm/widgets/line_edit.py
pydm/widgets/scale.py
pydm/widgets/slider.py
pydm/widgets/spinbox.py

This PR separates out all of the machinery we use to take a value, a unit string, and a precision, and turn it into a string suitable for use in a text label.
There's a bunch of Qt properties and methods required for all of that stuff, and only a small number of widgets (label, line edit, scale, slider, and spin box) actually use it.  Now, all of those widgets use the TextFormatter mixin class to gain that functionality.
The good news here is that properties like 'precision', 'precisionChanged', 'unitChanged', 'showUnits', 'precisionFromPV', etc. now only show up on widgets that can actually use those properties.  Qt Designer is less cluttered, and hopefully it will reduce confusion among new users.

Text Formatter Mixin

---

setup.py

I came across the following issue with a newer version of setuptools:
`'install_requires' must be a string or list of strings containing valid project/version requirement specifiers;`
We need to explicitly use `'r'` mode when reading the requirements file.

FIX: Explicitly open as 'r' the requirements file.

---

examples/actions/label_text_from_rule.ui
pydm/widgets/label.py

You can now set the text on a PyDMLabel via the rules system.  Comes with a new example showing how it works.
This can be useful for doing things like making a label that behaves like an enum, even though behind the scenes it is driven by plain-old integer or boolean channels.  Or, if you *do* have an enum, overriding the string for each value.
Thanks to @hhslepicka for making this trivial to implement.

Add support for changing label text via the rules system.

---

pydm/data_plugins/__init__.py
pydm/widgets/channel.py

There are occasions when a user intentionally leaves the channel property for a PyDM widget empty.  Right now, this causes PyDM to emit a bunch of error messages if the underlying data plugin tries to connect to an empty string and throws an exception.  This PR changes the behavior to do nothing at all if the channel address is blank.

Silence exceptions when channel address is blank.

---

azure-pipelines.yml

GitHub Pages was failing to build as the changes were being submitted by an invalid authentication from Azure Pipelines.
This PR adds the tweak to use an Access Token to upload the docs (as doctr was doing on the days of TravisCI).

CI: Ensure that we use a valid Access Token when pushing docs.

---

README.md
azure-test-template.yml
dev-requirements.txt
setup.py

- Explicitly set `pytest` to be `>=3.6`.
- Removes `pytest-azurepipelines` from dev-requirements and add it specifically into `azure-test-template.yml`.
- Remove 'test' entry for `extras_require` at setup.py and add `dev` entry pulling info from `dev-requirements.txt`
- Add instructions on README.md for running tests and building docs.

MNT: Cleanups and README Update

---

pydm/widgets/byte.py

The usage of `event.rect()` causes weird redraw issues when the screen is resized or even someone uses a scrollarea.
This PR fixes it by using the widget rect at the paint event which will preserve the size.
Here is a screenshot of the issue:

BUG: Widgets must always use its rect when painting.

---

pydm/widgets/enum_combo_box.py

Lets user to setup combobox items in Qt Designer, if they are not coming from the CS.

ENH: PyDMEnumCombobox can be used with items setup in Qt Designer

---

pydm/application.py
pydm/data_plugins/__init__.py
pydm/main_window.py
pydm/widgets/template_repeater.py

This PR adds a new feature to the recently-added `pydm.data_plugins.connection_queue`.  By setting a flag when you create the queue, you can prevent PyDM from establishing connections after exiting the `with connection_queue` block, then establish those connections at some later time via `pydm.data_plugins.establish_queued_connections()`.
PyDMMainWindow now uses this.  The motivation here is to prioritize loading a display and showing it to the user above establishing connections to widgets.  While this doesn't really make things much faster, they certainly *feel* faster, and the user doesn't sit at a blank screen while PyDM frantically establishes connections to the thousands of channels that the display author foolishly decided the user needed to know about.
Additionally, the queue now …

Defer connections until after PyDMMainWindow loads the display.

---

pydm/application.py
pydm/utilities/display_loading.py
pydm/widgets/embedded_display.py

This PR adds a new property ("loadWhenShown") to PyDMEmbeddedDisplay that lets you control when the embedded .ui or .py file gets loaded.  The default, loadWhenShown=False, is the old behavior, where the embedded file gets loaded as soon as the 'filename' property is set (usually shortly after instantiation).  If you set loadWhenShown=True, the widget will wait until it gets a showEvent before loading the embedded file.
I added this because I built a huge display with 15 tabs, each tab containing an embedded display that contained a very large number of widgets (hundreds).  This display was unbearably slow to load (five seconds to just instantiate widgets, then five more to establish channel access connections).  With loadWhenShown=True, loading is nearly instantaneous, and connections …

Add option to defer loading embedded displays until they become visible.

---

azure-pipelines.yml

The miserable `*` that was missing failed the upload to PyPI.
I did a manual upload... next tag it will be okay! 👍 
All the other uploads worked fine for the tag. I call it a success. 🏆

CI: Fix PyPI upload using twine.

---

pydm/tests/widgets/test_byte.py
pydm/widgets/byte.py

Crash was caused by bit shift operation which affected both PyDM runtime and Qt Designer.
I also added test_byte.py because I could not find a test class for PyDMByteIndicator.

BUG: Crashfix for PyDMByteIndicator with negative shift

---

pydm/tests/widgets/test_enum_button.py
pydm/widgets/enum_button.py

Allows defining the items manually without involving enum_strings_changed signal.
This way, user can define buttons in Qt Designer.

ENH: PyDMEnumButton items property

---

pydm/main_window.py

PyDMMainWindow was not adding a new item to the navigation history stack if you loaded a display that had the same filename, but didn't take macros into account.  Now, if either the filename or the macros are different, a new item will be added to the history stack, making the 'back' button work in that case.

Fix for navigation history with same file, new macros

---

pydm/widgets/embedded_display.py

This PR:
- Fixes a logic error that would sometimes prevent a display from ever loading.
- Fixes a case that would prevent PYDM_DISPLAYS_PATH from being searched when loading a display.
- Makes the `macro` property behave like `filename`, and re-load the display if it changes.

Minor Embedded Display Improvements

---

pydm/widgets/related_display_button.py

When the user instantiates a related display button with a filename, like this: `b = PyDMRelatedDisplayButton(filename='myfile.ui')`, put the filename argument into the `filenames` property, not the old deprecated `displayFilename` property.

Stop using the deprecated displayFilename property in initializer.

---

pydm/widgets/slider.py

@marciodo found a bug introduced by https://github.com/slaclab/pydm/pull/491 in which a widget with limits defined by the User would never be enabled.
I tracked it down and we just need to call `set_enable_state` at the connection and write access callbacks. Tested locally and all is working.

FIX: Call set_enable_state at connection and write_access callbacks.

---

pydm/widgets/shell_command.py

This PR fixes the PyDMShellCommand button so that the shell command will only execute on a _left_ click, rather than any kind of click.

Only execute shell command on left click.

---

pydm/widgets/image.py

This PR changes PyDMImageView to add three new properties:
- **showAxes**: Lets you show/hide axes for the image view.  Defaults to `False`.
- **scaleXAxis**/**scaleYAxis**: Lets you set a scale factor for the X/Y axis units.  Useful from converting to pixels to real-space units like millimeters.

Add option to display axes on the side of image views.

---

pydm_launcher/main.py

Just an idea. It seems more convenient to be able to specify:
`pydm -m a=b -m c=d` rather than `pydm -m a=b,c=d`

ENH: allow specification of multiple -m macro args

---

pydm/widgets/embedded_display.py

I forgot to handle one of the strange corner cases of Embedded Display, where it doesn't get a base_path set.  That caused a crash.  This fixes it.

Fix crash in case where base_path property isn't set.

---

pydm/widgets/embedded_display.py

This is a follow up of 352e5dea796c6798ed60f769a1ecc12ba8b29f24
1. It avoids the crash in Qt Designer, when PyDMEmbeddedDisplay is used.
2. It reverts the logic of 352e5dea796c6798ed60f769a1ecc12ba8b29f24 to try and open the file at the relative path, if the base_path is not set.

FIX: Do not crash Qt Designer when base_path is not set

---

pydm/tests/widgets/test_base.py
pydm/tests/widgets/test_lineedit.py
pydm/tests/widgets/test_spinbox.py
pydm/widgets/base.py

When user in Qt Designer sets precisionFromPV to False, and some non-zero precision, it will be disregarded in some cases, if precisionFromPV is parsed after, because during object creation it defaults to True and precision setter gets ignored.

FIX: Precision could be ignored if it was parsed before precisionFromPV

---

pydm/widgets/embedded_display.py

Scenario:
1. Have a PyDMEmbeddedDisplay with some inner UI, which normally gets rendered by the Qt Designer
2. Toggle loadWhenShown property
3. Embedded display is not rendered until next restart of Qt Designer
Cause:
Because of the invalid condition, existing widget was set to None

BUG: loadWhenShown in Qt Designer loses embedded widget

---

pydm/widgets/base.py
pydm/widgets/label.py

In Qt Designer:
1. Set a custom "text" on a PyDMLabel
2. Select any DisplayFormat -> text is reset to None
3. OR Uncheck precisionFromPV and change "precision" -> text is reset to None
Changing the precision on PyDMSpinBox would actually crash the Designer, as PyDMSpinBox cannot accept None as value.

Value should not be reset in Qt Desinger when changing DisplayFormat or precision

---

pydm/data_plugins/plugin.py

Before I did the stupid mistake of calling `channel.notified` which blocked the whole main thread.
:neckbeard:

FIX: Make notification of new listeners be via signal.

---

pydm/widgets/base.py
pydm/widgets/label.py
pydm/widgets/line_edit.py
pydm/widgets/spinbox.py

This fix address the race condition of loading UI files in which sometimes the property precision is interpreted before the precisionFromPV. This fix was tested and it is working properly.
It is a backport of a fix that I was going to submit to 2.0 branch.

FIX: Separate precision from channel from precision from user defined property.

---

examples/external_tool/lookup_path/new_tool.py
pydm/tools/__init__.py
pydm/tools/tools.py
pydm/widgets/base.py

- Allow one to specify that an ExternalTool is not to be used at the whole application menu. (`use_without_widget`)
- Allow ExternalTools to determine based on the widget if they are compatible or not with the widget before adding it to the menu.  E.g.: One can now filter out the EPICS ExternalTools for a widget using Archiver as the data plugin.
Attn. @slacrherbst

ENH: Some new functionalities for ExternalTools

---

pydm/widgets/template_repeater.py

This adds a new property to PyDMTemplateRepeater that lets you control the spacing of the template repeater's layout.

Add a new property to template repeater to control the spacing.

---

pydm/tests/widgets/test_slider.py
pydm/widgets/slider.py

The slider had two issues:
1. Clicking on the slider bar to jump to a new value (rather than dragging the handle around) would move the handle, but would not update the slider's value.  This PR fixes that by moving the slider's value calculation from the 'internal_slider_moved' slot (which is only called during a drag, not a click) to the 'internal_slider_value_changed' slot (which is called after a drag OR click).
2. If a slider was embedded in a scroll view, you could accidentally change the slider value while trying to scroll using the mouse wheel.  This PR fixes that by adding a new property, "ignoreMouseWheel", that lets you disable slider value changes via the mouse wheel.

Fix some slider problems

---

azure-test-template-win.yml
azure-test-template.yml

CI: Windows no longer needs caRepeater.
CI: epics-base is no longer required as pyepics now uses epicscorelibs.

CI: Attempt to fix Windows build

---

pydm/widgets/waveformplot.py

This PR fixes the problem reported by @anacso17 in #556, which prevented a waveform plot from drawing anything in the case where both X and Y waveforms have non-updating values.

Fix waveform plot bug that prevented constant waveforms from ever getting plotted.

---

pydm/data_plugins/epics_plugins/psp_plugin_component.py

The pyca EPICS data plugin always attempted to decode strings to ascii.  This PR adds logic that will only attempt to decode byte strings, rather than *all* strings, which fixes crashes under Python 3.

Fix psp_plugin string handling for Python 3.

---

pydm/data_plugins/epics_plugins/psp_plugin_component.py
pydm/data_plugins/plugin.py
pydm/widgets/embedded_display.py

This PR fixes three separate bugs related to connections:
1) A bug in the embedded display widget.  When `disconnectWhenHidden` is true, the widget is supposed to disconnect from its channels on a hideEvent, then on a showEvent, it is supposed to reconnect.  Due to a missing update to the `_is_connected` variable, the reconnect was never happening on a showEvent.
2) A bug that would cause completely disconnected PyDMConnection objects to stick around, and sometimes cause havoc, since they were in a disconnected state, but could potentially maintain things like write callbacks.
3) A bug in the PSP data plugin.  There were cases where widgets wouldn't receive enum string values, or the read/write access state from a PSP connection.

Several channel connection fixes

---

pydm/widgets/embedded_display.py
pydm/widgets/template_repeater.py

Close #563 
This PR also address the issue with the EmbeddedDisplay when full_fname is None.

FIX: Template Repeater was not protecting against invalid JSON

---

azure-test-template-win.yml
azure-test-template.yml
pydm/qtdesigner.py
pydm/widgets/embedded_display.py

ENH: Add exception information to Embedded Display widget error message.
ENH: Properly present error at Embedded Display when extension is invalid.
Related to #565 
After this PR is in, the Qt Designer should no longer crash. For now we will print a message at the terminal but in the future the goal is to do a better handling of that. Since I am still unsure what is best this will get it done for now.

ENH: Add exception hook when running with Qt Designer.

---

pydm/widgets/base.py

It seems that https://github.com/slaclab/pydm/pull/524 has been merged with slight modification, which prevents it from fixing the problem.
Reproduction steps:
1. Create a display with PyDMLabel in Qt Designer.
2. Set precision to 2, precisionFromPV to False
3. Run the application, precision of the label will be 0, not 2  (considering using PV that does not broadcast any precision)
This PR brings that missing bit back.

FIX: Missed fix for precision

---

pydm/widgets/display_format.py

Recently PyDM started dumping the following messages:
```
~$ pydm examples/display_format/display_format.ui
[2019-12-20 15:25:42,670] [INFO    ] - Opening the default stylesheet '/Users/slepicka/sandbox/git-slaclab/pydm-git/pydm/default_stylesheet.qss'...
[2019-12-20 15:25:42,698] [ERROR   ] - Could not display value 'None' using displayFormat 'Exponential' at widget named ''.
[2019-12-20 15:25:42,699] [ERROR   ] - Could not display value 'None' using displayFormat 'Hex' at widget named ''.
[2019-12-20 15:25:42,699] [ERROR   ] - Could not display value 'None' using displayFormat 'Binary' at widget named ''.
[2019-12-20 15:25:42,703] [ERROR   ] - Could not display value 'None' using displayFormat 'Exponential' at widget named ''.
[2019-12-20 15:25:42,703] [ERROR   ] - Could not display …
```

FIX: Suppress error message when value is None for display Format.

---

examples/shell_command/shell_command.ui
pydm/tests/widgets/test_shell_command.py
pydm/widgets/shell_command.py

This PR replaces the PyDMShellCommand button's QString `command` property with a new QStringList property called `commands`.  This lets you specify more than one shell command to associate with the button.  If more than one command is specified, clicking the button will present a menu where the user can choose which command to run.  Another new QStringList property, `titles`, lets you specify what to call each command in the menu.
The old `command` property is deprecated - it still exists, but is no longer exposed in designer.  If you load an old .ui file that had `command` set, it will now populate `commands` with a single item instead.  If `commands` is not empty, setting `command` has no effect.  In any case, setting `command` will trigger a deprecation warning message.
The tests for …

Add support for multiple commands to shell command button

---

pydm/widgets/qtplugin_base.py

This is useful to customize the look'n'feel at the Qt Designer widget list.

ENH: Expose the icon parameter for qtplugin_factory.

---

examples/exception/demo.py
pydm/exception.py
pydm/utilities/__init__.py

ENH: New decorator only_main_thread that blocks execution of code if not at the main thread.
REF: Refactored the excepthook to use a QThread with a Queue that distributes the exceptions via a Qt Signal. That allow for custom handlers to be used.

REF/ENH: Refactored the excepthook code and added a decorator.

---

pydm/widgets/channel.py

PyDMChannel comparison could produce false positive when only one of the channels has value_signal set to None.

Fixed channel comparison when one of the value_signals would be None

---

setup.py

With Windows and when using `gui_scripts` as an `entry_point` it uses `pythonw` which creates an asynchronous process and releases the console causing output to not be displayed.
We don't have this kind of issues with `*nix` systems so that is why we revert just Windows to `console_scripts`.
This was tested at my windows VM and it works properly.

FIX: Use console_scripts for Windows for Output

---

conda-recipe/bld.bat
conda-recipe/build.sh
conda-recipe/meta.yaml

- Delay expansion of `CONDA_PREFIX` until the script is used. This avoids the issue in which users get the wrong path for the designer plugin file.
- Address issue with Windows in which the PYQTDESIGNERPATH was not being set due to lack of pydm.bat file.
Attn. @ZLLentz this will be the same at Typhos.

BLD: Synchronize conda-recipe with conda-forge and some other fixes.

---

docs/source/widgets/scatterplot.rst
docs/source/widgets/timeplot.rst
docs/source/widgets/waveformplot.rst
pydm/widgets/scatterplot.py
pydm/widgets/timeplot.py
pydm/widgets/waveformplot.py

Due to an oversight in the doc index, the docstrings for the WaveformPlotCurveItem, TimePlotCurveItem, and ScatterPlotCurveItem weren't making it into the sphinx docs.  This was a real shame, since they were actually pretty well documented.  This PR fixes that.

Fix docs to show the various Plot Curve Items 

---

pydm/widgets/enum_button.py

Expose properties of the PyDMEnumButton widget to customize the layout spacings and margins, which fixes #605.  Here are settings for the .ui file that MEDM screens will use:
```
<property name="horizontalSpacing" stdset="0">
<number>0</number>
</property>
<property name="verticalSpacing" stdset="0">
<number>0</number>
</property>
<property name="margin_top" stdset="0">
<number>0</number>
</property>
<property name="margin_bottom" stdset="0">
<number>0</number>
</property>
<property name="margin_left" stdset="0">
<number>0</number>
</property>
<property name="margin_right" stdset="0">
<number>0</number>
</property>
```

Configure button layout spacings and margins in PyDMEnumButton

---

docs/source/widgets/byte.rst
docs/source/widgets/checkbox.rst
docs/source/widgets/drawing.rst
docs/source/widgets/embedded_display.rst
docs/source/widgets/enum_button.rst
docs/source/widgets/enum_combo_box.rst
docs/source/widgets/frame.rst
docs/source/widgets/image.rst
docs/source/widgets/label.rst
docs/source/widgets/line_edit.rst
docs/source/widgets/log.rst
docs/source/widgets/pushbutton.rst
docs/source/widgets/related_display_button.rst
docs/source/widgets/scale.rst
docs/source/widgets/scatterplot.rst
docs/source/widgets/shell_command.rst
docs/source/widgets/slider.rst
docs/source/widgets/spinbox.rst
docs/source/widgets/symbol.rst
docs/source/widgets/tab_widget.rst
docs/source/widgets/template_repeater.rst
docs/source/widgets/timeplot.rst
docs/source/widgets/waveformplot.rst
docs/source/widgets/waveformtable.rst
pydm/widgets/waveformplot.py

@tashasummers noticed that our documentation is missing key properties that are inherited from the base classes at the widgets API.
This PR enables `inherited-members` and also `show-inheritance`.
Better too much information than no information at all.

DOC: Show inherited-members and show-inheritance.

---

pydm/tests/widgets/test_colormaps.py
pydm/widgets/colormaps.py
pydm/widgets/image.py

Should fix the image View with `pyqtgraph 0.11`, and should work with `pyqtgraph < 0.11` as it used to.
Closes #616

FIX: possible fix for pydm ImageView with pyqtgraph 0.11

---

pydm_launcher/main.py

Without this we run into an issue if users add a `QWebEngineView` or similar at the UI.
With this in place users can now add the WebEngineView and render HTML5 webpages inside of the UI file.
I came across this issue when looking for some options for the PMPS screen for PCDS.
If using a custom QApplication developers are responsible for handling this since we have no control over when the QApplication is created.

FIX: Import QtWebEngineWidgets before creating PyDMApplication.

---

pydm/widgets/logdisplay.py

This should fix https://github.com/pcdshub/typhos/issues/272 .
Probably a race condition between the Ophyd device generating log messages and the widget being destroyed is causing this issue. Simply wrapping the emit with a try/except block will address this issue.

FIX: Wrap GuiHandler emit to avoid RuntimeError.

---

pydm/utilities/__init__.py
pydm/utilities/shortcuts.py
pydm_launcher/main.py

For now the default for the Inspector is `Alt+C` but users are allowed to specify a custom KeySequence if desired.

ENH: Add utilities.shortcuts and initial shortcut ConnectionInspector

---

examples/camviewer/camviewer.py
examples/image_processing/image_view.py

After merging #514 in, the view returned by `image.getView()` is no longer a `ViewBox` and it is now a `PlotItem`. This PR fixes the examples to reflect this change.

DOC: Fixing examples after change on Image widget viewBox.

---

pydm/tests/widgets/test_base.py
pydm/widgets/base.py

I came across this when investigating an error message reported by @ghalym at one of the L2S-I vacuum screens. The property was modified but was empty which caused PyDM to create a channel with an empty string at the channel property.
This fix avoids this condition and a subsequent error message:
```
[ERROR   ] - Channel  did not specify a valid protocol and no default protocol is defined. This channel will receive no data. To specify a default protocol, set the PYDM_DEFAULT_PROTOCOL environment variable.
```

FIX: Make sure we don't create channels with empty strings.

---

pydm/tests/widgets/test_rules.py
pydm/widgets/base.py
pydm/widgets/rules.py

FIX: Reduce verbosity of Not all channels are connected message which can be very annoying and little informative.
Came across the need for this code while exercising rules at the PMPS-UI for L2S-I.

FIX: Make sure we unregister when setting a new rule even if invalid.

---

azure-pipelines-linux.yml
azure-pipelines-macos.yml
azure-pipelines-windows.yml
pydm/widgets/image.py

This PR here requires a lot of explanations.
Today I was poking with pyqtgraph and I noticed that when displaying an Image via the ImageView widget all worked out fine but with PyDM it failed on instantiation with the famous `ConnectSlotsByName` error which up to this point was blamed into Python >= 3.7.4 and also PyQt 5.13.1 not being available.
The reality of the fact is that Python 3.7.4+ now exposes the violations that we were having in which `Qt properties` of the widget were trying to access attributes that were not available yet.
Today after finding out that the issue was entirely on our field I decided to debug it more and I managed to finally fix it.
Closes #533 and unleashes Python > 3.7.3.

FIX: Address issues with PyDMImageView and initialization.

---

pydm/widgets/rules.py

I came across the need for this fix while testing the PMPS-UI yesterday night.
It will most likely also affect other screens using rules eventually.

ENH: Only connect channels after adding entries to widget_map.

---

pydm/widgets/base.py

Came across this issue when helping Allen Pai and Bill with a closing Vacuum Screen.
I got an error that a child widget was deleted when refreshing the stylesheet. 🤞

FIX: Prevent dead child widgets to cause issues when refreshing stylesheet.

---

pydm/widgets/spinbox.py

closes #640.
The logic defined in the homonymous base class method to check the
value of `precisionFromPV` before accepting `new_precision` was being
ignored with the call to `setDecimals`.

BUG: fix `pydm.widgets.spinbox.precision_changed`

---

pydm/utilities/__init__.py
pydm_launcher/main.py

When using any Qt Quick widget (such as QWebEngineView) at a screen via SSH the screen would crash or freeze with many OpenGL errors.
Switching the renderer to software when using PyDM over SSH solves the issue.
A new utility function `is_ssh_session` was added to also help other applications if needed.
This was tested with psbuild and other SLAC machines as well as locally.
Kudos to https://github.com/spyder-ide/spyder/issues/7447

FIX: Revert to Software Rastering if using PyDM via SSH.

---

pydm/widgets/rules.py

If we don't do that connections will multiply at the callbacks at rules.

FIX: Pass destroying only if widget reference is gone.

---

examples/enum_buttons/buttons.ui
examples/enum_buttons/enum.db
examples/enum_buttons/enum.ui
pydm/widgets/enum_button.py

Not always the order coming from the control system will be the best or more logical one for the User Interface.
This PR comes from the need highlighted by users at https://github.com/pcdshub/pcdswidgets/issues/42 in which the `ON/OFF` buttons were being represented as `OFF/ON`.
This PR adds three new properties to the PyDMEnumButton:
- invertOrder (bool) - this just inverts the order
- useCustomOrder (bool) - whether or not to use a custom order
- customOrder (QStringList) - the new order list using here indexes starting at 0.
Here is an example of the outcome:
TODO:

ENH: PyDMEnumButton Order options - Inverted & Custom

---

docs/source/widgets/datetime_edit.rst
docs/source/widgets/datetime_label.rst
docs/source/widgets/index.rst
examples/datetime/datetime.ui
examples/testing_ioc/pydm-testing-ioc
pydm/widgets/datetime.py
pydm/widgets/qtplugins.py

This PR adds two new widgets to the set of PyDM widgets.
- PyDMDateTimeEdit
This widget inherits from QDateTimeEdit and allow users to use a channel providing either a timestamp with seconds or milliseconds as time-base.
- PyDMDateTimeLabel
This widget inherits from QLabel  and allow users to use a channel providing either a timestamp with seconds or milliseconds as time-base.
For both widgets users can configure the Display/Text format. By default it follow the ISO format.
Motivation
-----------
https://github.com/pcdshub/pmps-ui/issues/2
Screenshot
------------

ENH: New Date/Time widgets

---

docs/source/configuration.rst
docs/source/index.rst
docs/source/stylesheets.rst
pydm/config.py
pydm/display.py
pydm/tests/utilities/test_stylesheet.py
pydm/utilities/stylesheet.py

- Add support for multiple files at `PYDM_STYLESHEET`. Files must be separated with `os.pathsep`.
- Add support for usage of the PyDM default stylesheet along with a custom one via definition of the `PYDM_STYLESHEET_INCLUDE_DEFAULT` configuration variable. The default is False to keep current behavior.
This solves an issue with users that just want to add or extend the default stylesheet without keeping track of it or copying it from PyDM and risking get it sync.
- Fixes an issue that stylesheets were never applied to Display instances if not using a PyDMApplication/PyDMMainWindow.
- Update docs to reflect new variable and new behavior for `PYDM_STYLESHEET`.

ENH: Update to PyDM StyleSheet mechanism

---

pydm/widgets/baseplot.py

The current plot zoom is very counterintuitive. This PR sets the mode to be RectMode (aka 1-button) mode in which when the user clicks and drags with the left button of the mouse it draws a rectangle for the Zoom.

ENH: Move the default mouse mode to RectMode (1-button).

---

pydm/widgets/byte.py

Unsure if this may cause unintended side effects; have not tested thoroughly.
Was curious to see how stacking some byte indicator widgets would look, but ran into opaque background issues:
Before
After

MNT: is autofillbackground necessary?

---

pydm/widgets/byte.py

FIX: Align label to center Vertical/Horizontal of Bit widget at ByteIndicator.

---

pydm/data_plugins/__init__.py

Closes #679 and https://github.com/pcdshub/lucid/issues/78
I tested this fix against my reproducible case and the issue is gone.
I also confirmed that all channels are connecting at all embedded and template repeated widgets.

FIX: Address race condition at establish_queued_connections.

---

pydm/widgets/spinbox.py

I have installed an event filter for the QLineEdit which is a child of QDoubleSpinBox, this  captures the events that are filtered and handled in `base.py` - the middle click is one of those events.
I have only tested this on Ubuntu using a Windows machine. 
Trying to close #685

FIX: a possible fix for middle click inside the text-box for spinbox

---

pydm/tests/widgets/test_spinbox.py
pydm/widgets/spinbox.py

This PR implements a `writeOnPress` (bool) parameter for the spinbox widget, which allows for atomic updates to the value without requiring the user to press the `ENTER` key to submit the value. This modified behavior only applies to value adjustments and does not extend to changes to the exponent values. This feature was requested here: https://github.com/slaclab/pydm/issues/686
When `writeOnPress` is `True`:
When disabled, the spinbox functions as before:

Spinbox write on press

---

pydm/widgets/slider.py

Slider was never updating the format when Precision was user defined and value was still null resulting into ginormous values.

FIX: Update format string when value changes.

---

pydm/data_plugins/__init__.py

This was introduced by my somewhat stupid patch (https://github.com/slaclab/pydm/commit/e96f7c895bf6c56d2839ddeb9de773dd065db1f2) in which I failed to notice the `not`.
With this fix the template repeaters will be back to connect properly.

FIX: Establish queued connection when we have elements in the QUEUE.

---

pydm/widgets/embedded_display.py

Avoids Qt Designer related logic in __init__ and rather moves it to init_for_designer.

ENH: Move Qt Designer related styling in PyDMEmbeddedDisplay to init_for_designer

---

pydm/data_plugins/epics_plugins/pyepics_plugin_component.py
pydm/widgets/base.py
pydm/widgets/label.py
pydm/widgets/line_edit.py

Reported by @jesusvasquez333 via Slack:
```
$ [2020-09-30 11:43:30,358] [INFO    ] - Using PyDM via SSH. Reverting to Software Rendering.
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-fsoftegr'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Traceback (most recent call last):
File "/usr/local/lcls/package/python/python2.7.13/linux-x86_64/lib/python2.7/site-packages/pydm/widgets/base.py", line 758, in channelValueChanged
self.value_changed(new_val)
File "/usr/local/lcls/package/python/python2.7.13/linux-x86_64/lib/python2.7/site-packages/pydm/widgets/label.py", line 94, in value_changed
self.setText(str(new_value))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-7: ordinal not in range(128)
``` …

FIX: Address issue with weird chars returned by channel.

---

pydm/data_plugins/epics_plugins/pyepics_plugin_component.py

FIX: Python 2 returns a TypeError for a failed conversion while Python3 returns ValueError.

---

pydm/widgets/spinbox.py

This PR fixes the write on press capitalization to be consistent with other menu items.

MNT: Correct capitalization for write on press toggle

---

pydm/main_window.py
pydm/tests/conftest.py

This PR enables Quit confirmation dialog when closing application via title bar close button, Alt+F4 or any other scenarios, involving the closure of main window.
Previously, it would bypass the confirmation dialog, while menu File->Quit would issue it.

FIX: Use quit confirmation on all close scenarios, not just menu click

---

azure-pipelines-linux.yml
azure-pipelines-macos.yml
azure-pipelines-windows.yml
azure-pipelines.yml

- Adding flake8 into Linter stage as initial step towards some better code.
For now it is classified as `allowFailures: true` until we clean up our own mess...
Once that is done we can start enforcing that on collaborators.
- Removes Python 3.6 from test matrix.
Pursuant of Numpy NEP29 and since we are testing 3.7, 3.8 and 3.9 we are dropping 3.6 from the test matrix.
But what about the Linux Python 2.7? That will remain for a little longer but its end is also near. 🙏

CI: Add linter stage and adjust dependencies.

---

pydm/widgets/template_repeater.py

The `PyDMTemplateRepeater` has a malformed error message. In this case, `fname` is actually `None` after being processed above in `find_file`, so it is not a useful string for the error message.
Fixed by replacing the `fname` (always `None` if file not found) with `self._data_source` (always set to a string if we've gotten to this point).
We encountered this while debugging issues related to https://github.com/pcdshub/typhos/issues/429
Before:
```
[2021-03-12 15:48:20] - ERROR - Cannot locate data source file None for PyDMTemplateRepeater.
```
After:
```
[2021-03-12 15:53:36] - ERROR - Cannot locate data source file at2l0_filters.json for PyDMTemplateRepeater.
```

MNT: use filename instead of None in error message.

---

pydm/default_stylesheet.qss

Closes #727 
Screenshots
-------------
Before the PR:
After the PR:

FIX: Make so that ALARM_NONE widgets don't loose their original border.

---

pydm/data_plugins/plugin.py
pydm/widgets/channel.py

I removed the `is_qt_designer() and not config.DESIGNER_ONLINE` check from the `channel.py` and incorporated this check in the `plygin.py`
Removing this check from the `channel.py` allows for automatic DataPlugins' connections at QtDesigner. 
I added an additional attribute (`designer_online_by_default`) at `PyDMPlugin` which is set to `False` by default. If some DataPlugin has this attribute set to `True`, then regardless if they have the `PYDM_DESIGNER_ONLINE` environment variable set or not, the DataPlugin will try to connect at QtDesigner
I only tested this locally, by adding the new attribute to the `PyEPICSPlugin` and it seemed to work: 
```
class PyEPICSPlugin(PyDMPlugin):
...
protocol = None
connection_class = Connection
designer_online_by_default = True
```
When the attribute is …

Allow data plugin to force connect at qt designer

---

pydm/display.py

Considered a proof-of-concept because 1 prerequisite~s~ ~are~ is not yet merged.
Prerequisites
-------------
~#578 (merged here for convenience, or rather out of necessity for the converter to work)~
My branch of adl2pydm https://github.com/klauer/adl2pydm/tree/ref_in_memory (tweak to allow in-memory conversion of ADL screens)
Functionality
-------------
Actual functionality only in 2 small commits: bf560cb, 753e8f7 
Result
--------
```bash
$ pydm ~/Repos/adl2pydm/tests/medm/mca-R7-7-mca.adl
[2021-03-18 17:00:10,549] [ERROR   ] - Loading /Users/klauer/Repos/adl2pydm/tests/medm/mca-R7-7-mca.adl file by way of load_adl_file...
[2021-03-18 17:00:10,607] [INFO    ] - Environment variable PYDM_DISPLAYS_PATH is not defined.
[2021-03-18 17:00:10,607] [INFO    ] - file not found: stylesheet.qss …
```

Proof-of-concept automatic MEDM ADL converter and loader

---

pydm/config.py
pydm/main_window.py

This PR adds a new config option that specifies whether PyDM displays the quit confirmation dialog box or not when closing a window.  This option is driven by an environment variable, `PYDM_CONFIRM_QUIT`.  If this variable is set to "Y", "T", "1", or "TRUE" (case insensitive), PyDM will show the quit dialog.  If the environment variable is set to any other value, or if it is not set at all, PyDM will not show the dialog.
@ivany4 This is relevant to you - to keep the current behavior, you'll have to set this environment variable.

Make the confirm close dialog optional.

---

conda-recipe/meta.yaml
examples/calc/README.md
examples/calc/demo.db
examples/calc/sin_cos_tan.ui
pydm/__init__.py
pydm/data_plugins/calc_plugin.py
pydm/data_plugins/plugin.py
pydm/widgets/__init__.py
requirements.txt

The long waited and requested plugin.
I do have some things that I would like input from others such as:
- Should I include a configuration for trigger on the calculation for channels? 
As of now, it will calculate on any value update. With the trigger option (similar to rules) you can control which channels would trigger a new calculation.
- Should I limit the number of calculations to a certain frequency?
As of now, it is calculating as fast as it can based on how fast the event is set and cleared.
I tested this using the example and EPICS database available here.
The values for TAN (calculated and IOC) are consistent and so is the calculation of the point to make the point position plot at the example.
As of this moment the calc channel syntax is a bit annoying but it will be better …

ENH: Calculation Data Plugin

---

pydm/widgets/multi_axis_plot.py
pydm/widgets/multi_axis_viewbox_menu.py

Right-clicking on a plot will bring up a context menu for making various changes to the plot during runtime. This fix will ensure that the mouse mode change takes effect correctly. (Mouse mode controls what left-clicking on the plot will do. There are two options, panning the plot, and drawing a rectangle to zoom in on)
Currently, this doesn't work properly for multi-axis plots, this will fix it so that it does by propagating the change through every view box on the plot.

Fix the menu option to change mouse mode on plots

---

requirements.txt

Update the requirements file to use version 0.11.0 of PyQtGraph only. This version is recent enough to support the plotting changes, while still having Python2 support. This can be changed to a more recent version upon upgrading to Python3.

BLD: Use pyqtgraph version 0.11.0 when installing PyDM

---

pydm/widgets/byte.py

This PR fixes an issue with the PYDMByteIndicator where when alarm state was set to invalid the color of the indicator would not switch to the invalid color.  
created a custom widget to test the invalid case. 
No new documentation has been made at the moment

FIX: PYDMByteIndicator was not changing color when invalid alarm was set  

---

pydm/widgets/byte.py

override the base class alarm_severity_changed method to address issue with PyDMByteIndicator where color would not update when alarm state changed from invalid or to invalid.  
tested on pydm example ui file.
No new documentation has been made at the moment

FIX: added a method to address issue with PyDMByteIndicator where color would not update when alarm state changes  

---

pydm/widgets/drawing.py

A one line changed to address issue #766. Default color was not working because self._original_brush was initializing as None.
tested on pydm example ui file.
No new documentation has been made at the moment

FIX: Issue with drawing widget using default color not loading unless widget refreshed. 

---

pydm/widgets/baseplot.py

Now that multiple y-axes are supported, deprecate the use of setting y-labels in baseplot in favor of being able to directly set them on each AxisItem. Currently setYLabels() is hard-coded to only set one label anyway, and this makes it easier to set each label on the correct axis by name.

Set y labels on the AxisItem directly

---

README.md
azure-pipelines-linux.yml
examples/README.md

Removes Python 2 as an option in the README, and removes the Python 2 test from the azure pipeline.

BLD: Drop support for python 2

---

pydm/widgets/baseplot.py

Currently the default is to automatically (and unexpectedly) change the tick values on an axis when zooming in or out on it and a unit is set in the label (seconds in the below example). This will disable that behavior by default. Can be re-enabled for individual plots if wanted through setting it back to true.
From:
To:

Disable axis label behavior where it automatically changes tick values when a unit is set on the axis

---

pydm/tests/widgets/test_rules_editor.py

Whoops - I changed the default state of the use_enum checkbox in the rules editor, but didn't update the test.  This PR rectifies the situation.

Update test to match default state of use_enum checkbox.

---

pydm/tests/widgets/test_curve_editor.py
pydm/widgets/axis_table_model.py
pydm/widgets/baseplot_curve_editor.py
pydm/widgets/baseplot_table_model.py
pydm/widgets/scatterplot_curve_editor.py
pydm/widgets/timeplot_curve_editor.py
pydm/widgets/waveformplot_curve_editor.py

The indices ended up incorrect as part of the last round of changes on #754 breaking the display of the "Redraw Mode" column for curve editor for waveform plots and scatter plots. It displays just the number corresponding to the mode instead of the readable label, as well as breaking "Buffer Size" in scatter plots.
Broken version:
Fixed version:
Updated all column delegates to just grab index values based on the column name. Manually verified all 3 types of plots look good now. Included additional tests to automatically catch such issues in the future.

FIX: Update column delegate placements for curve editor

---

pydm/utilities/__init__.py

Fixes a problem with file paths on Windows which needs that pathext parameter set to correctly build the path to files.
Verified file related tests are good now.

Fix a path issue with windows

---

pydm/widgets/datetime.py

Inside the `PydmDateTimeEdit` widget, if you select the "absolute" timestamps, the code currently converts the value using `val.currentMSecsSinceEpoch()`, which gives you the _current_ timestamp, regardless of what `val` originally was. This means that the only value the widget can send in absolute mode is "right now".
This pull request switches it to use `val.toMSecsSinceEpoch()` instead, which converts the datetime to the integer unix timestamp in milliseconds.
References:
https://doc.qt.io/qt-5/qdatetime.html#currentMSecsSinceEpoch
https://doc.qt.io/qt-5/qdatetime.html#toMSecsSinceEpoch
I've tested this only interactively, using our `pmps-ui` application over the last few months:
https://github.com/pcdshub/pmps-ui/blob/97ddee40b63a72e4543481e5986eb0bc16829e4c/pmps.py#L176-L195 …

PyDMDateTimeEdit widget issue with absolute timestamps

---

pydm/widgets/symbol.py

PyDMSymbol has an extra property in widget rules to change the index.  The data type of this property was 'object', but this doesn't actually work - the index must be an integer.

Fix data type for PyDMSymbol's 'index' rule property

---

pydm/widgets/symbol.py

Just changing from object to int. This will not catch anyone off guard as setting this to anything other than an int will cause multiple errors already.

DOC: Update doc string with correct parameter type

---

docs/source/widgets/index.rst

Link to the new documentation from the index

DOC: Add documentation for archiver plots to the index

---

pydm/widgets/qtplugins.py

As discussed will always load the PyDMTimePlotPlugin into designer. Leave the conditional in place for archiver plots so they are only loaded if the environment variable is set.

Always show time plots in designer regardless of archiver environment varilable

---

docs/source/widgets/curve_editor.rst
pydm/widgets/axis_table_model.py
pydm/widgets/baseplot.py
pydm/widgets/multi_axis_plot.py

Adds a column for setting the y-axis label in the axes tab of the curve editor in designer for all PyDM plots, instead of using the label value of each PV added to the plot.

ENH: Add a column in curve editor for setting y-axis labels

---

pydm/tests/widgets/test_baseplot.py
pydm/tests/widgets/test_timeplot.py
pydm/widgets/baseplot.py
pydm/widgets/multi_axis_plot.py
pydm/widgets/timeplot.py

When creating a multi-axis plot using python code only, an additional y-axis names "left" gets added automatically even if it was not specified by name in the addChannel() or addAxis() flow in the user's code. This removes that axis.
Also removed PyDMTimePlot specifically setting the left axis on intialization, which will also cause this issue separate of the other two types of plots. There is no need to do this, either the user will create their own axis, or pyqtgraph will create the default left one.
Added additional test covering this case. Re-ran existing examples/designer flow as well.

FIX: Remove auto-added y-axis when not specifically requested

---

pydm/widgets/archiver_time_plot.py
pydm/widgets/multi_axis_plot.py
pydm/widgets/multi_axis_viewbox_menu.py

PyDMTimePlot (and by extension the archiver plots as well) lets the user set a timespan for the plot upon startup. This PR will let archive plots that set this value automatically request data from the archiver based on the timespan. 
For example, if an archive plot has a timespan that is set to two hours, then anytime that plot is opened it will automatically pull in the last two hours worth of data and display it. After that it will work as before.

ENH: Request data from archiver based on the set timespan upon plot startup

---

pydm/tests/widgets/test_multiaxis_plot.py
pydm/widgets/multi_axis_plot.py
pydm/widgets/multi_axis_viewbox_menu.py

Per request, adds an option in the right-click menu on PyDM plots to restore the x-axis and all y-axes to the original ranges they were specified with when the user created the plot. Will go back to auto-range for any that were left to that option.
Also restores the functionality of the "View All" option to set everything to auto-range. It's a similar option so figured it would be easiest to test both at once here including the interaction between them.
Added unit tests for the new functionality.

ENH: Add a restore default x/y ranges option to the right-click menu in all plots

---

pydm/widgets/embedded_display.py

Size hints and size policies can be incorrect - potentially much too large for some embedded displays.
This PR changes the `PyDMEmbeddedDisplay` to match with the size hints and size policies of the embedded widget automatically.
With PyDM master:
With this PR:

FIX: size hints should be as reported by embedded widget

---

pydm/default_stylesheet.qss

Added a line to the default stylesheet to set the currentIndex of the tabs in the PyDMTabWidget to 0. 
Addresses #764

FIX: make PyDMTabWidget open with the first tab 

---

azure-pipelines.yml

Still run the job, but a warning no longer results in a non-zero exit code. Also update max line length.

BLD: Update azure pipeline so that style warnings are no longer reported as a failure of the pipeline

---

pydm/tests/widgets/test_label.py
pydm/widgets/label.py

Updates PyDMLabel's default text to ###### and displays just the channel name if the PV it is connected to is disconnected. Setting the text via a rule is unaffected.

ENH: Change default text of PyDMLabel to ###### and display channel name when PV is not connected

---

pydm/tests/widgets/test_archiver_timeplot.py
pydm/widgets/archiver_time_plot.py

This fixes an issue with archiver plots where the x-axis scroll keeps on going even when manually zooming into a specific region of the plot. Now this update to the x-axis only happens when no zooming has occurred.

FIX: Don't keep the rolling window moving when zooming in on archiver plots

---

pydm/widgets/rules.py

Added a check to the run method in rules.py to ignore the expression while in qt_designer. 
This was done to address issue #810

FIX: ignores the rule editor expression in qt designer

---

pydm/data_plugins/plugin.py

As discussed here #798 when a partial is used as a slot for a PyDMChannel, the code for removing a listener and disconnecting that slot does not work properly since pyqt is not handling the case of automatically disconnecting slots that were created as partials. 
This will specifically handle that case to ensure the disconnect will happen. The check for whether or not to disconnect a slot has been moved to its own method to make it clear what is happening in each case. And additional documentation was added.
I tested this by creating a time plot with a channel that uses a silly partial like this:
```
self.channel = PyDMChannel(address=new_address, 
connection_slot=self.connectionStateChanged,
value_slot=partial(self.receiveNewValue))
```
Before applying this PR confirmed that the log is …

FIX: Ensure PyDMChannel signals/slots are disconnected when a functools.partial is used

---

pydm/widgets/baseplot.py

Currently an error will occur when setting axis colors in designer if one of the specified axis names does not exist. This will make it so that it just iterates through each axis on the plot instead of looking for specific ones, as well as applying the color correctly after setting any additional axes through designer.

FIX: Error when setting axis colors on a plot through designer

---

pydm/tests/widgets/test_baseplot.py
pydm/widgets/archiver_time_plot.py
pydm/widgets/baseplot.py
pydm/widgets/timeplot.py

There is an issue where a time plot created with default axis settings only will not receive mouse events on the x-axis. (For one example, run the timeplot.ui file under the examples directory and see that the x axis is not interactable) This is much more noticeable when using archive plots and trying to move the x-axis.
The fix is in 2 parts. The change to baseplot.py will now create/link data to the default left axis only when no other y-axis is specified. This will ensure the view box remains linked to the x-axis. 
The second part is the change to timeplot/archiver_time_plot which is the same fix as the change to timeplot here but applied to archive plots as well: #803 
The easiest way to test is just to run the time plot under examples/timeplot but it will also work with any custom …

FIX: Ensure time plot x-axis receives all mouse events

---

pydm/widgets/embedded_display.py

When right clicking on the space of an embedded display, a context menu will now be created that allows opening that embedded display in its own window. 
Because plots use special event handling code, their context menu will be re-used for this with an extra option added to the bottom (see screenshot below) rather than creating a new menu.
The widgets in the top half of this display are all in one embedded widget:
Clicking on the new window option results in this:
The option when clicking on a plot will be added to the bottom of the existing menu:

ENH: Add an "Open in New Window" option to embedded displays

---

pydm/widgets/timeplot.py

`PyDMTimePlot.getAutoRangeX` returns `None` when `self._plot_by_timestamps` is False (i.e., not plotting by timestamps)
Add `return` for the `else` clause
Found while trying to resurrect timechart.
Should resolve https://github.com/slaclab/timechart/issues/59

FIX: return getautorangex in pydm.widgets.timeplot

---

docs/source/installation.rst

Just adding in an extra step that should fix designer not launching on mac os.

DOC: Update installation instructions with a fix for designer not opening on mac os

---

docs/source/data_plugins/calc_plugin.rst
pydm/data_plugins/calc_plugin.py
pydm/tests/data_plugins/test_calc_plugin.py

- Add a helper function, `epics_unsigned` to be used in the `calc` plugin for converting signed EPICS integers to unsigned versions to close #767. Philosophically, it didn't feel right to build this into the EPICS plugins since the EPICS plugins are producing the true values as appropriate, and since there would be three plugins to modify. Building this into the widgets seemed similarly annoying due to proliferation of widget types. Building this into the `calc` plugin allows me to re-use this for my various unsigned longs that are wrapping around to negative values, and to be very explicit about what I'm doing.
- Add basic unit tests for calc_plugin, including my added functionality. These tests are in no way exhaustive, but they are a start.
- Add some docstrings and doc page info for …

ENH: Unsigned calc helper and TST: calc_plugin tests

---

conda-recipe/meta.yaml

The newest pyqt build is up on conda-forge and coincides with the test failures. Passing builds have:
```
pyqt                      5.12.3           py37h89c1867_8    conda-forge
```
Failing builds have:
```
pyqt                      5.15.4           py37hd23a5d3_0    conda-forge
```
Hopefully, the tests on this PR pass.
If so, let's pin it down until someone has time to figure out the compatibility nuances.

BLD: new pyqt seems to break the test suite on the CI, pin for now

---

pydm/widgets/multi_axis_plot.py

There was an issue where the primary view box on a PyDM plot was not being set to auto-range when the view all button was clicked. Fixed here - it should not be an if/else, every view box should always be set.
Verified the in-progress sparkline widget now looks good (where this bug was discovered) as well as existing example plots.

Fix: Ensure the main view box for plot widgets is also set to auto range when "View All" is clicked

---

conda-recipe/meta.yaml
docs/source/data_plugins/external_plugins.rst
docs/source/development/external_tools.rst
docs/source/index.rst
examples/external_tool/dummy_tool.py
examples/external_tool/lookup_path/new_tool.py
examples/external_tool/lookup_path/root_tool.py
pydm/config.py
pydm/data_plugins/__init__.py
pydm/display.py
pydm/tests/test_data_plugins_import.py
pydm/tests/test_tools.py
pydm/tests/utilities/test_utilities.py
pydm/tools/__init__.py
pydm/utilities/__init__.py
requirements.txt

Allow for external tools to be loaded by one of two mechanisms:
* `PYDM_TOOLS_PATH` environment variable, which is an `os.pathsep`-delimited list of paths to search for `*_tool.py` files
* entrypoint-exposed classes in other packages' `setup.py` files.
* Example: https://github.com/slaclab/timechart/pull/77
Add some basic tests for the new functionality and some of the old. Some holes in coverage still, but I think this is probably better than the status quo.
Allow for data plugins to be loaded by one of two mechanisms:
* `PYDM_DATA_PLUGINS_PATH` environment variable, which is an `os.pathsep`-delimited list of paths to search for `*_plugin.py` files
* entrypoint-exposed classes in other packages' `setup.py` files.
* No example for this yet
* Removes references to deprecated `imp` library …

REF/ENH: Entrypoints for external tools and data plugins

---

pydm/main_window.py
pydm/show_macros/__init__.py
pydm/show_macros/show_macros.py
pydm/tests/test_show_macros.py

With this PR, users can view macros and their values on display by right clicking in it and selecting "Show Macros..." A new window containing the macros is shown. The text within the window is read-only but selectable and copyable as in EDM.
The display below was instantiated via `pydm -m "macro1=hello,macro2=world" test.ui`:

Show macros command

---

pydm/data_plugins/epics_plugins/pyepics_plugin_component.py
pydm/data_plugins/plugin.py
pydm/tests/conftest.py
pydm/tests/data_plugins/test_pyepics_plugin_component.py
pydm/tests/widgets/test_base.py
pydm/tests/widgets/test_channel.py
pydm/widgets/base.py
pydm/widgets/channel.py

Add signals that will be emitted when there are changes to the alarm limits of a PV. These can be monitored by adding the appropriate slot to a PyDMChannel which will be run on any change to the alarm limit value.
Tested with a custom widget to ensure all the signals are working and ending up in the correct place.

ENH: Add the ability to monitor changes to alarm limits of PVs

---

pydm/widgets/multi_axis_viewbox.py

At some point during the development of this I vaguely remember needing to do something special here, but it got removed at some point and now not only is it useless it inits GraphicsWidget twice for no reason. This was caught by the updated PyQT and will fix at least some of the test suite issues it was showing.

FIX: Remove unnecessary init for the multi axis viewbox

---

docs/source/installation.rst

After messing around with upgraded PyQt5 locally and then trying to restore it back to a working version, I realized the installation instructions currently will leave developers with an incompatible version of PyQt. Updated these to reflect our current pin.

DOC: Update installation instructions to not choose an incompatible verion of PyQt

---

docs/source/development/designer_widgets.rst
docs/source/index.rst
pydm/config.py
pydm/widgets/qtplugin_base.py
pydm/widgets/qtplugins.py

Add support for designable widget entrypoints. 
This means that PyDM-related packages which provide designable widgets no longer need to include their own activation scripts, assuming PyDM itself is configured appropriately.
Closes #848 
Example PR from typhos showing all that can be removed: https://github.com/pcdshub/typhos/pull/491
I have pre-commit configured and inadvertently ran `isort` on plugins.py. I can revert that, if need be.

ENH: entrypoint for designer widgets

---

pydm/data_plugins/epics_plugins/pyepics_plugin_component.py

Simple idea I had while ruminating over this slack thread: https://slac.slack.com/archives/C6B8GRCPQ/p1652395534927249
Since this can block up to 5 seconds, just do it in a thread maybe?
Does this have any terrible downstream effects? I'm not sure, but my uis are opening notably faster.

ENH: add pyepics callback in background thread

---

pydm/tests/widgets/test_timeplot.py
pydm/widgets/timeplot.py

Add updateMode as enum as property for TimePlot widget selection. Keeping updatesAsynchronously as backward compatible but remove accessibility from Designer. Tested with PyDMLineEdit-testing-ioc, MeanValue as PV channel.

Rename PyDMTimePlot's update modes #828

---

pydm/tests/widgets/test_spinbox.py

Enables the spinbox widget before attempting to give it keyboard focus. This should fix the non-linux test failures in #863

FIX: Update spinbox test 

---

pydm/data_plugins/epics_plugins/caproto_plugin_component.py

This includes the alarm limit monitoring added here: #847  to the `caproto_plugin_component.`. Also see #874
Verified that a label widget received updates to the alarm limits as expected.

ENH: Add monitoring of alarm limits to the caproto data plugin

---

pydm/widgets/baseplot.py

Fixes an issue in the qt designer flow only where an extra axis will be created even when not asked for. It can be easily removed but is really annoying.
Current behavior: Create any type of plot, add a curve to it, notice that two left axes will show up.
After this fix: Only the one asked for will show up.

FIX: Don't add an extra axis when creating plots through designer

---

pydm/widgets/baseplot.py
pydm/widgets/multi_axis_plot.py

This fixes #841 where using the show grid option in designer will lead to an exception if a specific left axis is not defined. Will now handle each axis in the plot without looking at the name.
Verified existing plots work with the showGrid option, and that new plots created with it work as well.

FIX: Exception when using the show grid option in designer

---

docs/source/widgets/curve_editor.rst
pydm/tests/widgets/test_multiaxis_plot.py
pydm/widgets/axis_table_model.py
pydm/widgets/baseplot.py
pydm/widgets/multi_axis_plot.py

When creating a new plot in designer, users can now set whether or not to use a logarithmic scale on each axis added to the plot. Also updates the functionality of the transform log options in the right-click menu to work on all axes and data items. Adds associated unit tests.

ENH: Set log mode on or off on a per-axis basis in designer

---

azure-test-template-win.yml
dev-requirements.txt
pydm/data_plugins/epics_plugins/psp_plugin_component.py
pydm/tests/conftest.py
pydm/tests/data_plugins/test_psp_plugin_component.py
run_tests.py
windows-dev-requirements.txt

This includes the alarm limit monitoring added here: #847 to the `psp_plugin_component`. It's mostly the same, but one thing to point out is that I've updated the creation of the psp Pv object to use` control=True`. This change was needed to actually get updates to control values to be sent to the widgets. This does cause the loss of timestamp data, but since we currently aren't doing anything with it in this plugin, no functionality should change.
Added a test case to confirm all the signals are being sent correctly. Verified that a label widget received updates to the alarm limits as expected.

ENH: Add monitoring of alarm limits to the PyCA based data plugin

---

pydm/utilities/iconfont.py
pydm/widgets/base.py
pydm/widgets/qtplugin_base.py
pydm/widgets/terminator.py

With PyDM master, try the following:
```bash
$ python -c "import pydm.widgets.terminator"
QPixmap: Must construct a QGuiApplication before a QPixmap
Aborted
```
```bash
$ python -c "import pydm.widgets.qtplugins"
QPixmap: Must construct a QGuiApplication before a QPixmap
Aborted
```
I think it's not controversial to say that importing _any_ module in Python should not cause a segfault based on some assumption about what was imported before it (or otherwise, for that matter).  So I investigated what could be done to avoid creating `QIcon` instances on import.
* Do not create `QIcon` instances on import
* Instead, tweak the API to optionally have a `get_designer_icon` static (or class) method
* Fallback for all widgets remains an empty `QIcon`
* Adjust `IconFont` to only load fonts if a …

FIX: do not create QIcons on import

---

pydm/utilities/__init__.py

``import_module_by_filename`` is having trouble importing files that contain imports of modules that are just files that live in the same directory as ``source_filename``. It results in a ``ModuleNotFoundError``. We used to just add the directory to the path to ensure it could find these as in this PR.
I'm open to other suggestions to solve this issue, but this would at least get it working again.

Add directory of imported module to sys.path

---

pydm/widgets/analog_indicator.py

Opening designer currently results in `AttributeErrors` being raised from these two properties. This should keep the desired behavior without the use of errors.

FIX: Don't raise AttributeError when loading widget in designer

---

pydm/widgets/colormaps.py

Our test suite consistently pops up deprecation warnings from PyDM:
```
../../../micromamba/envs/testenv/lib/python3.7/site-packages/pydm/widgets/colormaps.py:1072
/home/travis/micromamba/envs/testenv/lib/python3.7/site-packages/pydm/widgets/colormaps.py:1072: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
if LooseVersion(pyqtgraph.__version__) > LooseVersion('0.10.0'):
```
This is due to the deprecation of `distutils`: https://peps.python.org/pep-0632/#migration-advice
Though `packaging` (a non-standard library package) could be used to implement the same functionality as in `master`, the pyqtgraph version as per the package requirements is `>=0.12.0`. This means that the above check is actually unnecessary. 
The conda recipe does not appear …

FIX: distutils deprecation warning for ancient pyqtgraph

---

pydm/widgets/multi_axis_plot.py

The CSV exporter for plots reads from the list of curves added to the plot item, which is currently empty because nothing is getting added. This will fix that. Currently choosing to export to CSV and save will result in `ValueError: max() arg is an empty sequence`
After applying this PR it should work.

FIX: Get the export to csv functionality working for plots

---

pydm/widgets/base.py
pydm/widgets/embedded_display.py
pydm/widgets/label.py
pydm/widgets/related_display_button.py
pydm/widgets/symbol.py

The current way in which rule-triggered properties are set for `PyDMPrimitiveWidget` derivative classes is a bit cumbersome in that:
* It's done at `__init__` time.
* Requires copying the rules from the parent class, which creates unneeded coupling.
* Forces us to write boilerplate code just to check if it's the first time this is being done, and only then add the extra properties.
The first point is not a big issue in practice because Designer instantiates the classes after loading them, but not ideal (and we're doing class-related stuff from an instance...)
The second point is not a huge problem either because you don't refactor parent class names that often, but not pretty either.
The third point is more salient. Boilerplate code is hard to refactor (if needed), and is prone to bugs. …

ENH: provide a decorator to add rule properties to a class

---

docs/source/stylesheets.rst
pydm/display.py
pydm/tests/test_data/test_stylesheet.css
pydm/tests/test_display.py
pydm/utilities/stylesheet.py

This PR adds a new feature to `pydm.Display`: if you put a path to a CSS file in the `Display.styleSheet` property, the display will load the file, and use the contents of that file as the stylesheet.  This makes it much easier to re-use one stylesheet for a bunch of different displays, without using it for _every_ display (which is what the `PYDM_STYLESHEET` environment variable and `--stylesheet` command line arg are for).
A slight bonus: this PR changes where the "global" stylesheet gets merged with the display's "local" stylesheet, which appears to fix some bugs where setting at the widget's `styleSheet` property un-did the global stylesheet.

Support loading stylesheets from files in PyDM Displays

---

azure-pipelines-macos.yml

10.15 has been deprecated for use and will be removed soon. See here for example: https://dev.azure.com/pydm/pydm/_build/results?buildId=1111&view=results 
Bumping up to 12.

BLD: Use a more recent macOS for azure pipelines

---

pydm/tests/widgets/test_multiaxis_plot.py
pydm/widgets/multi_axis_plot.py

Right now when editing a plot in designer, an error will be printed, see #912. This is due to a view box which is not associated with the item trying to clear it out. The fix is to ensure we get the view box which is actually linked with the item before attempting the removal.
How to reproduce current issue:
Open up any of the plots under pydm/examples in designer, open up curve editor, click on Done. An exception will be printed. Repeating those steps after applying this PR should clear up the exception.
Also verified clear() behavior outside of designer and during run time works as expected.

FIX: Remove plot items from the correct view box when calling clear in all cases

---

azure-test-template.yml

Setting the same environment variable as needed on macOS for designer/pydm windows will fix the issue currently seen in the macOS test runs. (here for example: https://github.com/slaclab/pydm/runs/8280030600)

BLD: Fix azure pipelines for macOS 11+

---

pydm/main_window.py

Currently launching a display with the --hide-nav-bar options leaves the "Show Navigation Bar" option in the view menu still checked requiring two clicks to get it to show up. This is just a small fix to get that to work properly (as well as status bar).

FIX: When launching pydm with --hide-nav-bar or --hide-status-bar, uncheck the corresponding menu options

---

pydm/display.py

Quick follow-up to the feature added in #906 
We found that a few of our screens incidentally had empty strings in the `styleSheet` property, which instead of being interpreted as a blank stylesheet were now being reinterpreted as a relative file path to the current directory, which is never a valid stylesheet. Since the code was only checking that the path exists, and the current directory always exists, it was proceeding to try to open the current directory as a stylesheet and crashing.
This just amends the `exists` checks to `isfile` checks which is a bit more precise and prevents empty strings from being interpreted as filepaths.

FIX: skip non-file stylesheets such as empty string

---

pydm/widgets/embedded_display.py

Adds a method to the PyDMEmbeddedDisplay widget, so it can have both its filename and macros changed without reloading the page, which can lead to errors in between changes. 
Tested with a small local example
new documentation will have been added via the auto documentation in the embedded display rst file.

ENH: New embedded display method which can update macros and filename without a reload in between 

---

docs/source/configuration.rst
pydm/application.py
pydm/config.py
pydm/display.py
pydm/main_window.py
pydm_launcher/main.py

Implementation of #905 
Allows setting a display to go to when the home button is clicked via either the `--homefile` command line option, or the `PYDM_HOME_FILE` environment variable. When both are set, the command line option will take precedence. If neither is set, the current behavior will be used where the first display opened is set as the home display.
Example usage - both of these will open the byte indicator display, with the home button set to display the top-level home example.
`pydm --homefile examples/home.ui examples/byte_indicator/byte_indicator.ui`
```
export PYDM_HOME_FILE=examples/home.ui
pydm examples/byte_indicator/byte_indicator.ui
```

ENH: Set a display to return to when the home button is clicked in the nav bar

---

pydm/widgets/multi_axis_plot.py
pydm/widgets/multi_axis_viewbox_menu.py

Fixes #924 
Only the top-level view should have its menu set to the `MultiAxisViewBoxMenu`, all others can use the regular menus as they each affect only their own associated view boxes.
Adds options to the `MultiAxisViewBoxMenu` for clicking on y-auto range. Also fixes the invert axis option since it's similar and affected by the same issue.

FIX: Autorange for plots will now work properly when the context menu is opened in the main view and y-axis options are used

---

docs/source/widgets/PyDMWidget.rst
pydm/data_plugins/epics_plugins/caproto_plugin_component.py
pydm/data_plugins/epics_plugins/p4p_plugin_component.py
pydm/data_plugins/epics_plugins/psp_plugin_component.py
pydm/data_plugins/epics_plugins/pyepics_plugin_component.py
pydm/data_plugins/plugin.py
pydm/tests/widgets/test_base.py
pydm/tests/widgets/test_channel.py
pydm/widgets/base.py
pydm/widgets/channel.py

Creates a PyDMWidget tooltip property that can take in a string which can display current values of object attributes along with the name and value of the channel.
The object attribute is give inside of a tag and when the user hovers over the widget the value is fetched and replaced. For example if "The precision of the widget is $(precision)" is set as the tooltip string, then when the user hovers over the widget they would see "The precision of the widget is 3" (assuming the precision was set to 3 at the time.)
Went ahead and added timestamp to the PyDMChannel class. This was a large addition which should be looked at in detail. Also updated all the plugins to pass the timestamp and the PYDMWidget class
Addresses an open request. #876 Also tries to partially address #518, although the …

ENH: Tooltip

---

pydm/widgets/archiver_time_plot.py

Previously on startup, the `PyDMArchiverTimePlot` would mark an archive request as queued, and run `requestDataFromArchiver`.  
https://github.com/slaclab/pydm/blob/9225c7bd8a5fe8907586212d02f80e7a2885f0fb/pydm/widgets/archiver_time_plot.py#L243-L247
If the time range was not large enough, this method would return without emitting the `archive_data_request_signal` https://github.com/slaclab/pydm/blob/9225c7bd8a5fe8907586212d02f80e7a2885f0fb/pydm/widgets/archiver_time_plot.py#L295-L296
which clears the flag.
This simply clears the flag when those initial requests are veto'd

BUG: clear buffer queue requested flag during initial renders

---

pydm/widgets/timeplot.py

Implements the request in #223 
Currently if you open a time plot, set the timespan to something high like 500, right click on it, and choose "View All" or set the x-axis to autorange, it will not do anything useful since it is set to always display the amount of data specified by the time span.
After applying this, it will auto range properly until it reaches the time span.

ENH: Let the x-axis of time plots autorange until the buffer is filled

---

pydm/tests/widgets/test_spinbox.py
pydm/widgets/spinbox.py

Fixes #903 
The PyDMSpinBox will always set the maximum and minimum values to display based on the HOPR/LOPR fields of the PV. This happens even if the user tries to set their own limits. And in the case HOPR/LOPR are not defined then it will set minimum and maximum both to zero so that the spinbox cannot display anything other than zero.
As an example, connect a spinbox to MTEST:XPos from the testing ioc and try to use it.
This will fix the issue by adding the option to set user-defined limits and use those instead of the ones received from the channel. The default options remains to use the ones from the channel so as to not impact existing uses of the spinbox.
Tested with some local examples, modified the existing spin box test for updating limits, added a new one for the new code.

FIX: Allow the user to set the range of PyDMSpinbox, instead of always taking it from the channel

---

pydm/display.py
pydm/tests/test_display.py
pydm/utilities/stylesheet.py

Currently when setting a style sheet on a display, the code will merge the local and global style sheets together before calling the actual setter. This causes an issue where the global style sheet rules are interpreted as more specific than those of the widget's parent, and thus take precedent over them when they shouldn't. In particular, widgets like embedded displays or template repeaters are not having their styles set correctly on their children.
This just stops merging the global and the local together when setting the stylesheet of a display. The global stylesheet should already be set as part of display creation, so the additional merge should not be necessary. Tested on displays containing embedded widgets/template repeaters. Updated style sheet tests. Has the potential to change …

Fix style sheet overwriting specific rules with global ones

---

pydm/widgets/archiver_time_plot.py

When optimized data is used on the archiver time plot and bars are set to represent the min/max values, these bars will persist on the plot even when `clearCurves()` is called. This will clean them up.

FIX: Clear out the bars set on the archiver plot when clearCurves() is called

---

pydm/widgets/archiver_time_plot.py

Resets the internal `PyDMArchiverTimePlot._min_x` when calling `.clearCurves()`.
As the widget makes requests to the archiver appliance, `._min_x` is updated to keep track of the earliest datapoint requested from the archiver.  This internal attribute is updated whenever the plot is adjusted to include earlier times.
https://github.com/slaclab/pydm/blob/72111a266cd41af7778ac19f68af986bc267f2d3/pydm/widgets/archiver_time_plot.py#L249-L251
This is never reset, so if `.clearCurves()` is called, the plot mistakenly remembers that previous setting and new data will only be requested if we navigate earlier than that number.  
This PR simply resets this to the time the widget was created.

BUG: reset _min_x in clearCurves()

---

pydm/widgets/designer_settings.py

The issue reported in #943 was only reproducible on a mac, as Qt on a mac will default to using `QFormLayout::FieldsStayAtSizeHint` while other platforms do not.
(https://doc.qt.io/qt-6/qformlayout.html#details)
This changes the resize policy to specifically use `QFormLayout::ExpandingFieldsGrow` for all platforms as it will resize the fields that need to expand correctly while leaving fixed size items like the rules button alone.
Also includes a small tweak to the regex so that pydm will parse as a single word when at the start of an attribute name (PyDMToolTip in this case).
Works as expected on all of mac/linux/windows now (screenshot from mac):

ENH: Set resize policy for the QFormLayout of the basic settings widget

---

pydm/widgets/base.py

Not sure if you got to this already or if you have a more complete fix in the works- this seems to fix my middle-click copy that doesn't work in master

FIX: call middleclick event filter instead of dropping middle click events

---

pydm/tests/test_data/test_emb_style.ui
pydm/tests/widgets/test_related_display_button.py
pydm/widgets/related_display_button.py

This isn't quite ready yet (see questions at the bottom) but I think it is in the right direction
In the `PyDMRelatedDisplayButton` widget, load the pydm stylesheet onto the widget that gets created if we're not in a pydm app.
If we are in a pydm app, we already have the stylesheet as set in https://github.com/slaclab/pydm/blob/68150968259ea190c521768e275dfc4fbc6fff26/pydm/application.py#L225 which applies the pydm stylesheet at the pydm application level. We can't do this the same way in a non-pydm app without restyling everything in the application, including the non-pydm things, and potentially overwriting application stylesheets.
If we're not in a pydm application and we want to include a pydm screen, one convenient way to do this is to use the `PyDMRelatedDisplay` button, but then …

ENH: apply pydm stylesheet to related display if not pydm app

---

pydm/widgets/eventplot.py
pydm/widgets/eventplot_curve_editor.py

The early explicit int typing on the x and y index made the use of macro impossible.
This fixes that by pushing the typing much later, at the receive value step.
This has been tested with embedded display for XPP.

Fix idx typing for eventplot

---

pydm/widgets/archiver_time_plot.py
pydm/widgets/eventplot.py
pydm/widgets/scatterplot.py
pydm/widgets/timeplot.py
pydm/widgets/waveformplot.py

The most recent version of numpy has now removed the deprecated aliases, causing errors when trying to use them. This PR will just use the built-in `float` as that is what `np.float` is an alias for.
See here for information on the change: https://numpy.org/doc/stable/release/1.20.0-notes.html#deprecations
See here for why this cast is still needed in pydm plots (underlying issue not yet resolved): #370
Verified tests are passing again after this change, and plots still look fine.

FIX: Switch usages of numpy aliases of floats to the built-in float

---

azure-test-template.yml
dev-requirements.txt

mac os python 3.7 tests started failing because it started solving the environment with a version of pyqt that doesn't work with pytest-qt for some reason. This will add an extra step for that specific test run only to install a version of pyqt that will definitely work with pytest-qt.

TST: Fix mac os test run

---

pydm/tests/widgets/test_lineedit.py
pydm/widgets/line_edit.py

Fixes #940 
To reproduce the issue - create a pydm display with a `PyDMLineEdit` widget. Set the precision (manually or from PV are both fine) and set the `displayFormat` to Decimal or String. It will ignore the value of precision. 
This PR removes the unnecessary check for the display format type. The text formatter will do the right thing no matter what it is set to, this is what the `PyDMLabel` already does.
Verified it works as expected with test displays. Corrected the test case already in place, and added a couple more cases.

FIX: Take precision into account for the line edit widget

---

pydm/widgets/byte.py

Fixes #957 specifically. Still more to come of course. `QPointF` was also an option, but I figure this keeps existing displays exactly the same.
Also includes added type hints and small style fixes.
Confirmed that setting the display to use circles works now for python 3.10, and existing displays using byte indicators look the same.

FIX: Update byte indicator to work with python 3.10

---

pydm/display.py
pydm/tests/test_display.py

This is a continuation of the work done in #859 
When doing some profiling on the pyqt side of things, a lot of time was spent in the compilation of ui files when calling `loadUiType`. For example:
```
Total time: 5.24095 s
File: /afs/slac/g/lcls/package/anaconda/envs/python3_devel/lib/python3.8/site-packages/PyQt5/uic/__init__.py
Function: loadUiType at line 171
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
171                                           def loadUiType(uifile, from_imports=False, resource_suffix='_rc', import_from='.'):
<snip>
199       107       4868.2     45.5     92.9      winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports, 
<snip>
```
This PR applies a similar …

ENH: Improve load time of displays that re-use the same UI file repeatedly

---

pydm/tests/widgets/test_shell_command.py
pydm/widgets/shell_command.py

Fixes #968
If the `enviornmentVariables` property of a `PyDMShellCommand` is saved as an empty string, it will cause an error. This fixes it by not using it if it is empty, same as is done for `None`.
Also includes flake8 fixes, type hints, a bit more documentation, and a unit test covering this case which will fail prior to applying this PR.
Verified existing shell commands still work fine, verified this fixes the issue.

FIX: Error with shell command when environment variable set to empty string

---

examples/README.md
examples/waveformplot/waveform_with_transform.ui

In addition, added to the examples README to reflect an EPICS configuration step we needed to take before we could run the testing_ioc.

DOC: added example transforming a waveform using calc_plugin

---

pydm/widgets/drawing.py

This PR adds midpoint arrows to PyDMDrawingLine.
Added to address #963
Tested on an example Gui.
auto documentation will add the documentation for the new properties.

ENH: add midpoint arrows to PyDMDrawingLine

---

azure-build-template.yml
azure-pipelines-linux.yml
azure-pipelines.yml

Version 18.04 is deprecated per https://github.com/actions/runner-images/issues/6002
Moved to 20.04 for our tests, and switched to just using latest for build pipelines.

BLD: Update ubuntu version used in pipelines

---

pydm/tests/widgets/test_baseplot.py
pydm/widgets/baseplot.py

Fixes #971 by using the `updateAutoRange` methods on the `plotItem`.
10af972 and 6696e9f are the relevant commits for fixing the bug, everything else is adding type hints and doc strings.

FIX: Get the resetAutoRange functions working again

---

pydm/widgets/rules.py

Implements #983
Will log output like the following:
`
[2023-04-03 14:59:33,028] [ERROR   ] - Error while evaluating Rule with name: Show Widget and type: Visible and expression: True if ch[0] == 40 else False`
Narrowed the scope of the try/except to only include the evaluation of the rule, if the rule was not created properly then it will correctly fail with a `KeyError` prior to evaluation.

Add additional information to error message when rule evaluation fails

---

docs/source/data_plugins/p4p_plugin.rst
docs/source/widgets/nt_table.rst
pydm/data_plugins/__init__.py
pydm/data_plugins/epics_plugins/p4p_plugin_component.py
pydm/data_plugins/plugin.py
pydm/tests/test_data_plugins_import.py
pydm/tests/utilities/test_remove_protocol.py
pydm/utilities/__init__.py
pydm/utilities/remove_protocol.py
pydm/widgets/__init__.py
pydm/widgets/base.py
pydm/widgets/nt_table.py
pydm/widgets/qtplugins.py

This PR adds a way to use p4p to pass NTTable data through pydm as a dictionary and to be accessed and displayed with a PyDMNTTable Widget. 
Adapts Hugo Slepicka's NTTable widget for the current version of PyDM:
https://github.com/slaclab/pydm_pva_widgets/blob/master/pydm_pva_widgets/widgets/pva_table.py
and adapts Jake Rudolph's PR https://github.com/slaclab/pydm/pull/979
also implements this idea from @mattgibbs
https://github.com/slaclab/pydm/pull/979#issuecomment-1451152201
A follow up PR will change the calc and loc plugin to work with the changes to hoe the address is parsed. I will aslo add more test coverage and the ability to write with sub-fields in a follow up PR. - YY
Tested on an example Gui
Auto documentation will add documentation for the NTTable Widget and for any new …

ENH: PyDMNTTable Widget 

---

pydm/data_plugins/epics_plugins/p4p_plugin_component.py

A table I was displaying had column headers that were different from the value names, and this is valid as noted here: https://github.com/epics-base/normativeTypesCPP/wiki/Normative+Types+Specification
`Agents SHOULD use the elements of labels as the column headings. There is no normative requirement that the field names of value match the strings in labels.`
So just a minor change to send along the labels as well to cover the case where they are different than the field names of value.

FIX: Send the labels value for the NTTable to widgets

---

pydm/display.py
pydm/tests/test_data/macro_test.ui
pydm/tests/test_display.py
pydm/utilities/macro.py

A follow up fix from #965 
Errors were seen in shell commands like the following where the compilation process was not generating valid python code due to use of single vs double quoted strings like so:
`self.PyDMShellCommand.setProperty("commands", ['xterm -e 'command to run''])`
The reason is that the uic compiler was returning the macros in single quotes like:
`self.PyDMShellCommand.setProperty("commands", ['${button_4_command}'])`
This replaces all instances of single quoted placeholders with double quotes. It double checks that it is actually a macro key before replacing on the off change anyone uses the same format for something else and is expecting single quotes to stay that way.
Also adds a unit test for the new code, as well as one for macro replacing in general to catch this or …

FIX: Ensure placeholders for macro substitutions are always double quoted

---

pydm/tests/widgets/test_lineedit.py
pydm/widgets/line_edit.py

Fixes #993. As described in that issue, when a display first loads a `PyDMLineEdit` can appear with focus and missing the value of the PV it is connected to despite actually being connected. And this behavior is due to PyQT auto focusing it, no user input actually happened. 
This PR should fix that problem by checking to ensure the widget has finished connecting before accepting any `QFocusEvent` where the reason is `TabFocusReason` or `ActiveWindowFocusReason` (these both could cause the issue in my testing).
I think this is a clean way to go about it, the default behavior for a `PyDMLineEdit` which is not connected is to just disable the widget entirely, so no default user functionality is lost this way. And in case there is custom behavior out there around disconnected line edits, it …

FIX: Prevent race condition between PyDMLineEdit connecting and being given default focus

---

pydm/display.py
pydm/main_window.py
pydm/utilities/__init__.py
pydm/widgets/embedded_display.py
pydm/widgets/related_display_button.py
pydm/widgets/template_repeater.py

This adds a check to see if the filename is None in the utilities/__init__.py method 'find_file' to catch an obtuse error when file is missing and set to None then passed on to otehr methods. This change should make the error more understandable to the user. The check is only enabled with a flag set to False, that way the methods original functionality is preserved.

ENH: adds error messege for when file cannot be found 

---

pydm/widgets/line_edit.py
pydm/widgets/nt_table.py

This PR is for two fixes. 
First, 
Addresses issue with imputing boolean values into PyDMNTTable.
Second, 
Addresses issue with passing an np.ndarray with a PyDMLineEdit, where by the line edit is adding extra quotes every time it is passed.

Fix: Issue with boolean inputs into PyDMNTTable and Issue with passing np.ndarray with a PyDMLineEdit 

---

conda-recipe/meta.yaml
docs/source/installation.rst

Remove the `<5.15` pin and just ensure we're on PyQt 5.x.
This is just a test and may fail miserably. Let's see what happens on CI.

BLD: pin pyqt to 5.x

---

pydm/tests/widgets/test_lineedit.py
pydm/widgets/line_edit.py

This is probably another instance of #951, though it seems like the only one caught in the test coverage, since resolving it also removes the deprecation warning for that issue (or I misunderstood something about those warnings, which is highly possible :P).

FIX: Line edit value setting on Python 3.10+

---

pydm/tests/test_data/macro_test.ui
pydm/tests/test_display.py
pydm/utilities/macro.py

I made an incorrect assumption in #991 where I had thought that double quotes were already handled properly during macro substitution. This just applies the same strategy of escaping double quote as well. 
The context for the problem is a display that had a macro like:
`FIELD='.{"dec":{"n":25}}'`
And then when the substitution into the channel address happened it resulted in invalid python code with multiple sets of double quotes:
`self.Val.setProperty("channel", _translate("Form", "ca://PvName.{"dec":{"n":25}}"))`

FIX: Escape double quotes during macro substitution

---

azure-build-template.yml

Reverts slaclab/pydm#967, this change leads to a silent failure when trying to update to documentation.

Revert "Update azure-build-template.yml"

---

pydm/tests/test_data/subfolder/test_relative_filename_child.ui
pydm/tests/test_data/test_relative_filename_parent.ui
pydm/tests/widgets/test_embedded_display.py
pydm/tests/widgets/test_related_display_button.py
pydm/widgets/embedded_display.py
pydm/widgets/related_display_button.py

This PR adds a new property to both `PyDMEmbeddedDisplay` and `PyDMRelatedDisplayButton`, called `followSymlinks`. 
This is rather useful for some situations, in which we have the main display file for an interface mapped with a symbolic link to somewhere else (some people are _a bit_ overly enthusiastic with symlinks, and that's a bit outside our control :P), in which case the previous behavior would be to not follow the link on that file, so when you tried to open a child display via a relative path, it would not find the file.
With this new property, you can switch that behavior so that the path is canonized before trying to search the relative path, so even in that case the correct file is found.
Aside from the very particular issue I mentioned, that kick-started this PR, I think this …

ENH: Allow following symlinks when opening embedded / related files using relative paths

---

.github/workflows/publish-to-pypi.yml
.github/workflows/run-tests.yml

Follow up to #1009. 
Pins zipp to 3.15.0, the most recent version released two days ago no longer supports python 3.7.
Also adds checks to not run the test and pypi jobs by default on forks.

MAINT: Fix flake8 run in github actions

---

pydm/connection_inspector/connection_inspector.py
pydm/tests/widgets/test_base.py
pydm/widgets/base.py

This fixes #932.
I still need to add docstrings and a new test case, but just want to get a quick check that this solutions looks reasonable before proceeding.
This sets up an additional monitor on `channel_name.DISP` for any writable widget so that the widget can be disabled with an appropriate tooltip, similar to the way access security is currently handled.
If `DISP` is not set, it will timeout in a thread without performance impact, I checked with several displays with write widgets and did not see adverse performance issues.

ENH: Monitor the DISP field of records connected to by PyDMWritableWidget

---

examples/pva/nt_enum.ui
examples/testing_ioc/pva_testing_ioc.py
pydm/data_plugins/epics_plugins/p4p_plugin_component.py
pydm/tests/data_plugins/test_p4p_plugin_component.py

Implementation for #1016. The data plugin will now send data from `NTEnum` using the signals that the corresponding PyDM widgets expect to receive (`new_value` and `enum_strings`)
Tested on a local record using `softIocPVA`.  Also tested on the added example in the gif below. Added a test case for sending and receiving the enum data with the p4p data plugin test.
The top widget is a `PyDMLabel` connected to the new example enum channel from the pva test ioc, and the bottom two are `PyDMEnumButton` and  `PyDMEnumComboBox`. (This is the added .ui file under examples)

ENH: Add support for NTEnum to the p4p data plugin

---

conda-recipe/meta.yaml
requirements.txt

This pull request removes the unused dependency `requests` from the `requirements.txt` configuration file as well as from the `meta.yaml` file, which is used for defining the Conda package attributes, inside the `conda_recipe` directory. This detection and removal is a finding from ongoing research aimed at identifying and eliminating code bloat within software projects.
The `requests` package was removed from the source code in [this commit](https://github.com/slaclab/pydm/commit/a2bb68fddf8b2454935a370c94651c962a2f2def), but it still remained as a requirement in the project's dependencies files. Since it is no longer being utilized within the project, removing this unused dependency will reduce the overall footprint of the application, mitigate potential security risks, and simplify the …

Remove Unused Dependency: Requests

---

examples/label/label.ui
pydm/tests/widgets/test_label.py
pydm/widgets/label.py

Fixes https://github.com/slaclab/pydm/issues/1013
Fix is simply to set the text format of the PyDMLabel class to from PlainText to RichText.
Added small test case to ensure stays set.
Also tested by using newly added rich text example:
_-pydm examples/label/label.ui
-in another terminal: caput MTEST:Float 3.2
-label with rich text is shown in Qt window
-caput MTEST:Float 0.007
-label with rich text is hidden_

STY: Enable rich text for PyDMLabels

---

.github/workflows/run-tests.yml

Attempting to fix the macOS test runs failing to build the environment by using Mambaforge in the setup-miniconda action

MAINT: Use mambaforge to fix failing github action for running tests

---

examples/drawing/drawing_demo.ui
pydm/tests/widgets/test_drawing.py
pydm/widgets/designer_settings.py
pydm/widgets/drawing.py

Fixes https://github.com/slaclab/pydm/issues/962
To try out changse:
_-pydm examples/drawing/drawing_demo.ui
-"File", then "Open in Designer"
-click on polyline widget, below label "PyDMDrawingPolyline" (bottom right of qt window)
-go right-side of window in property window, and scroll to bottom to find polyline specific settings
-can toggle on/off the arrow options, and see reflected in qt designer_
Fixes https://github.com/slaclab/pydm/issues/964
To try out changes:
_-pydm examples/drawing/drawing_demo.ui
-"File", then "Open in Designer"
-double click on polyline widget, below label "PyDMDrawingPolyline" (bottom right of qt window)
-can edit points by double clicking on a point and typing new value, press "Update" in bottom right of settings
window, and can see polyline widget's points …

Improvements to Polyline

---

pydm/tests/widgets/test_lineedit.py
pydm/widgets/line_edit.py

We noticed that a bunch of `QMenu` instances were in our typhos test suite at the top-level (`QApplication.instance().topLevelWidgets()`).
While tangential to the issue we were investigating in that repository, it seems unnecessary for PyDM to create these at `__init__` time.
This PR creates the unit conversion menu on-demand.
* Test suite was updated
* Quickly checked the example to see if it still works:

PERF: create unit menu on-demand for QLineEdit

---

pydm/tests/widgets/test_rules_editor.py
pydm/widgets/rules.py
pydm/widgets/rules_editor.py

Add notes field to notes menu so description for current rule can be added.

ENH: Add notes to rules

---

pydm/widgets/base.py

disconnected message was being set correctly, but was getting overridden at point when mouse hovers over widget (when it is time to actually display the tooltip).
the fix is to not write any new values to the tooltip while the widgets channel is disconnected (since tooltip will be already set to the correct disconnected msg). once reconnected, the connected msg will be set again.
to verify this works:
-launch examples/pydm-testing-ioc and then examples/label/label.ui
-open it in designer
-add _Test: $(pv_value)_ as the PyDMToolTip for the label on the left (the one connected to _ca://MTEST:Float_)]
-relaunch label.ui, and hover over the modified label, and confirm it reads _Test: \<value of MTEST:Float\>_
-kill pydm-testing-ioc, go back to the label window and hover mouse over this same …

STY: Stop overriding tooltip's disconnected-msg when channel is disconnected

---

pydm/widgets/pushbutton.py
pydm/widgets/related_display_button.py
pydm/widgets/shell_command.py

Issue was when using designer, entering a password in "Property" window on right-side of screen would not save the encrypted password to the .ui file as expected, and password feature would not work.
This is because editing the "password" property would in-turn update the "protectedPassword" property, 
but designer would not consider the "protectedPassword" property as having been edited, and would then not save it out to the .ui file.
Fix is to update the "protectedPassword" widget property directly with "setProperty" when the "password" is set, to make sure designer knows to save the "protectedPassword" value.
Widget-update code grabbed from the "update_property_for_widget" function in "pydm/widgets/designer_settings.py":
```python
def update_property_for_widget(widget: …
```

Fix password

---

pydm/widgets/drawing.py

Modifies `pydm.widgets.drawing.PyDMDrawingLine._arrow_points` to avoid divide by 0 errors.  
https://github.com/pcdshub/atef/issues/210
I ran into this, but had difficulty consistently reproducing it.  I think in most cases when the length is 0, the widget is hidden and this method would never get called.  But in some cases (if you slowly contract a container or expand a container with the hidden line), this method can be called with arguments that make the `length=0`.  
This modification did not prevent the widget from being hidden when squeezed out of existence, which maintains the existing functionality.
Tested this interactively with no issues

BUG: prevent PyDMDrawingLine from dividing by a length of 0

---

docs/source/widgets/event_plot.rst
docs/source/widgets/index.rst

Adding missing doc page for PyDMEventPlot
Now doc page should be present for all the pydm widgets we export:
_(from pydm/widgets/__init__.py)_ 
__all__ = [
"PyDMChannel",
"PyDMByteIndicator",
"PyDMCheckbox",
"PyDMDrawingLine",
"PyDMDrawingRectangle",
"PyDMDrawingTriangle",
"PyDMDrawingEllipse",
"PyDMDrawingCircle",
"PyDMDrawingArc",
"PyDMDrawingPie",
"PyDMDrawingChord",
"PyDMDrawingImage",
"PyDMDrawingPolyline",
"PyDMDrawingPolygon",
"PyDMDrawingIrregularPolygon",
"PyDMEmbeddedDisplay",
"PyDMEnumComboBox",
"PyDMImageView",
"PyDMLabel",
"PyDMLineEdit",
"PyDMPushButton",
"PyDMRelatedDisplayButton",
"PyDMShellCommand",
"PyDMSlider",
"PyDMSpinbox",
"PyDMSymbol",
"PyDMWaveformTable",
"PyDMScaleIndicator",
"PyDMTimePlot",
"PyDMArchiverTimePlot",
"PyDMWaveformPlot",
"PyDMScatterPlot", …

DOC: Add doc page for event plot

---

pydm/tests/widgets/test_timeplot.py
pydm/widgets/archiver_time_plot.py
pydm/widgets/eventplot.py
pydm/widgets/scatterplot.py
pydm/widgets/timeplot.py
pydm/widgets/waveformplot.py

While making subclasses for TimePlot and WaveformPlot for my application, I noticed this little inconvenience with non-TimePlot plots. I think it's a good thing to have a factory method such as this in every plot! :slightly_smiling_face:
I kept it as close as possible to the one in TimePlot, so as to not change more stuff than needed, though I figured it may be even better to pass a generic `*args, **kwargs` to the `createCurveItem` functions, so as to not constrain the signature of the CurveItem custom implementations. What do you think?

Simplify using CurveItem subclasses in Plot subclasses

---

pydm/tests/widgets/test_rules.py

fixes issue where running tests locally would fail sometimes
issue is that both _pydm/examples/testing_ioc/pydm_testing_ioc_ and the rules-tests use the same named "fake" channel MTEST:Float.

Fix issue where rules test fails if also running testing-ioc

---

examples/icons/icons.ui
pydm/tests/widgets/test_pushbutton.py
pydm/tests/widgets/test_related_display_button.py
pydm/tests/widgets/test_shell_command.py
pydm/widgets/pushbutton.py
pydm/widgets/related_display_button.py
pydm/widgets/shell_command.py
pydm/widgets/slider.py

allow qt standard icons to be set in designer by exposing a custom property that sets the icon using python inside the property's setter.
this should provide a set of default icons cross-platform, since they ship with qt.

ENH: Add propertry for setting Qt Standard Icons in designer

---

.github/workflows/run-tests.yml

Just want to add newer version of Python and PyQt to our test runs. Also undoes a pin to a flake8 dependency that was only needed for python 3.7 and below. Leaves the PyQt 5.12.3 testing in place since the Designer/custom widget problem is still an issue for PyQt versions greater than that.

BLD: Update test workflow file with python 3.10 and pyqt 5.15.9

---

docs/source/widgets/PyDMWidget.rst
docs/source/widgets/index.rst
docs/source/widgets/multistate.rst
examples/byte_indicator/multi_state_indicator.ui
pydm/tests/widgets/test_multistate.py
pydm/tests/widgets/test_multistate_led.py
pydm/widgets/byte.py
pydm/widgets/qtplugins.py

Add basic version of widget.
could expand out later with:
-submenu for easier selection of state colors
-options for rendering different shapes/visual
-accepting >1 PVs
-allow configurable # states besides just 16

Basic version of multi-state LED indicator widget

---

pydm/widgets/image.py

A request from slack that it would be nice to have a way to pause drawing updates to the image in the `PyDMImageView` widget. This PR adds a simple method for doing that, same as is done for pausing plotting updates in `BasePlot`.
Verified functionality with an example like this
```
from os import path
from pydm import Display
from qtpy.QtWidgets import QVBoxLayout, QPushButton
class ImageExample(Display):
def __init__(self):
super().__init__()
self.my_layout = QVBoxLayout(self)
self.button = QPushButton()
self.button.clicked.connect(self.ui.PyDMImageView.toggleRedraw)
self.my_layout.addWidget(self.button)
def ui_filename(self):
return 'image.ui'
def ui_filepath(self):
return path.join(path.dirname(path.realpath(__file__)), self.ui_filename())
```

ENH: Add a method for pausing/resuming the drawing of an image

---

examples/eventplot/eventplot.ui
pydm/tests/conftest.py
pydm/tests/widgets/test_eventplot.py
pydm/tests/widgets/test_related_display_button.py
pydm/widgets/eventplot.py

Just adds the second '*' to the keyword arguments so they are handled properly. Added simple test case to cover this, as well as an example event plot that can be run.
Also includes a couple minor test updates to make the test suite compatible with pytest 8.0 and pytest-qt 4.3+
To reproduce can run the new test or example without the change to `eventplot.py` and see it fail

Fix event plot curve creation

---

pydm/display.py
pydm/main_window.py
pydm/tests/test_main_window.py

As a result of #965 when a user chooses to reload a display, it will reset itself but changes to any underlying `.ui` files are not picked up since the compiled file from the cache is used instead. This PR adds a function for clearing that cache, and calling this new function when reloading a display. To reproduce can open up a display from a ui file, change the ui file while the display is running, and then try to reload and see the change is not reflected in the running display.
Added a test that would have caught the issue, confirmed it fails prior to this code change and passes after. Manually tested changing a file and reloading the display and confirmed it works now.

FIX: Pick up changes to UI files when the main window is reloaded

---

pydm/connection_inspector/connection_inspector.py

Local plugin's `self.address` is not a string, but rather a parsed URL. As such, it does not have a `.endswith` attribute, which would make it fail with an exception when trying to open the connection inspector.
This has been an issue since commit 709a144, in release 1.20.0.

Fix connection inspector with local plugins

---

pydm/widgets/multi_axis_plot.py

Partially fixes #1068
The Python 3.8 issue I didn't tackle, as it's supposed to not be an issue when https://github.com/conda-forge/pyqtgraph-feedstock/issues/30 is fixed.
I'm not sure what has changed upstream to cause this issue, but with this change, it seems to work properly :-)

Fix plotting on pyqtgraph 0.13.4

---

pydm/widgets/multi_axis_viewbox.py

As a follow up to #1069 there are cases in which depending on how the user initializes their plot the main view box on it can get stuck in a loop in which it will continue increasing in size. As a fun example try running `pydm/examples/scatterplot/scatterplot.ui ` using pyqtgraph 0.13.4 without this fix
This is due to https://github.com/pyqtgraph/pyqtgraph/pull/2762
The bounding rect of a ViewBox now adjusts itself before returning, so connecting the `sigResized` signal of a ViewBox to a function which changes its own size results in an endless loop of it resizing itself.
There are more robust ways to solve this on our end, but this is the most fragile area of our code base which I hope to eventually replace with a built-in pyqtgraph solution to multi-axis plots if one of the PRs there …

FIX: MultiAxisViewBox resizing breaks in certain cases

---

pydm/widgets/archiver_time_plot.py
pydm/widgets/timeplot.py

Made changes to the address setters for ArchivePlotCurveItem and TimePlotCurveItem classes:
1. Archive curve object now has an address setter that replaces the function setArchiveChannel. The setter calls the TimePlotCurveItem address setter, then sets the new address as the archive channel. This results in the live and archive channels always being tied to the same address.
2. Both address setters now also check that the new address is different from the current address. If they're the same, the function returns.
3. Changed the way the ArchivePlotCurveItem address setter replaces the address's protocol. Now the pydm utility is used.
4. The TimePlotCurveItem address setter clears all live data tied to the previous channel. Similarly, the ArchivePlotCurveItem removes all archived data for …

ENH: Archiver Timeplot address setters

---

pydm/widgets/embedded_display.py

`EmbeddedDisplay.set_macros_and_filename` only reloads the display if the filename is changed.  This PR makes `EmbeddedDisplay.set_macros_and_filename` reload the display if either parameter is changed.

BUG: reload embedded display when only macros change

---

examples/archiver_time_plot/archiver_time_plot_example.py
pydm/widgets/archiver_time_plot.py
pydm/widgets/timeplot.py

Archived Data Only Mode
The Archived Time Plot Widget currently only supports a live+archived data, this pull requests looks to add a mode where the widget would only pull and display archived data from the given data source.   
At SLAC we are developing a new Archive Viewer, which we wish to also double with displaying live data--which is the current functionally of the PYDM Archiver Time Plot Widget. We also need it to be able to display only archived data without fetching live data. We think this functionality would be useful to the greater PYDM community.     
Will be tested on an example GUI and unit tests will be included in the PR. 
documentation is still being worked on.

ENH: Archived Data Mode for the Archiver Time Plot Widget

---

pydm/widgets/baseplot.py

Follow up to #1061 
Currently, BasePlotAxisItems have range values (_min_range & _max_range) but these are unnecessary as BasePlotAxisItem subclasses AxisItem which has range values. I changed the to_dict function, setters and getters to use these native properties instead.
Created signals for the BasePlotAxisItem that emit when the x or y ranges change. These signals are attached to the axis' linked view (rather than the range setters) because this captures all range changes in the plot's viewbox rather than just on the axis item.
Small fix in BasePlotCurveItem's threshold color setter. The setter takes both QColor objects and strings (which are converted to QColor objects).

ENH: Base Plot Axis range values

---

pydm/widgets/archiver_time_plot.py
pydm/widgets/timeplot.py

Follow up to #1601
Add an autoscroll feature to PyDMTimePlot and PyDMArchiverTimePlot. 
When enabling autoscroll a refresh rate, timespan, and padding are provided. A QTimer is created that will call a function to shift the plot along the X-axis, always showing the given timespan. The QTimer calls this function after <refresh_rate> seconds. The padding will show that much space to the right of the rightmost datapoint.
By default the padding is 10% of the timespan. If the padding value is less than the refresh_rate, then the padding size is the refresh_rate value. This prevents getting newer data than the X-axis shows, which would cause the plot to "jump" to the right frequently.

ENH: Timeplot auto scrolling

---

pydm/widgets/slider.py

This PR is to address an issue where the slider's click behavior was functioning differently on mac's then Linux.
On macOS before this fix when clicking on the slider, the slider value would jump to the position of the click. After the fix when clicking on the slider the slider will increment or decrement one step depending on the side tab the user clicks on. 
Was tested locally on a mac.

FIX: Fix to clicking on PyDMSilder running on MacOS 

---

pydm/widgets/analog_indicator.py

Starting at python 3.10, the rules for passing floats into python C extension modules like pyqt has gotten stricter.
See #951 (closes #951)
The analog indicator widgets have this issue, but they mask over it with try/except blocks to prevent the app from crashing.
This PR makes the widget render as intended by casting all variable inputs to int.
Some of these are guaranteed to always be ints, but some of them are floats. Rather than parse out which is which, I figured it was better to cover all of them.
Python 3.9 pre-PR:
Python 3.12 pre-PR:
Python 3.12 post-PR:

FIX: in analong_indicator, explicitly cast to int for py310+ compat

---

pydm/widgets/image.py

add option for specifying how pydm should read pva image dimensions.
more context: https://github.com/slaclab/pydm/issues/1082

ENH: pva image dim order option

---

pydm/tests/widgets/test_slider.py
pydm/widgets/slider.py

The PyDMSlider has a bug(s) when the channel it is connected to is a certain type of PV (epics record).  If the record is an analog out (ao), and it does not have the record fields DRVH and DRVL set, then the slider is not forced to be within the bounds of the minimum and maximum properties. Since the default values of DRVH and DRVL are both zero, the slider wouldn't have a range of allowed values outside of "0".
This can cause two bugs. The first was calculated step size becomes 0,  which would essentially form a never ending while loop of allowed positions when the slider value was out of bounds. The second bug is PV values could be out of the slider bounds.
These bugs only occur when both DRVH and DRVL were at default values. If either was set it would not occur. This PR has code to …

FIX: PyDMSlider out of bounds bug

---

pydm/widgets/baseplot.py
pydm/widgets/multi_axis_plot.py

This fixes a bug in the BasePlotAxisItem class where the name property will be set internally, but the axis' associated MultiAxisPlot will contain a dictionary with the wrong key-value pairing for the axis object.
AxisItem name bug example scenario:
1. Create a BasePlotAxisItem with name "A"
`my_axis = BasePlotAxisItem(name="A")`
2. Change the name of the previous BasePlotAxisItem to "B"
`my_axis.name = "B"`
3. Create a BasePlotCurveItem and attach it to the BasePlotAxisItem using its new name
`my_curve = BasePlotCurveItem(yAxisName = "B")`
This scenario produces a `KeyError` as the MultiAxisPlot.axes dictionary still uses "A" as the key to reference `my_axis`, but it should use "B".
Solution:
Include a method in MultiAxisPlot for changing the name/key of an axis. Then, update the …

FIX: Plot Axis Name Change

---

pydm/data_plugins/plugin.py

Fix for an error when closing PyDM displays. The error occurs when closing a PyDM application and a PyDMChannel attempts to close its connections. Somehow the connections are already deleted before PyDMChannel can delete them explicitly.
Error text example: 
[2024-06-26 14:13:39,082] [ERROR   ] - Unable to remove connection for <PyDMChannel (archiver://pv=KLYS:LI22:31:KVAC)>
Traceback (most recent call last):
File "/afs/slac.stanford.edu/u/cd/zdomke/workspace/pydm/pydm/widgets/channel.py", line 164, in disconnect
plugin.remove_connection(self, destroying=destroying)
File "/afs/slac.stanford.edu/u/cd/zdomke/workspace/pydm/pydm/data_plugins/plugin.py", line 320, in remove_connection
self.connections[connection_id].deleteLater()
RuntimeError: wrapped C/C++ object of type Connection has been …

FIX: PyDMChannel Connection Removal Error

---

pydm/widgets/baseplot.py

Adding stepMode functionality to BasePlotCurveItem so that stepMode can be changed on the fly. StepMode information can be found [here](https://pyqtgraph.readthedocs.io/en/latest/api_reference/graphicsItems/plotcurveitem.html#pyqtgraph.PlotCurveItem.setData).
The BasePlotCurveItem setter does not ensure the x and y data are the correct lengths for given stepModes. Instead the docstring warns the users of this.
I also included BasePlotCurveItem.redrawCurve as an abstract method since it is called by the stepMode setter.

ENH: Add stepMode to BasePlotCurveItem

---

pydm/data_plugins/epics_plugins/p4p_plugin_component.py

Use `collections.abc.Container` instead of `collections.Container` (which was deprecated in Python 3.3 and removed in 3.10).
This should fix issue #1103.

Fix Container class move for python 3.10

---

pydm/widgets/axis_table_model.py

In the axis table model, when switching an axis from left to right orientation, it was not actually moving the axis. There is a function in multi_plot_axis.py called "rebuildLayout" that moves the axes to where they need to be in the layout, which is one of the added lines.
The axis would then be physically moved, but it would also require being flipped around such that the label would be on the right side of the axis, which wasn't being done either. Prompting the axis to show causes it to redraw properly, so now by switching orientation of a y-axis from left to right (or vice versa) will correctly and immediately update the axis to the opposite side.

FIX: Switching Y Axis orientation was not properly updating

---

docs/source/widgets/archiver_timeplot.rst
examples/archiver_time_plot/formula_curve_example.py
pydm/tests/widgets/test_archiver_timeplot.py
pydm/widgets/archiver_time_plot.py
pydm/widgets/archiver_time_plot_editor.py
pydm/widgets/baseplot.py
pydm/widgets/timeplot.py

Created class FormulaCurveItem. This accepts a formula (in the form of a string) and a dictionary of string : BasePlotCurveItem and populates a new data buffer with the function of the data being passed in. Can be used to graph functions of other functions, by passing FormulaCurveItems in the dictionary and referencing them in the formula string.
This is useful for the Archive Viewer because one of the requested functionalities is the ability to graph a function of one or more PVs rather than graphing only PVs themselves. As the new class extends BasePlotCurveItem, this is usable in other contexts where BasePlotCurveItems are being used.

ENH/DEV: Formula Viewer for Archive Viewer

---

pydm/widgets/baseplot.py
pydm/widgets/timeplot.py

Opening the Archive Viewer, changing plot config, then saving it to a file requires that the plot config can be saved in a dictionary style data structure. This to_dict() function does that for us.

ENH: Import/Export Plot Config

---

pydm/widgets/multi_axis_plot.py

MultiAxisPlot.py linkDataToAxis automatically adds the curve to the legend, but unlinking doesn't remove it, leading to multiple of the same curve existing on the legend if it changes axes. One liner fix.

FIX: Unlinking a curve from an axis now removes it from the legend

---

pydm/widgets/timeplot.py

We want to have curves be automatically attached to axes of the correct units. In order to receive the units, we will attach a slot to the PyDM channel plugin, and emit a signal to whatever curves model (in my case, the Archiver Time Plot Curve Model) we want for it to handle attaching to the correct axis.

ENH: Added a slot to capture units received from the PyDMChannel

---

pydm/data_plugins/archiver_plugin.py
pydm/widgets/archiver_time_plot.py
pydm/widgets/timeplot.py

Adds `connection_state_signal` to the Archiver Plugin and makes use of it in the `ArchivePlotCurveItem`. More details given below:
1. Archiver Plugin will emit to the connection_state_signal when
a. The Archiver URL doesn't exist ( --> False)
b. The network request returns an error and/or data that isn't JSON formatted ( --> False)
c. The network request returns no error and data in JSON format ( --> True)
2. `TimePlotCurveItem` change:
a. Create a channel connection signal that is emitted in `connectionStateChanged`
b. In address setter, disconnect channel (if one exists) and connect the new channel
3. `ArchiverPlotCurveItem` changes:
a. Create a channel connection signal that is directly tied to the archive_channel connection signal
b. In address setter, disconnect archive_channel (if …

ENH: ArchivePlotCurveItem Connection Status

---

pydm/tests/widgets/test_archiver_timeplot.py
pydm/widgets/archiver_time_plot.py

Adds connection status checks to the FormulaCurveItem for both live and archive state. More details below:
1. `FormulaCurveItem` changes:
a. Add properties `connected`, `arch_connected`, `live_connections` and `arch_connections` for storing the status of the curve an all used curves. The curve is only connected if **all** used curves are connected.
b. If the `FormulaCurveItem` has no live and no archive connection then the formula's evaluations are skipped.
c. Set `plot_style` default in `__init__` arguments definition.
2. `ArchivePlotCurveItem` change:
a. Store the archiver channel's connection status in `arch_connected`.

ENH: FormulaCurveItem Connection Status

---

pydm/widgets/multi_axis_plot.py

Add a signal to MultiAxisPlot that is emitted when the user makes changes to the X-Axis. Mimics the ViewBox signal `sigRangeChangedManually` which emits which axes are mouse enabled, but this signal doesn't need to pass any info.
Adding this signal to the event handlers `handleWheelEvent` and `handleMouseDragEvent`. The signal can just be emitted from here because these handlers are only called when the X-Axis is changed manually and only once per change.
I can't use that signal because the X-Axis is linked to each new Y-Axis in `addAxis`, meaning that users need to change which ViewBox to listen to every time a new Y-Axis is added. Adding this signal removes this issue by emitting when the changes are being propagated out to all ViewBoxes.

ENH: Add Manual XRange Change Signal

---

pydm/tests/widgets/test_slider.py
pydm/widgets/slider.py

This PR fixes two bugs with the PyDMSlider. The first was with middle clicking on the slider, which did nothing, indeed of the expected behavior of displaying the PV name. The second was that the Slider was unable to be dragged. Now if a user clicks then holds on the handle of the slider they are able to drag the slider.

FIX: Addressed two bugs on the slider. Middle click to see PV name and click and drag on the slider handle 

---

.github/workflows/publish-to-pypi.yml

changes to the actions/upload-artifact and actions/download-artifact versions to address an issue with pushing to pypi on the release of v1.25.0

FIX: changes to publish-to-pypi.yml

---

docs/source/tutorials/index.rst
docs/source/tutorials/intro/features.rst

found this unmerged doc page when updating old pydm tutorial's url, found in this pr: https://github.com/slaclab/pydm-tutorial/pull/20
ran the example code and this feature still works, so would be good to add to docs.

DOC: add page about custom menu actions

---

.github/workflows/run-tests.yml

This address the follwing warning during CI:
"Warning: Mambaforge is now deprecated! Future Miniforge releases will NOT build Mambaforge installers. We advise you switch to Miniforge at your earliest convenience. More details at
https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/."
This seemed to have caused CI failures pretty recently, although oddly doesn't atm. (perhaps there was an update to miniforge installer?).
But regardless, this change is needed to make sure CI setup doesn't break in the future.

DEV: don't use mambaforge installers in github actions setup

---

pydm/widgets/archiver_time_plot.py

Solves an edge case bug that came up, where we have one FormulaCurveItem with a constant value ('A': 'f://4') that is referenced in another FormulaCurveItem ('B': 'f://{A}*2'). An error would be thrown:
```
File "/afs/slac.stanford.edu/u/cd/zdomke/workspace/pydm/pydm/widgets/timeplot.py", line 670, in redrawPlot
curve.redrawCurve(min_x=min_x, max_x=max_x)
File "/afs/slac.stanford.edu/u/cd/zdomke/workspace/pydm/pydm/widgets/archiver_time_plot.py", line 622, in redrawCurve
self.evaluate()
File "/afs/slac.stanford.edu/u/cd/zdomke/workspace/pydm/pydm/widgets/archiver_time_plot.py", line 520, in evaluate
pvValues[pv] = pvLiveData[pv][1][pvIndices[pv] - 1]
IndexError: index -1 is out of bounds for axis 0 with size 0
```
This is because when a formula was a constant, no data was actually saved …

FIX: Store Data for FormulaCurveItem with Constant Value

---

pydm/tests/widgets/test_curve_editor.py
pydm/widgets/archiver_time_plot_editor.py
pydm/widgets/axis_table_model.py
pydm/widgets/baseplot_table_model.py

This started with adding basic tests to check the validity of 3 `QAbstractTableModel` classes:
- `BasePlotAxesModel`
- `BasePlotCurvesModel`
- `PyDMArchiverTimePlotCurvesModel`
I fixed the issues that came up when the models were declared invalid. These fixes include:
- In `flags()`, the models check the validity of the given `QModelIndex`
- In `data()` and `setData()`, returns `None` instead of an empty `QVariant` object. This is done because `QVariant` is not really needed in PyQt like it is in Qt. In some cases where it makes more sense, I replaced the `QVariant` with empty strings.
- While [this documentation](https://doc.qt.io/qtforpython-5/PySide2/QtCore/QAbstractItemModel.html#PySide2.QtCore.PySide2.QtCore.QAbstractItemModel.data) suggests returning an invalid QVariant, it doesn't …

FIX: Check Validity of QAbstractTableModel Classes

---

pydm/main_window.py
pydm/tests/test_main_window.py

Also add testcase, which can be expanded later to test more of the main window menubar options.

ENH: make main window menubar action for 'Enter Fullscreen' toggle to 'Exit Fullscreen' when in fullscreen view.

---

pydm/data_plugins/epics_plugins/pva_codec.py

If you specify python 3.10+ in the conda install,
numpy will then be installed with the latest version 2.20.
Updated numpy has removed np.compat.long, which was for compatibility with python 2's 'long' variable, and we don't support python 2. ('long' is replaced with the just an expanded 'int' in python 3).

MNT: fix error when using numpy 2+

---

pydm/widgets/archiver_time_plot_editor.py

In `AbstractItemModel.data` and `AbstractItemModel.setData`, returns `None` instead of an empty `QVariant` object. This is done because QVariant is not really needed in PyQt like it is in Qt.
While [this documentation](https://doc.qt.io/qtforpython-5/PySide2/QtCore/QAbstractItemModel.html#PySide2.QtCore.PySide2.QtCore.QAbstractItemModel.data) suggests returning an invalid QVariant, it doesn't specify what an invalid QVariant should be
[This documentation](https://doc.qt.io/qtforpython-5/considerations.html#qvariant) suggests that `None` can be used as an invalid `QVariant`.

DEP: Remove References to Deprecated QVariant

---

pydm/tests/widgets/test_shell_command.py

Switch outdated tests to use .commands, which is not deprecated. And supress the error for when intentionally using deprecated call.
Fixing this b/c I want to clear out the old warnings before I deal with some warnings from adding pyside6 support.

MNT: stop warnings during tests from using deprecated .command property

---

pydm/widgets/related_display_button.py

We noticed a niche issue when it comes to using the `PyDMRelatedDisplayButton` widget outside of a pydm application.
In these cases, the display that gets loaded is orphaned, and will eventually get garbage collected because there are no python references to the display object. This isn't a problem inside the pydm applications because in these cases we either start a new process, which retains a reference to the screen, or we replace our main widget with the new widget, so the window retains a reference.
Users have been reporting that their displays would "crash with no error message" and I tracked it down to this.
In this PR, I create a list and stash these related displays in the list. This means they have one python reference, so they aren't closed automatically.

FIX: maintain reference to related displays to avoid gc

---

pydm/tests/widgets/test_shell_command.py
pydm/widgets/shell_command.py

This PR was created to address a bug, but in the process it grew to become a minor rework of how we parameterize `PyDMShellCommand` widgets.
In the `PyDMShellCommand` widget, we've been using `subprocess.PIPE` for the `stdout` and `stderr` arguments to `subprocess.Popen` when we don't want these streams to show in the caller's terminal.
Unfortunately, this creates a problem. If the subprocess generates a certain amount of stdout or stderr, the pipe "fills up" so to speak, and then the subprocess is stuck waiting on being allowed to write more to stdout. The subprocess will then "freeze" until the calling process reads enough of the stdout buffer to allow the subprocess to finish writing data.
I'm not sure if this affects all flavors of subprocesses, but this definitely affects shell …

ENH/FIX: shell command output options

---

.github/workflows/run-tests.yml
README.md
conda-recipe/meta.yaml

Before it was using the pip '.txt' package files to install packages with conda. 
But that doesn't mimic how we instruct users to locally install packages with conda+pip, and causes some issues with packages in coda (ex=p4p) being outdated compared to pip and causing actions setup to fail. 
The outdated packages are why this patch is needed to later add tests for most recent python version (can't do now b/c pyqt5 only supports up to 3.10, but pyside6 support will test with python latest)
Also this drops python 3.8 automated tests, and update docs and conda recipe for 3.9+ (min supported python version).

MNT: make gh actions setup use conda and pip to install packages

---

pydm/widgets/slider.py

Currently a value error can be thrown when dragging the handle of a slider that has floating point values. This fix rounds and casts to int the value change while dragging the handle of the PyDMSlider

FIX: Small change to addess a valueError in PyDMSlider when they are being dragged 

---

pydm/widgets/axis_table_model.py
pydm/widgets/baseplot_table_model.py

Removing 2 if statements that were adapted from a check for empty QVariants. Since references to QVariants were removed entirely from PyDM, these checks aren't necessary anymore.
Including these checks resulted in the error below when entering data into the model:
`AttributeError: 'str' object has no attribute 'toString'`

DEP: Remove Deprecated QVariant Checks

---

pydm/tests/widgets/test_drawing.py
pydm/tests/widgets/test_label.py
pydm/tests/widgets/test_related_display_button.py
pydm/tests/widgets/test_slider.py
pydm/tests/widgets/test_symbol_editor.py
pydm/utilities/__init__.py
pydm/widgets/related_display_button.py

Also adding these b/c RULE_PROPERTIES system is going to get reworked to work with qt6/pyside6. (these tests should remain same while implementation changes)

TST: add tests for objects the use PyDMPrimitiveWidget's RULE_PROPERTIES

---

.github/workflows/run-tests.yml
LICENSE.md

Before looking too much into the intermittent failures on mamba setup during the `conda-incubator/setup-miniconda`, update the action to the latest version. Updates checkout action too.
Have seen recently among others:
`Error: The process '/usr/share/miniconda3/condabin/mamba' failed with exit code 1`
```
error    libmamba Error when extracting package: Could not chdir include/openssl/rsaerr.h
openssl-1.1.1w-hd590300_0.conda extraction failed
Found incorrect download: openssl. Aborting
```
etc...
Will make a separate issue if they continue.

MNT: Update versions of checkout and setup-miniconda actions

---

.github/workflows/run-tests.yml

Some intermittent issues cause test to just run forever until hit 6 hour default timeout to fail ex: https://github.com/slaclab/pydm/actions/runs/12777372530/job/35622564890
Longest run of tests is on windows/mac and seems to take about 5 mins, so 30 min timeout should be long enough.

MNT: make gh-actions timeout and fail at 30 mins (instead of 6 hour default)

---

pydm/data_plugins/epics_plugins/p4p_plugin_component.py
pydm/tests/data_plugins/test_p4p_plugin_component.py

Adds an additional case in the p4p_plugin_component module for Numpy integers. 
Tested using an in-development GUI on the same PV described in #1119 
Closes #1119

BUG: Add a case in p4p_plugin_component.py for Numpy integers.

---

pydm/tests/widgets/test_timeplot.py
pydm/widgets/datetime.py
pydm/widgets/display_format.py
pydm/widgets/enum_button.py
pydm/widgets/image.py
pydm/widgets/label.py
pydm/widgets/line_edit.py
pydm/widgets/logdisplay.py
pydm/widgets/template_repeater.py
pydm/widgets/timeplot.py

This should fix main issue making it difficult to support both PyQt5 and PySide6 enums at same time!
The need for inheritance was b/c  when an enum gets written to a ui file by designer, its in the form of \<widget class name\>::\<enum value\> (ex='PyDMLabel::STRING').
On loading the ui file, unless the widget class had subclassed the enum class it wouldn't find the definition of the enum.
The issue with subclassing the enum is:  in qt6 enums must inherit from python 'Enum' (ex = class MyNewEnum(Enum)), and these classes can not be inherited from.
So instead we can just re-declare the values of the enum in the class itself, mimicking if the class had inherited from the enum.

MNT: remove widget classes inheritance from enum, as preperation for qt6 enum support

---

dev-requirements.txt
pydm/tests/data_plugins/test_psp_plugin_component.py
requirements.txt
run_tests.py

the psp test can be enabled (except still unsupported on windows) if we switch to using correct pyca package from github. (pyca from PyPI was the wrong package)
This fixes issue where user downloads pydm and runs the tests with pytest cmd directly (instead of run_tests.py) and gets 'no module named psp' failure. 
This failure seems to suggest to user to 'pip install psp', which is the wrong package and leads to further confusion.

MNT: stop install wrong pyca package through pip, and enabled psp test which uses pyca's psp library

---

pydm/display.py

The pyqt5 uic lib seems to be replaced by cmdline tool in pyside6, https://doc.qt.io/qtforpython-6/tools/pyside-uic.html.

ENH: Add Pyside6 compatible UI file compilation

---

pydm/widgets/archiver_time_plot.py
pydm/widgets/baseplot.py
pydm/widgets/multi_axis_plot.py

Fixes some bugs found in the ErrorBarItems for the ArchiverPlotCurveItem. Below are a few of the problems I found and their solutions.
- Moving a curve to a new y-axis did not move the curve's error bars, they were just left on the previous axis. I fixed this by adding a `y_axis_name.setter` override in ArchivePlotCurveItem. This setter calls the `super().y_axis_name.setter`, but then moves the associated error bar as well.
- Setting a y-axis & curve to use log mode in the y direction did not set log mode for the error bars, their values were just off. This required overriding the curve's `setLogMode` method to update the error bar's data in addition to the `super()` method.
- Error bars do not get removed from the plot when the curve is removed. The solution was to use the …

FIX: Set log mode and link/unlink ArchivePlotCurveItem.ErrorBarItems

---

pydm/widgets/base.py
pydm/widgets/drawing.py
pydm/widgets/embedded_display.py
pydm/widgets/label.py
pydm/widgets/related_display_button.py
pydm/widgets/slider.py
pydm/widgets/symbol.py

PySide6 uses the Shiboken library for its python bindings, which has stricter rules for class definition than PyQt's sip library. 
This means that pyside6 doesn't allow us to pass 'new_properties' to classes in their class-definitions.
Instead, we can store the properties as a class attribute defined inside the classes. 
Note: we don't use '.self' here for the variable since we want the properties to be defined at time of class definition and stay the same across all objects of the class.
And the RULE_PROPERTIES are getting tested already by this recent patch: https://github.com/slaclab/pydm/pull/1151

MNT: make RULE_PROPERTIES work with pyside6

---

pydm/data_plugins/plugin.py
pydm/tests/conftest.py
pydm/widgets/base.py

syntax is described here in the pyside6 docs:
https://doc.qt.io/qtforpython-6/tutorials/basictutorial/signals_and_slots.html#overloading-signals-and-slots-with-different-types
using this syntax doesn't have effect on pyqt5 functionality.

MNT: switch signal type overloading to use syntax that works for both pyqt5 and pyside6

---

pydm/utilities/shortcuts.py

(QtCore.Qt.ALT | QtCore.Qt.Key_C) and (QtCore.Qt.ALT + QtCore.Qt.Key_C) both still result 'ALT + C' on qt5
https://doc.qt.io/qt-6/qkeysequence.html#details

MNT: '|' is only supported way to combine macros in qt6, and still works also for qt5

---

pydm/tests/widgets/test_pushbutton.py
pydm/tests/widgets/test_related_display_button.py
pydm/tests/widgets/test_shell_command.py

This approach is required for pyside6(qt6), but also still works and seems to be correct way to access pixmaps in pyqt5(qt5).
https://doc.qt.io/qt-6/qstyle.html#StandardPixmap-enum 
https://doc.qt.io/qt-5/qstyle.html#StandardPixmap-enum

MNT: in tests, access style pixmaps using StandardPixmap

---

pydm/widgets/archiver_time_plot.py
pydm/widgets/baseplot.py
pydm/widgets/drawing.py

While ints works on pyqt5(qt5), PenStyle enums should be passed according to the docs. (https://doc.qt.io/qt-5/qpen.html#setStyle)
And with pyside6(qt6) ints do not work, b/c it seems to have stricter typing than pyqt5, so we must use the enums.

MNT: Be sure we use Qt.PenStyle enums for setting pen style, not ints.

---

examples/camviewer/camviewer.py

Docs point to currentTextChanged being the correct signal to use here: https://doc.qt.io/qt-6/qcombobox.html#activated

MNT: use the correct signal for comboboxes in the camviewer example, stops error on pyside6

---

pydm/tests/widgets/test_rules.py

been hitting random github-actions failures of the tests on windows (ex: https://github.com/slaclab/pydm/actions/runs/13847730884/job/38750781319),
having to rerun on almost every new patch to get passing
my first guess was windows was being a bit slow, so increase the wait time a bit on the failing tests.
i ran windows tests and they are passing 4 times in a row, but maybe im just really lucky here
(this does makes tests a few seconds slower)

MNT: fix github actions windows tests from failing randomly: maybe windows is slow, try waiting a few seconds longer

---

pydm/widgets/archiver_time_plot.py

This change prompts the ArchiveTimePlot to get data from the Archiver Appliance every time the x-axis' range changes.
Previously, archive data was only fetched when the user showed a section of the plot that had no data. With this set up, zooming out will fetch a optimized data (averaged w/ min/max error bars), but zooming back in would still optimized data. This results in the "resolution" looking wrong.
Now zooming in on a section will get the data for the time range shown on the plot. This will result in showing the correct "resolution" at all times.

ENH: ArchiveTimePlot Fetch Data on X-Axis Change

---

pydm/widgets/enum_button.py

Calling signal without overloaded int and expecting a button object back, is whats specified in qt5 docs:
https://doc.qt.io/qt-5/qbuttongroup.html#buttonClicked.
This is the same in the qt6 docs, and pyside6 even throws error if signal is not used in this correct way.
Also i think its the newer python im running with pyside6 that doesn't like using enums to index into an array, so use a map for 'class_for_type' instead. 
(using the enum's '.value' should also allow for indexing into an array, but imo using the map is more readable.)

MNT: update enum-button widget's button-group to use proper clicked signal, avoid pyside6 error

---

pydm/application.py

The check already in place:
'if hasattr(Qt, "AA_UseHighDpiPixmaps"):'
was not stopping the warning, I think b/c the attribute still exists in Qt6 (was getting ran), but is marked internally as depreciated.

MNT: stop high-dpi setting warning on pyside6(qt6)

---

pydm/widgets/template_repeater.py

Seems like the newer python im running pyside6 on doesn't like using enums to index into a tuple: "TypeError: tuple indices must be integers or slices, not LayoutType"
so use a map for 'layout_class_for_type' instead. (using the enum's '.value' should allow for indexing into the tuple too, but imo using the map is more readable.)
this works fine still older python

MNT: appease newer python by not using enum to index into tuple

---

pydm/data_plugins/epics_plugins/caproto_plugin_component.py
pydm/data_plugins/epics_plugins/p4p_plugin_component.py
pydm/data_plugins/epics_plugins/psp_plugin_component.py
pydm/data_plugins/epics_plugins/pyepics_plugin_component.py
pydm/data_plugins/local_plugin.py
pydm/data_plugins/plugin.py

pyqt5: missing overload = KeyError
pyside6: missing overload = IndexError
also make plugin channel connecting/disconnecting into a nicer equivalent for-loop, and add catching TypeErrors too (explanation in new comments)
and add comments to explain why we are catching these specific errors.

MNT: pyside6 just throws an IndexError instead when connecting to value_signals not overloaded with the specified type

---

pydm/widgets/channel.py

Corrects for the pyside6 error:
"AttributeError: 'PySide6.QtCore.SignalInstance' object has no attribute 'signal'"
Docs don't seem to say how to compare signals in pyside6,
so i verified by checking 'value_signal_matched' result during tests is same on pyside6 and pyqt5.
also verified with following script which acts as expected:
from PySide6.QtCore import Signal
a = Signal(int)
b = Signal(str)
c = b
print("a is b: ", a is b) # False
print("b is c: ", b is c) # True
print("a == b: ", a == b) # False
print("b == c: ", b == c) # True

MNT: On pyside6 use == for signal comparison (can't use .signal like in  pyqt5)

---

docs/source/installation.rst

Avoid the commercial license of Anaconda and use Miniforge instead, which has fully opensource licence (BSD-3-Clause).
Miniforge is also the listed preferred installer by the conda-forge repository we use anyway.

MNT: instruct users to use conda from Miniforge for it's better licensing.

---

pydm/widgets/base.py
pydm/widgets/byte.py
pydm/widgets/datetime.py
pydm/widgets/drawing.py
pydm/widgets/frame.py
pydm/widgets/image.py
pydm/widgets/label.py
pydm/widgets/related_display_button.py
pydm/widgets/scale.py
pydm/widgets/shell_command.py
pydm/widgets/symbol.py
pydm/widgets/tab_bar.py

There is no issue running on pyqt5, but on pyside6 throws a runtime error when initializing classes that use multiple inheritance of a qt base class and a pydm class.
example class:
```
class PyDMDrawing(QWidget, PyDMWidget, new_properties=_penRuleProperties))
...
def __init__(self, parent=None, init_channel=None):
...
QWidget.__init__(self, parent)
PyDMWidget.__init__(self, init_channel=init_channel)
...
```
The runtime error happens when a call is made in the base class that relies on the qt base class's \_\_init\_\_ call to have completed setting things up (such as 'installEventFilter()).
example error:
```
-> self.installEventFilter(self)
RuntimeError: '__init__' method of object's base class (PyDMDrawingImage) not called
```
This error is thrown despite that we explicitly call each …

MNT: Move some calls to children classes to stop pyside6 throwing an error about __init__ in classes that use multiple inheritence.

---

pydm/data_plugins/plugin.py
pydm/tests/data_plugins/test_plugin.py

Addresses #1186. 
When calling set_channel on a PyDMWidget, the process is:
- Call disconnect() on any channels the widget is already connected to
- Disconnect signals/slots and decrement the listener count on the `PyDMConnection` associated with the address
- If the listener count hits 0, close out the `PyDMConnection` for that address entirely
- Then establish the new channel for the widget
The problem in #1186 seems to be that the `value_signal` is not disconnected, so if there is still an active listener such that the connection is not closed out entirely, that signal remains active and will continue to send even though the channel should have been replaced.
This should fix it by ensuring the `value_signal` is disconnected as part of `remove_listener` along with all the other signals. …

FIX: Disconnect the value signal when removing a listener from a connection

---

pydm/widgets/baseplot.py

`BasePlotAxisItem.auto_range` was never being read, so setting auto-range to `True` or `False` had no effect on the drawn plot.  By passing assignments on to the linked `ViewBox`, setting auto-range in the baseplot does effect the range of the drawn plot.
Auto-range is also disabled whenever the plot range is manually adjusted.  This is achieved by connecting to `ViewBox.sigRangeChangedManually`.

BUG: connect BasePlotAxisItem auto-range methods to the linked ViewBox auto-range methods

---

pydm/main_window.py
pydm/tests/test_main_window.py

Fixes #1114 
As suspected in #1114, the previous instance of the Display class was not getting garbage collected when using reload display. Checking what still had references to it after a reload showed that it was only the `PyDMMainWindow.home_widget` which still had a reference to it.
Fix is to clear that out during the reload. The home widget will get correctly set to the refreshed version of the display later on as part of the reload process so the home button continues to work fine after this change.
Verified that the test display from #1114 now only ticks once per second after reloading when applying this fix. Added a unit test that catches this issue, fails prior to this fix, and passes after.

FIX: Ensure previous instance of display class is fully cleaned up after reloading it

---

pydm/widgets/archiver_time_plot.py

Fixing a bug that I introduced to `PyDMArchiverTimePlot.updateXAxis` in PR #1172. Jesse mentioned that I created this bug. I intended to fix it and forgot to address it.
The bug comes from removing the parameter `update_immediately` from the declaration of `updateXAxis`. This PR adds it back in.

FIX: Fixing bug with updateXAxis def

---

pydm/tests/widgets/test_eventplot.py

When running on pyside6, this error is not thrown on examples or when running test files individually. But only when running all the tests in sequence (with pytest cmd directly or run_tests.py), was getting following error:
```
Traceback (most recent call last):
File "/home/nolan-work/repos/pydm/pydm/widgets/eventplot.py", line 403, in redrawPlot
curve.redrawCurve()
File "/home/nolan-work/repos/pydm/pydm/widgets/eventplot.py", line 195, in redrawCurve
self.setData(
File "/home/nolan-work/miniforge3/envs/pydm-environment-pyside6/lib/python3.10/site-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 833, in setData
self.updateItems( styleUpdate = self.property('styleWasChanged') )
RuntimeError: Internal C++ object (EventPlotCurveItem) already deleted.
```
Calling a redraw of the …

TST: fix error during tests on pyside6 with c++ internal object deletion

---

pydm/widgets/archiver_time_plot.py

PyDMArchiverTimePlot.clearCurves tries to remove the error bars from its curves before removing the curves themselves, which is throwing an AttributeError if an error bar doesn't have a view box.  This situation can occur when first setting curves in a model, when no curves or error bars have been set up.
This commit fixes the error by delegating error bar removal to the curve itself via ArchivePlotCurveItem.remove_error_bar

BUG: properly remove error bars in time plot's clearCurves

---

pydm/connection_inspector/connection_inspector.py

User-defined sorting of the connections table is no longer reset when connections are updated. This also allows exporting the connection data with the user-defined sort order.
Closes #708

FIX: connection inspector no longer resets user-defined sort when connections are updated

---

pydm/widgets/shell_command.py

Adds one/two entries to the context menu of the shell command widgets. Some screenshots will help explain better than words:
Closes #1225

ENH: add context menu options to PyDMShellCommand to display and copy their command(s)

---

pydm/tests/utilities/test_remove_protocol.py
pydm/utilities/__init__.py
pydm/utilities/remove_protocol.py

Replaces `urllib.parse.urlparse` with a regex. The params and fragment values have been dropped from the returned tuple, as they were unused and could possibly break up valid channel names.
Closes #1118

FIX: use a regex to parse a given URI instead of urllib

---

pydm/tests/widgets/test_timeplot.py

while we import QSignalSpy thru qtpy, it doesn't seem to
implement an abstraction over it so its up to us to handle.

TST: make timeplot testcase work for pyside6 too

---

pydm/data_plugins/__init__.py
pydm/tests/widgets/test_channel.py

We only defined and only accept the protocol in channel addresses when its all lowercase. ('pva', 'calc', 'ca', etc) \
Used in an address, it looks like: 'ca://test:example'.
But sometimes we set the protocol to be uppercase, like in the testing when we use 'CA://MTEST'.
This fix just converts all protocols into lowercase to avoid an error, which imo is more user friendly than enforcing case-sensitive protocols
Found this issue when running tests on pyside6 since with it logger.error() calls are printed and fail the tests, but on pyqt5 we need to set 'log_cli=true' to get the same behavior. (which we currently don't do, but i'll set it in followup patch)

BUG: fix error when establishing plugin connections with protocols in all caps.

---

docs/source/tutorials/intro/launcher.rst
pydm/application.py
pydm/main_window.py
pydm/tests/utilities/test_utilities.py
pydm/utilities/__init__.py
pydm/widgets/drawing.py
pydm/widgets/embedded_display.py
pydm/widgets/related_display_button.py
pydm/widgets/template_repeater.py
pydm_launcher/main.py

Let me know if you would like any changes to the implementation, such as a command-line argument to enable this behavior. Possibly unknowingly changing existing behavior of a display, or having a collision between two displays with the same name worries me. I also disabled this behavior everywhere I found unrelated to loading displays, but maybe the parameter should be disabled by default and enabled in display loading code? Let me know your thoughts, I'm very new to this codebase.
Hopefully closes #1065

ENH: allow displays to be loaded from subdirectories of search paths

---

pydm/tests/widgets/test_base.py
pydm/widgets/__init__.py
pydm/widgets/base.py
pydm/widgets/checkbox.py
pydm/widgets/datetime.py
pydm/widgets/enum_button.py
pydm/widgets/enum_combo_box.py
pydm/widgets/line_edit.py
pydm/widgets/pushbutton.py
pydm/widgets/spinbox.py
pydm/widgets/waveformtable.py

This fixes middle-click functionality issues on some widgets (like
PyDMPushButton)
In https://github.com/slaclab/pydm/pull/1181
(https://github.com/nstelter-slac/pydm/commit/c949c0272565f89add821b1116e0793881bc09af), we moved some calls from
the base widgets into the subclasses to appease pyside6 warnings.
These calls should have been added to all child classes of PyDMWritableWidget and PyDMWidget.
(note this setup is not intended to be done for widgets that subclass
PyDMPrimitiveWidget directly)
And expand testcase to check if this setup is getting done by checking
all the relevant widget class's middle-click functionality.
(this is still quite fast (~ 1 sec) even when checking all the classes)
Also add missing classes to be exported from module as part of \_\_all\_\_.

BUG: ensure all PyDMWritableWidget and PyDMWidget subclasses get init'd correctly.

---

examples/datetime/datetime.ui
pydm/tests/widgets/test_datetime_edit.py
pydm/tests/widgets/test_datetime_label.py
pydm/widgets/datetime.py

- Fixed the `datetime` example erroring about implicit type conversion
- Fixed `PyDMDateTimeEdit` not being able to send the correct value in most cases (for dates further than approx. a week away it was breaking and/or sending negative values)
- Added barebones basic tests for both datetime widgets
- Let me know if I should add more
Closes #1203

FIX: PyDMDateTime weirdness

---

pydm/widgets/byte.py
pydm/widgets/checkbox.py
pydm/widgets/datetime.py
pydm/widgets/drawing.py
pydm/widgets/enum_button.py
pydm/widgets/enum_combo_box.py
pydm/widgets/frame.py
pydm/widgets/image.py
pydm/widgets/label.py
pydm/widgets/line_edit.py
pydm/widgets/nt_table.py
pydm/widgets/pushbutton.py
pydm/widgets/related_display_button.py
pydm/widgets/scale.py
pydm/widgets/shell_command.py
pydm/widgets/slider.py
pydm/widgets/spinbox.py
pydm/widgets/symbol.py
pydm/widgets/tab_bar.py
pydm/widgets/waveformtable.py

Some more pyside6 weirdness was that events such as middle-click's were not getting propated from child classes of PyDMWidget/PyDMWritableWidget to their parent's eventFilter() funcs.
This is even after an earlier fix for event-handling, which made pyqt5's events work again but not pyside6's.
The problem seems to be that pyside6 is unsure of which parent class to propagate the events to, and explicity declaring this in the eventFilter() func of the child classes fixes the issue.

MNT: on pyside6, ensure events get filtered properly into pydm's base classes.

---

pydm/widgets/base.py

linux (x window system) has multiple clipboards, and we are currently just setting the 'Selection' clipboard which pastes by pressing middle-click.
while 'Selection' is only valid for linux, 'Clipboard' is still valid on linux also, so we can call 'setText' with it to enable pasting with 'Ctrl-V' on linux.

ENH: make middle-click copy-to-clipboard feature on widgets copy also to the clipboard that pastes with 'Ctrl-v'

---

pydm/main_window.py

seems like b4 we were getting the filepath in a very roundabout way:
- `QFileDialog.getOpenFileName()` returns a tuple where the 1st element is the full file-path
- we were then converting tuple into string, splitting it on the ' char to get something like` ["'(','/home/nolan-work/repos/pydm/examples/label/style.qss', ', ', 'PyDMStylesheets (*.qss *.css)', ')'",]` and then just selecting the 2nd element of the split result.
we can instead just directly grab the first element of the output tuple of `QFileDialog.getOpenFileName()`. 
this fix also stops the `FileNotFoundError` caused by the `if ss_filename:` always being True b/c `ss_filename` was a tuple b4
(and when nothing selected ('','') got returned from `getOpenFileName()`, which is True in a conditional)

BUG: cleanup stylesheet readin code, also stops FileNotFoundError error when cancel out stylesheet selecting window

---

pydm/display.py
pydm/tests/test_display.py
pydm/tests/widgets/test_baseplot.py
pydm/tests/widgets/test_checkbox.py
pydm/tests/widgets/test_datetime_edit.py
pydm/tests/widgets/test_datetime_label.py
pydm/tests/widgets/test_enum_button.py
pydm/tests/widgets/test_enum_combo_box.py
pydm/tests/widgets/test_frame.py
pydm/tests/widgets/test_label.py
pydm/tests/widgets/test_lineedit.py
pydm/tests/widgets/test_logdisplay.py
pydm/tests/widgets/test_pushbutton.py
pydm/tests/widgets/test_shell_command.py
pydm/tests/widgets/test_slider.py
pydm/tests/widgets/test_spinbox.py
pydm/widgets/datetime.py
pydm/widgets/logdisplay.py
pydm/widgets/nt_table.py
pydm/widgets/tab_bar.py
pydm/widgets/terminator.py

For some widgets that call "\_\_init\_\_(parent=parent)" using the named arg to pass in 'parent'
on pyside6 it was throwing the error "\_\_init\_\_() got an unexpected keyword argument 'parent'"
Most widgets already use the positional arg for passing 'parent':
"\_\_init\_\_(parent)", so this patch switches over those throwing error on
pyside6 to use positional arg.
(note: some plot related widgets still pass a named 'parent' arg to
\_\_init\_\_ and don't cause error, this seems to be related to their diff
class hierarchy and sublcassing of pyqtgraph classes)
Also add checks to tests for if parent gets set properly in widgets.
Also update to use correct signal type for the combobox text change in logdisplay.

MNT: stop passing parent=parent to prevent error on pyside6 with __init__() calls

---

pydm/widgets/archiver_time_plot.py

A small fix which allows FormulaCurveItems to work when the PVs in the formula are connected by at least one option: archive or live. currently all PVs in a formula needs both a live and archived connection to evaluate.

FIX: Gets FormulaCurveItems working for pvs with archived or live connections 

---

pydm/widgets/tab_bar.py

Stops the following error output when running a PyDMTabWidget widget:
```
Traceback (most recent call last):
File "/home/nolan/repos/pydm/pydm/widgets/tab_bar.py", line 36, in eventFilter
return PyDMWritableWidget.eventFilter(self, obj, event)
NameError: name 'PyDMWritableWidget' is not defined. Did you mean: 'PyDMTabWidget'?
```
We do these explicit parent eventFilter() calls in the first place so events to get events to be correctly on pyside6.
This bug got merged in b/c of lacking tests for the PyDMTabWidget, but tests for it and PyDMTerminator and PyDMNTTable will be added shortly.

BUG: make tabwidget call parent eventFilter() of correct parent class.

---

pydm/tests/utilities/test_macro.py
pydm/widgets/base.py

When running pydm using Python 3.12, these 2 places now print `SyntaxWarning` rather than the previous `DeprecationWarning`.
```
SyntaxWarning: invalid escape sequence '\$'
list_of_attributes = [substring.start() for substring in re.finditer("\$\(", new_tip)]
```
Uses raw strings now so that they aren't processed as escape sequences.
See here for more info: https://docs.python.org/3/whatsnew/3.12.html#other-language-changes
Verified that tool tips still parse correctly after applying this change. Verified that the macro test case is still valid (removing the backslash character)

MNT: Syntax warning messages in python 3.12

---

pydm/widgets/archiver_time_plot.py

Added ability to specify number of bins for optimized archive data retrieval per curve
- Added optimized_data_bins parameter to ArchivePlotCurveItem. 
- PYDMArchiverTimePlot.requestDataFromArchiver() checks to see whether the curve has a number of optimized_data_bins specified before using it's own default (preserves current behavior if no optimized_data_bins for the curve has been set)

n data bins

---

.github/workflows/run-tests.yml
CONTRIBUTING.rst
README.md
docs/source/installation.rst

run the following combos:
- 5.12.3 with latest python it supports (3.10) # this is latest pyqt5
with working designer plugins
- 5.15.11 with latest python (3.12) # this is latest pyqt5
next we should add runs for latest pyside6 and python 3.12
also make dev setup instructions easier to find on main github page.

MNT/TST: only do necessary runs in github actions

---

.github/workflows/run-tests.yml

Removes the p4p data plugin test from macOS test runs.
The issue is that the a new version of p4p has been uploaded to conda-forge for the first time in a long while. This version seems to error out when installed alongside the conda-forge version of epicscorelibs.
Rather than attempt to work around it here (the pypi version causes the macOS runner to build epics from source which takes forever, the old 3.5.5 version of p4p doesn't work with python 3.12, carving out these very specific exceptions is just really ugly), it would be faster to fix it on the p4p side which I can do soon.
This just gets the tests passing again for now. And there should be no functional difference in the plugin code being tested between the different operating systems.

TST: Fix macOS test runs

---

pydm/widgets/multi_axis_plot.py
pydm/widgets/multi_axis_viewbox_menu.py

Fixes #1269 
As mentioned in that issue, PySide 6.9.1 will not work due to https://bugreports.qt.io/browse/PYSIDE-3115, but there was also a second issue to fix on the pydm side.
When running PyDM with any pyside6 version, plots using multiple axes would error out because the view boxes associated with those axes were being garbage collected right away unlike in PyQt5.
Fix is just to store the viewboxes in a set so there are strong references to them as along as the main plot containing them is still around. This change is fine, they didn't need to be weak refs in the first place, they are cleaned up correctly if their associated axes go away.
Also includes a fix to ensure the "View All" option in the right-click context menu continues to function properly by setting the plot to …

FIX: Plot view boxes were being garbage collected too soon with pyside6

---

pydm/widgets/analog_indicator.py
pydm/widgets/base.py
pydm/widgets/baseplot.py
pydm/widgets/byte.py
pydm/widgets/datetime.py
pydm/widgets/drawing.py
pydm/widgets/embedded_display.py
pydm/widgets/enum_button.py
pydm/widgets/frame.py
pydm/widgets/image.py
pydm/widgets/label.py
pydm/widgets/line_edit.py
pydm/widgets/logdisplay.py
pydm/widgets/nt_table.py
pydm/widgets/pushbutton.py
pydm/widgets/related_display_button.py
pydm/widgets/scale.py
pydm/widgets/shell_command.py
pydm/widgets/slider.py
pydm/widgets/spinbox.py
pydm/widgets/symbol.py
pydm/widgets/tab_bar.py
pydm/widgets/template_repeater.py
pydm/widgets/terminator.py
pydm/widgets/timeplot.py
pydm/widgets/waveformtable.py
run_tests.py

the current way we use the `@Property` function-decorator doesn't work with pyside6.
the docs for how to declare Properties in pyside6 are
here: https://doc.qt.io/qtforpython-6/PySide6/QtCore/Property.html.
the docs claim that `@Property` should work if you import it from
`PySide6.QtCore`, but from my testing it does not.
what does work is the `Property()` function, which has an equivalent
in pyqt5 `pyqtProperty()`. So the idea of this patch is to switch all
instances of `@Property` to the instead use the function calls, and
conditionally import them depending on the current API.

ENH/MNT: convert all Qt Property declarations to use a way that works for both pyside6 and pyqt5. 

---

pydm/widgets/archiver_time_plot.py
pydm/widgets/timeplot.py

This PR is to address some persistent and new issues with the FormulaCurveItem. 
1. Small spelling mistake in remove_extension_line()
2. Fixes error in remove_error_bar and remove_extension_line leading to a `RuntimeError: Internal C++ object (MultiAxisViewBox) already deleted `
3. An issue with FormulaCurveItems not having 'optimized_data_bins'
4. Formula curves being duplicate on plot legends 
5. FormulaCurveItems not having Address and Units properties 
6. fix case where a formula is made up of constant formulas f://{f://1}+{f://2}

FIX: More Fixes to the FormulaCurveItem

---

.github/workflows/gh-pages.yml
README.md
conda-recipe/meta.yaml
pyproject.toml

min supported python for pydm is now 3.10 (bumped from 3.9)

MNT: change any min python version references to 3.10

---

.github/workflows/gh-pages.yml

This fixes the current documentation job, as well as updating to the latest suggested example from `setup-miniconda` version 3.

DOC: Update github workflow for building the documentation to use the latest version of its actions

---

.github/workflows/run-tests-pyqt5.yml
.github/workflows/run-tests-pyside6.yml
README.md
run_tests.py

for now just pass pyside6 tests regardless, use the result as reference on pyside6 status and not blocking for merge.
made a separate yaml file for pyside6 setup/running to avoid
complicating the pyqt5 yaml file any more.

MNT/TST: add pyside6 testing runs to gh-actions automation 
